import 'dart:convert';
import 'dart:io';

typedef Json = Map<String, dynamic>;
typedef WordSeed = ({
  String word,
  String meaning,
  String pronunciation,
  String en,
  String so,
});

Json vocabulary(
  String word,
  String meaning,
  String type,
  String pronunciation,
  String exampleEnglish,
  String exampleSomali,
  String explanation, [
  String mistake = '',
]) => {
  'englishWord': word,
  'somaliMeaning': meaning,
  'partOfSpeech': type,
  'pronunciation': pronunciation,
  'exampleEnglish': exampleEnglish,
  'exampleSomali': exampleSomali,
  'explanationSomali': explanation,
  'commonMistakeSomali': mistake,
};

List<Json> words(
  List<WordSeed> seeds, {
  String type = 'activity phrase',
}) => seeds
    .map(
      (item) => vocabulary(
        item.word,
        item.meaning,
        type,
        item.pronunciation,
        item.en,
        item.so,
        '${item.word} waa ${item.meaning}. Weedha waxaa loo isticmaalaa jadwal ama hawl maalinle ah.',
      ),
    )
    .toList();

Map<String, String> example(String english, String somali) => {
  'english': english,
  'somali': somali,
};

Json line(String speaker, String english, String somali) => {
  'speaker': speaker,
  'english': english,
  'somali': somali,
};

Json dialogue(String title, List<Json> lines) => {
  'titleSomali': title,
  'lines': lines,
};

Json exercise(
  String id,
  String type,
  String question,
  List<String> options,
  String answer,
  String explanation,
) => {
  'id': id,
  'type': type,
  'question': question,
  'options': options,
  'correctAnswer': answer,
  'explanationSomali': explanation,
};

Json grammar({
  required String titleEnglish,
  required String titleSomali,
  required String explanation,
  required String rule,
  required String structure,
  required List<Map<String, String>> positive,
  required List<Map<String, String>> negative,
  required List<Map<String, String>> questions,
  required List<String> mistakes,
}) => {
  'titleEnglish': titleEnglish,
  'titleSomali': titleSomali,
  'explanationSomali': explanation,
  'rule': rule,
  'sentenceStructure': structure,
  'positiveExamples': positive,
  'negativeExamples': negative,
  'questionExamples': questions,
  'commonMistakesSomali': mistakes,
  'practiceQuestions': const [],
};

List<Json> practices(
  String id,
  List<Json> vocabulary,
  List<Map<String, String>> examples, {
  required String fillQuestion,
  required List<String> fillOptions,
  required String fillAnswer,
  required String grammarQuestion,
  required List<String> grammarOptions,
  required String grammarAnswer,
  required String mistakeQuestion,
  required List<String> mistakeOptions,
  required String mistakeAnswer,
  required String arrangeQuestion,
  required String arrangeAnswer,
  required String readingQuestion,
  required List<String> readingOptions,
  required String readingAnswer,
  required String dialogueQuestion,
  required List<String> dialogueOptions,
  required String dialogueAnswer,
  required String speaking,
  required String writing,
  bool review = false,
}) {
  final result = <Json>[
    exercise(
      '$id-p01',
      'multipleChoice',
      '“${vocabulary[0]['englishWord']}” maxay ka dhigan tahay?',
      [
        vocabulary[2]['somaliMeaning'] as String,
        vocabulary[0]['somaliMeaning'] as String,
        vocabulary[3]['somaliMeaning'] as String,
        vocabulary[1]['somaliMeaning'] as String,
      ],
      vocabulary[0]['somaliMeaning'] as String,
      '${vocabulary[0]['englishWord']} macnihiisu waa ${vocabulary[0]['somaliMeaning']}.',
    ),
    exercise(
      '$id-p02',
      'fillInTheBlank',
      fillQuestion,
      fillOptions,
      fillAnswer,
      '“$fillAnswer” ayaa jumladda ka dhigaya mid sax ah.',
    ),
    exercise(
      '$id-p03',
      'matchWords',
      'Isku aadi “${vocabulary[1]['englishWord']}” iyo macnihiisa.',
      [
        vocabulary[3]['somaliMeaning'] as String,
        vocabulary[2]['somaliMeaning'] as String,
        vocabulary[1]['somaliMeaning'] as String,
        vocabulary[0]['somaliMeaning'] as String,
      ],
      vocabulary[1]['somaliMeaning'] as String,
      '${vocabulary[1]['englishWord']} waxaa loola jeedaa ${vocabulary[1]['somaliMeaning']}.',
    ),
    exercise(
      '$id-p04',
      'chooseGrammar',
      grammarQuestion,
      grammarOptions,
      grammarAnswer,
      'Qaabka saxda ahi waa “$grammarAnswer”. Subject-ka iyo helper-ka ayaa go’aamiya qaabka falka.',
    ),
    exercise(
      '$id-p05',
      'multipleChoice',
      mistakeQuestion,
      mistakeOptions,
      mistakeAnswer,
      'Saxitaanku waa “$mistakeAnswer”. Marka do/does/don’t/doesn’t jiro, base verb ayaa la isticmaalaa.',
    ),
    exercise(
      '$id-p06',
      'arrangeSentence',
      arrangeQuestion,
      const [],
      arrangeAnswer,
      'Kala horreynta saxda ahi waa “$arrangeAnswer”.',
    ),
    exercise(
      '$id-p07',
      'englishToSomali',
      'Turjun: ${examples[0]['english']}',
      [
        examples[3]['somali']!,
        examples[2]['somali']!,
        examples[0]['somali']!,
        examples[1]['somali']!,
      ],
      examples[0]['somali']!,
      'Turjumaadda saxda ahi waxay gudbinaysaa hawsha, qofka iyo waqtiga.',
    ),
    exercise(
      '$id-p08',
      'somaliToEnglish',
      'U beddel English: ${examples[1]['somali']}',
      [
        examples[4]['english']!,
        examples[1]['english']!,
        examples[0]['english']!,
        examples[3]['english']!,
      ],
      examples[1]['english']!,
      'Qaabka dabiiciga ah waa “${examples[1]['english']}”.',
    ),
    exercise(
      '$id-p09',
      'readingComprehension',
      readingQuestion,
      readingOptions,
      readingAnswer,
      'Jawaabta “$readingAnswer” waxay si toos ah uga timid routine-ka ama tusaalaha la akhriyey.',
    ),
    exercise(
      '$id-p10',
      'readingComprehension',
      dialogueQuestion,
      dialogueOptions,
      dialogueAnswer,
      'Wada hadalka si taxaddar leh u akhri; jawaabta saxda ahi waa “$dialogueAnswer”.',
    ),
    exercise(
      '$id-p11',
      'speakingPrompt',
      speaking,
      const [],
      'Teacher review',
      'Isticmaal routine male-awaal ah haddii aadan rabin xogtaada dhabta ah.',
    ),
    exercise(
      '$id-p12',
      'shortWriting',
      writing,
      const [],
      'Teacher review',
      'Hubi subject-ka, falka, time expression-ka iyo full stop-ka.',
    ),
  ];
  if (review) result.addAll(reviewExtras(id));
  return result;
}

List<Json> reviewExtras(String id) => [
  exercise(
    '$id-p13',
    'multipleChoice',
    'Wake up iyo get up maxay ku kala duwan yihiin?',
    [
      'Isku macne buuxa ayay yihiin',
      'Wake up waa hurdada ka kac; get up waa sariirta ka soo kac',
      'Get up waa seexo',
      'Wake up waa shaqo aadid',
    ],
    'Wake up waa hurdada ka kac; get up waa sariirta ka soo kac',
    'Wake up wuxuu ka bilaabmaa baraarugga; get up waa ka soo bixidda sariirta.',
  ),
  exercise(
    '$id-p14',
    'fillInTheBlank',
    'She ___ English every day.',
    ['study', 'studys', 'studies', 'studying'],
    'studies',
    'Study wuxuu consonant + y ku dhammaadaa; she studies.',
  ),
  exercise(
    '$id-p15',
    'fillInTheBlank',
    'He ___ television in the evening.',
    ['watch', 'watchs', 'watches', 'watchies'],
    'watches',
    'Watch wuxuu qaataa -es: watches.',
  ),
  exercise(
    '$id-p16',
    'multipleChoice',
    'Kee ayaa negative sax ah?',
    ['She doesn’t goes.', 'She don’t go.', 'She doesn’t go.', 'She not goes.'],
    'She doesn’t go.',
    'Doesn’t ka dib base verb go ayaa yimaada.',
  ),
  exercise(
    '$id-p17',
    'multipleChoice',
    'Kee ayaa question sax ah?',
    ['Does he works?', 'Do he work?', 'Does he work?', 'He does work?'],
    'Does he work?',
    'Does + he + base verb work.',
  ),
  exercise(
    '$id-p18',
    'fillInTheBlank',
    '___ they study English?',
    ['Does', 'Do', 'Are', 'Is'],
    'Do',
    'They waxaa question ahaan la socda do.',
  ),
  exercise(
    '$id-p19',
    'fillInTheBlank',
    'I ___ eat breakfast before school.',
    ['always', 'am always', 'does always', 'always am'],
    'always',
    'Main verb ka hor: I always eat.',
  ),
  exercise(
    '$id-p20',
    'multipleChoice',
    'She is ___ early.',
    ['always', 'always is', 'does always', 'early always is'],
    'always',
    'Verb to be ka dib: She is always early.',
  ),
  exercise(
    '$id-p21',
    'arrangeSentence',
    'Kala hagaaji: work / at / starts / He / eight',
    const [],
    'He starts work at eight.',
    'He + starts + object + time.',
  ),
  exercise(
    '$id-p22',
    'multipleChoice',
    '“Finally” maxay muujisaa?',
    ['Bilowga', 'Su’aal', 'Tallaabada ugu dambaysa', 'Diidmo'],
    'Tallaabada ugu dambaysa',
    'Finally waxaa lagu hordhigaa hawsha ugu dambaysa.',
  ),
  exercise(
    '$id-p23',
    'englishToSomali',
    'Turjun: “They rarely eat outside.”',
    [
      'Mar kasta dibadda ayay wax ku cunaan.',
      'Si dhif ah ayay dibadda wax ugu cunaan.',
      'Marnaba ma shaqeeyaan.',
      'Mararka qaar ayay seexdaan.',
    ],
    'Si dhif ah ayay dibadda wax ugu cunaan.',
    'Rarely waa si dhif ah.',
  ),
  exercise(
    '$id-p24',
    'speakingPrompt',
    'Samee role-play: hal qof ha weydiiyo routine-ka, qofka kalena ha kaga jawaabo do/does, times iyo frequency words.',
    const [],
    'Teacher review',
    'Isticmaal ugu yaraan afar su’aalood iyo afar jawaabood.',
  ),
  exercise(
    '$id-p25',
    'shortWriting',
    'Qor routine male-awaal ah oo 8–10 jumladood ah; ku dar first, then, after that, frequency adverb iyo finally.',
    const [],
    'Teacher review',
    'Hubi Present Simple iyo isku xirka hawlaha.',
  ),
];

Json lesson({
  required int number,
  required String titleEnglish,
  required String titleSomali,
  required String description,
  required List<String> objectives,
  required String type,
  required int minutes,
  required List<Json> vocabulary,
  Json? grammarTopic,
  required List<Map<String, String>> examples,
  required List<Json> dialogues,
  required List<Json> exercises,
  required String speaking,
  required String writing,
  required String summary,
}) {
  final id = 'a1-u05-l${number.toString().padLeft(2, '0')}';
  return {
    'id': id,
    'levelId': 'A1',
    'unitId': 'a1-u05',
    'lessonNumber': number,
    'titleEnglish': titleEnglish,
    'titleSomali': titleSomali,
    'shortDescriptionSomali': description,
    'learningObjectives': objectives,
    'lessonType': type,
    'estimatedMinutes': minutes,
    'difficulty': 'beginner',
    'isLocked': number != 1,
    'requiredPreviousLessonId': number == 1
        ? null
        : 'a1-u05-l${(number - 1).toString().padLeft(2, '0')}',
    'vocabulary': vocabulary,
    'grammar': grammarTopic,
    'examples': examples,
    'dialogues': dialogues,
    'practiceExercises': exercises,
    'speakingPractice': speaking,
    'writingPractice': writing,
    'summarySomali': summary,
    'quizQuestions': exercises
        .take(3)
        .toList()
        .asMap()
        .entries
        .map(
          (entry) => {
            ...entry.value,
            'id': '$id-q${(entry.key + 1).toString().padLeft(2, '0')}',
          },
        )
        .toList(),
  };
}

List<Json> morningWords() => words([
  (
    word: 'Wake up',
    meaning: 'Hurdada ka kac/baraarug',
    pronunciation: 'weyk ap',
    en: 'I wake up at six.',
    so: 'Waxaan hurdada ka kacaa lixda.',
  ),
  (
    word: 'Get up',
    meaning: 'Sariirta ka soo kac',
    pronunciation: 'get ap',
    en: 'I get up after the alarm.',
    so: 'Waxaan sariirta ka soo kacaa digniinta kadib.',
  ),
  (
    word: 'Make the bed',
    meaning: 'Sariirta hagaaji',
    pronunciation: 'meyk dha bed',
    en: 'I make the bed every morning.',
    so: 'Subax kasta sariirta waan hagaajiyaa.',
  ),
  (
    word: 'Wash my face',
    meaning: 'Wajigayga dhaq',
    pronunciation: 'wosh maay feys',
    en: 'I wash my face.',
    so: 'Wajigayga waan dhaqaa.',
  ),
  (
    word: 'Brush my teeth',
    meaning: 'Ilkahayga caday',
    pronunciation: 'brash maay tiith',
    en: 'I brush my teeth every morning.',
    so: 'Subax kasta ilkahayga waan cadayaa.',
  ),
  (
    word: 'Take a shower',
    meaning: 'Qubayso',
    pronunciation: 'teyk a shaawar',
    en: 'I take a shower at six thirty.',
    so: 'Waxaan qubaystaa lixda iyo badhka.',
  ),
  (
    word: 'Get dressed',
    meaning: 'Dhar xidho',
    pronunciation: 'get drest',
    en: 'She gets dressed early.',
    so: 'Waxay dharka xidhataa goor hore.',
  ),
  (
    word: 'Pray',
    meaning: 'Tuko',
    pronunciation: 'prey',
    en: 'I pray in the morning.',
    so: 'Subaxdii waan tukadaa.',
  ),
  (
    word: 'Eat breakfast',
    meaning: 'Quraac cun',
    pronunciation: 'iit brek-fast',
    en: 'I eat breakfast before school.',
    so: 'Waxaan quraacdaa iskuulka ka hor.',
  ),
  (
    word: 'Drink tea',
    meaning: 'Shaah cab',
    pronunciation: 'drink tii',
    en: 'We drink tea at home.',
    so: 'Guriga ayaan shaah ku cabnaa.',
  ),
  (
    word: 'Leave home',
    meaning: 'Guriga ka bax',
    pronunciation: 'liiv hoom',
    en: 'I leave home at seven.',
    so: 'Waxaan guriga ka baxaa toddobada.',
  ),
  (
    word: 'Go to school',
    meaning: 'Iskuulka aad',
    pronunciation: 'goo tu skuul',
    en: 'They go to school early.',
    so: 'Waxay iskuulka aadaan goor hore.',
  ),
  (
    word: 'Go to work',
    meaning: 'Shaqada aad',
    pronunciation: 'goo tu werk',
    en: 'She goes to work in the morning.',
    so: 'Waxay shaqada tagtaa subaxdii.',
  ),
]);

List<Json> schoolWords() => words([
  (
    word: 'Go to school',
    meaning: 'Iskuulka aad',
    pronunciation: 'goo tu skuul',
    en: 'I go to school at seven.',
    so: 'Waxaan iskuulka aadaa toddobada.',
  ),
  (
    word: 'Attend class',
    meaning: 'Fasalka ka qaybgal',
    pronunciation: 'a-tend klaas',
    en: 'We attend class every day.',
    so: 'Maalin kasta fasalka waan ka qaybgalnaa.',
  ),
  (
    word: 'Study English',
    meaning: 'English baro',
    pronunciation: 'sta-di ing-lish',
    en: 'I study English every day.',
    so: 'Maalin kasta English waan bartaa.',
  ),
  (
    word: 'Read a book',
    meaning: 'Buug akhri',
    pronunciation: 'riid a buk',
    en: 'She reads a book after class.',
    so: 'Waxay buug akhridaa fasalka kadib.',
  ),
  (
    word: 'Write notes',
    meaning: 'Qoraallo qor',
    pronunciation: 'raayt noots',
    en: 'I write notes in class.',
    so: 'Fasalka waxaan ku qoraa qoraallo.',
  ),
  (
    word: 'Ask a question',
    meaning: 'Su’aal weydii',
    pronunciation: 'aask a kwes-chan',
    en: 'Students ask questions.',
    so: 'Ardaydu su’aalo ayay weydiiyaan.',
  ),
  (
    word: 'Answer a question',
    meaning: 'Su’aal ka jawaab',
    pronunciation: 'aan-sar a kwes-chan',
    en: 'He answers the question.',
    so: 'Wuxuu ka jawaabaa su’aasha.',
  ),
  (
    word: 'Do homework',
    meaning: 'Shaqo-guri samee',
    pronunciation: 'duu hoom-werk',
    en: 'I do homework in the afternoon.',
    so: 'Galabtii waxaan sameeyaa shaqo-guri.',
  ),
  (
    word: 'Take an exam',
    meaning: 'Imtixaan qaado',
    pronunciation: 'teyk an ig-zaam',
    en: 'They take an exam today.',
    so: 'Maanta waxay qaadanayaan imtixaan.',
  ),
  (
    word: 'Learn',
    meaning: 'Baro',
    pronunciation: 'lern',
    en: 'We learn new words.',
    so: 'Waxaan barannaa erayo cusub.',
  ),
  (
    word: 'Practice',
    meaning: 'Ku celceli',
    pronunciation: 'prak-tis',
    en: 'I practice English at home.',
    so: 'Guriga waxaan ku celceliyaa English.',
  ),
  (
    word: 'Use a computer',
    meaning: 'Kombiyuutar isticmaal',
    pronunciation: 'yuuz a kam-pyuu-tar',
    en: 'She uses a computer at school.',
    so: 'Waxay iskuulka ku isticmaashaa kombiyuutar.',
  ),
  (
    word: 'Return home',
    meaning: 'Guriga ku noqo',
    pronunciation: 'ri-tern hoom',
    en: 'I return home at two.',
    so: 'Waxaan guriga ku noqdaa labada.',
  ),
]);

List<Json> workWords() => words([
  (
    word: 'Go to work',
    meaning: 'Shaqada aad',
    pronunciation: 'goo tu werk',
    en: 'I go to work at eight.',
    so: 'Waxaan shaqada aadaa siddeedda.',
  ),
  (
    word: 'Start work',
    meaning: 'Shaqada bilow',
    pronunciation: 'staart werk',
    en: 'We start work at eight.',
    so: 'Waxaan shaqada bilownaa siddeedda.',
  ),
  (
    word: 'Finish work',
    meaning: 'Shaqada dhammee',
    pronunciation: 'fi-nish werk',
    en: 'She finishes work at four.',
    so: 'Waxay shaqada dhamaysaa afarta.',
  ),
  (
    word: 'Open the shop',
    meaning: 'Dukaanka fur',
    pronunciation: 'oo-pan dha shop',
    en: 'The trader opens the shop early.',
    so: 'Ganacsaduhu dukaanka goor hore ayuu furaa.',
  ),
  (
    word: 'Close the shop',
    meaning: 'Dukaanka xir',
    pronunciation: 'klooz dha shop',
    en: 'He closes the shop at six.',
    so: 'Wuxuu dukaanka xiraa lixda.',
  ),
  (
    word: 'Help customers',
    meaning: 'Macaamiisha caawi',
    pronunciation: 'help kas-ta-mars',
    en: 'I help customers every day.',
    so: 'Maalin kasta macaamiisha waan caawiyaa.',
  ),
  (
    word: 'Sell products',
    meaning: 'Alaab iibi',
    pronunciation: 'sel pro-dakts',
    en: 'They sell products in the market.',
    so: 'Waxay alaab ku iibiyaan suuqa.',
  ),
  (
    word: 'Buy products',
    meaning: 'Alaab iibso',
    pronunciation: 'baay pro-dakts',
    en: 'We buy products on Monday.',
    so: 'Waxaan alaab iibsannaa Isniinta.',
  ),
  (
    word: 'Make a phone call',
    meaning: 'Wicitaan samee',
    pronunciation: 'meyk a foon kool',
    en: 'She makes a phone call.',
    so: 'Waxay samaysaa wicitaan.',
  ),
  (
    word: 'Send a message',
    meaning: 'Farriin dir',
    pronunciation: 'send a me-sij',
    en: 'I send a message to the driver.',
    so: 'Waxaan farriin u diraa darawalka.',
  ),
  (
    word: 'Use a computer',
    meaning: 'Kombiyuutar isticmaal',
    pronunciation: 'yuuz a kam-pyuu-tar',
    en: 'The office worker uses a computer.',
    so: 'Shaqaalaha xafiisku kombiyuutar ayuu isticmaalaa.',
  ),
  (
    word: 'Attend a meeting',
    meaning: 'Shir ka qaybgal',
    pronunciation: 'a-tend a mii-ting',
    en: 'We attend a meeting at ten.',
    so: 'Waxaan shir ka qaybgalnaa tobanka.',
  ),
  (
    word: 'Take a break',
    meaning: 'Nasasho qaado',
    pronunciation: 'teyk a breyk',
    en: 'They take a break at noon.',
    so: 'Waxay nasasho qaataan duhurkii.',
  ),
  (
    word: 'Return home',
    meaning: 'Guriga ku noqo',
    pronunciation: 'ri-tern hoom',
    en: 'The teacher returns home at three.',
    so: 'Macallinku guriga ayuu ku noqdaa saddexda.',
  ),
]);

List<Json> afternoonWords() => words([
  (
    word: 'Eat lunch',
    meaning: 'Qado cun',
    pronunciation: 'iit lanch',
    en: 'I eat lunch at one.',
    so: 'Waxaan qadeeyaa kowda.',
  ),
  (
    word: 'Rest',
    meaning: 'Naso',
    pronunciation: 'rest',
    en: 'She rests after work.',
    so: 'Waxay nasataa shaqada kadib.',
  ),
  (
    word: 'Take a break',
    meaning: 'Nasasho qaado',
    pronunciation: 'teyk a breyk',
    en: 'We take a break in the afternoon.',
    so: 'Galabtii nasasho ayaan qaadannaa.',
  ),
  (
    word: 'Visit a friend',
    meaning: 'Saaxiib booqo',
    pronunciation: 'vi-zit a frend',
    en: 'I visit a friend after school.',
    so: 'Waxaan saaxiib booqdaa iskuulka kadib.',
  ),
  (
    word: 'Go shopping',
    meaning: 'Dukaamaysi aad',
    pronunciation: 'goo sho-ping',
    en: 'They go shopping in the evening.',
    so: 'Waxay dukaamaysi aadaan fiidkii.',
  ),
  (
    word: 'Play football',
    meaning: 'Kubad ciyaar',
    pronunciation: 'pley fut-bool',
    en: 'He plays football after school.',
    so: 'Wuxuu kubad ciyaaraa iskuulka kadib.',
  ),
  (
    word: 'Exercise',
    meaning: 'Jimicsi samee',
    pronunciation: 'ek-sar-saayz',
    en: 'She exercises in the afternoon.',
    so: 'Waxay jimicsi samaysaa galabtii.',
  ),
  (
    word: 'Help my family',
    meaning: 'Qoyskayga caawi',
    pronunciation: 'help maay fa-ma-li',
    en: 'I help my family after work.',
    so: 'Waxaan qoyskayga caawiyaa shaqada kadib.',
  ),
  (
    word: 'Cook dinner',
    meaning: 'Casho kari',
    pronunciation: 'kuk di-nar',
    en: 'We cook dinner at home.',
    so: 'Guriga ayaan cashada ku karinnaa.',
  ),
  (
    word: 'Eat dinner',
    meaning: 'Casho cun',
    pronunciation: 'iit di-nar',
    en: 'They eat dinner at seven.',
    so: 'Waxay cashadaan toddobada.',
  ),
  (
    word: 'Watch television',
    meaning: 'Telefishan daawo',
    pronunciation: 'woch te-la-vi-zhan',
    en: 'He watches television after dinner.',
    so: 'Wuxuu telefishan daawadaa cashada kadib.',
  ),
  (
    word: 'Use my phone',
    meaning: 'Telefoonkayga isticmaal',
    pronunciation: 'yuuz maay foon',
    en: 'I use my phone in the evening.',
    so: 'Fiidkii waxaan isticmaalaa telefoonkayga.',
  ),
  (
    word: 'Study',
    meaning: 'Wax baro',
    pronunciation: 'sta-di',
    en: 'I study before dinner.',
    so: 'Waxaan wax bartaa cashada ka hor.',
  ),
  (
    word: 'Talk to my family',
    meaning: 'Qoyskayga la hadal',
    pronunciation: 'took tu maay fa-ma-li',
    en: 'I talk to my family after dinner.',
    so: 'Waxaan qoyskayga la hadlaa cashada kadib.',
  ),
  (
    word: 'In the afternoon',
    meaning: 'Galabtii',
    pronunciation: 'in dhi aaf-tar-nuun',
    en: 'I rest in the afternoon.',
    so: 'Galabtii waan nastaa.',
  ),
  (
    word: 'In the evening',
    meaning: 'Fiidkii',
    pronunciation: 'in dhi iiv-ning',
    en: 'We study in the evening.',
    so: 'Fiidkii wax ayaan barannaa.',
  ),
  (
    word: 'After school',
    meaning: 'Iskuulka kadib',
    pronunciation: 'aaf-tar skuul',
    en: 'He plays after school.',
    so: 'Wuxuu ciyaaraa iskuulka kadib.',
  ),
  (
    word: 'After work',
    meaning: 'Shaqada kadib',
    pronunciation: 'aaf-tar werk',
    en: 'She rests after work.',
    so: 'Waxay nasataa shaqada kadib.',
  ),
  (
    word: 'Before dinner',
    meaning: 'Cashada ka hor',
    pronunciation: 'bi-foor di-nar',
    en: 'I read before dinner.',
    so: 'Waxaan akhriyaa cashada ka hor.',
  ),
  (
    word: 'After dinner',
    meaning: 'Cashada kadib',
    pronunciation: 'aaf-tar di-nar',
    en: 'We talk after dinner.',
    so: 'Waxaan wada hadalnaa cashada kadib.',
  ),
]);

List<Json> nightWords() => words([
  (
    word: 'Finish my homework',
    meaning: 'Shaqo-gurigayga dhammee',
    pronunciation: 'fi-nish maay hoom-werk',
    en: 'I finish my homework at night.',
    so: 'Habeenkii waxaan dhammeeyaa shaqo-gurigayga.',
  ),
  (
    word: 'Prepare for tomorrow',
    meaning: 'Berri isu diyaari',
    pronunciation: 'pri-peer foor ta-mo-roo',
    en: 'She prepares for tomorrow.',
    so: 'Waxay isu diyaarisaa berri.',
  ),
  (
    word: 'Read',
    meaning: 'Akhri',
    pronunciation: 'riid',
    en: 'We read before bed.',
    so: 'Waxaan akhrinnaa sariirta ka hor.',
  ),
  (
    word: 'Check my phone',
    meaning: 'Telefoonkayga eeg',
    pronunciation: 'chek maay foon',
    en: 'I check my phone once.',
    so: 'Telefoonkayga hal mar ayaan eegaa.',
  ),
  (
    word: 'Brush my teeth',
    meaning: 'Ilkahayga caday',
    pronunciation: 'brash maay tiith',
    en: 'I brush my teeth before bed.',
    so: 'Waxaan ilkahayga cadayaa sariirta ka hor.',
  ),
  (
    word: 'Go to bed',
    meaning: 'Sariirta aad',
    pronunciation: 'goo tu bed',
    en: 'I go to bed at ten.',
    so: 'Waxaan sariirta aadaa tobanka.',
  ),
  (
    word: 'Sleep',
    meaning: 'Seexo',
    pronunciation: 'sliip',
    en: 'They sleep for eight hours.',
    so: 'Waxay seexdaan siddeed saacadood.',
  ),
  (
    word: 'Sleep early',
    meaning: 'Goor hore seexo',
    pronunciation: 'sliip er-li',
    en: 'She sleeps early.',
    so: 'Waxay seexataa goor hore.',
  ),
  (
    word: 'Sleep late',
    meaning: 'Goor dambe seexo',
    pronunciation: 'sliip leyt',
    en: 'He sleeps late on Friday.',
    so: 'Wuxuu seexdaa goor dambe Jimcaha.',
  ),
  (
    word: 'Set an alarm',
    meaning: 'Digniin saacad dhig',
    pronunciation: 'set an a-laarm',
    en: 'I set an alarm for six.',
    so: 'Waxaan digniin dhigtaa lixda.',
  ),
]);

List<Json> positiveWords() => words([
  (
    word: 'Base verb',
    meaning: 'Falka asalka ah',
    pronunciation: 'beys verb',
    en: 'Work is a base verb.',
    so: 'Work waa fal asal ah.',
  ),
  (
    word: 'Present Simple',
    meaning: 'Waqtiga caadada/jadwalka',
    pronunciation: 'pre-zant sim-pal',
    en: 'We use Present Simple for routines.',
    so: 'Present Simple waxaan u isticmaalnaa jadwallada.',
  ),
  (
    word: 'Work → works',
    meaning: 'Work wuxuu noqdaa works',
    pronunciation: 'werk, werks',
    en: 'He works at a bank.',
    so: 'Wuxuu ka shaqeeyaa bangi.',
  ),
  (
    word: 'Read → reads',
    meaning: 'Read wuxuu noqdaa reads',
    pronunciation: 'riid, riidz',
    en: 'She reads every day.',
    so: 'Maalin kasta way akhridaa.',
  ),
  (
    word: 'Go → goes',
    meaning: 'Go wuxuu noqdaa goes',
    pronunciation: 'goo, gooz',
    en: 'He goes to school.',
    so: 'Wuxuu aadaa iskuulka.',
  ),
  (
    word: 'Wash → washes',
    meaning: 'Wash wuxuu noqdaa washes',
    pronunciation: 'wosh, wo-shiz',
    en: 'She washes her face.',
    so: 'Waxay dhaqdaa wajigeeda.',
  ),
  (
    word: 'Watch → watches',
    meaning: 'Watch wuxuu noqdaa watches',
    pronunciation: 'woch, wo-chiz',
    en: 'He watches television.',
    so: 'Wuxuu daawadaa telefishan.',
  ),
  (
    word: 'Study → studies',
    meaning: 'Study wuxuu noqdaa studies',
    pronunciation: 'sta-di, sta-diz',
    en: 'She studies English.',
    so: 'Waxay barataa English.',
  ),
  (
    word: 'Play → plays',
    meaning: 'Play wuxuu noqdaa plays',
    pronunciation: 'pley, pleyz',
    en: 'He plays football.',
    so: 'Wuxuu ciyaaraa kubad.',
  ),
  (
    word: 'Routine',
    meaning: 'Jadwal joogto ah',
    pronunciation: 'ruu-tiin',
    en: 'This is my daily routine.',
    so: 'Kani waa jadwalkayga maalinlaha ah.',
  ),
  (
    word: 'Habit',
    meaning: 'Caado',
    pronunciation: 'ha-bit',
    en: 'Reading is a good habit.',
    so: 'Akhrisku waa caado wanaagsan.',
  ),
  (
    word: 'Schedule',
    meaning: 'Jadwal',
    pronunciation: 'ske-jool',
    en: 'My schedule starts at six.',
    so: 'Jadwalkaygu wuxuu bilaabmaa lixda.',
  ),
], type: 'grammar phrase');

List<Json> negativeWords() => words([
  (
    word: 'Do not',
    meaning: 'Ma sameeyo/samayno',
    pronunciation: 'duu not',
    en: 'I do not work on Friday.',
    so: 'Ma shaqeeyo Jimcaha.',
  ),
  (
    word: "Don't",
    meaning: 'Soo gaabinta do not',
    pronunciation: 'doont',
    en: "We don't study at night.",
    so: 'Habeenkii wax ma baranno.',
  ),
  (
    word: 'Does not',
    meaning: 'Ma sameeyo (he/she/it)',
    pronunciation: 'daz not',
    en: 'He does not work at night.',
    so: 'Habeenkii ma shaqeeyo.',
  ),
  (
    word: "Doesn't",
    meaning: 'Soo gaabinta does not',
    pronunciation: 'da-zant',
    en: "She doesn't eat early.",
    so: 'Goor hore wax ma cunto.',
  ),
  (
    word: 'Negative sentence',
    meaning: 'Jumlad diidmo ah',
    pronunciation: 'ne-ga-tiv sen-tans',
    en: "I don't drink coffee.",
    so: 'Kafee ma cabo.',
  ),
  (
    word: 'Base form',
    meaning: 'Qaabka asalka falka',
    pronunciation: 'beys foorm',
    en: 'Use go after does not.',
    so: 'Does not ka dib isticmaal go.',
  ),
  (
    word: 'At night',
    meaning: 'Habeenkii',
    pronunciation: 'at naayt',
    en: "They don't work at night.",
    so: 'Habeenkii ma shaqeeyaan.',
  ),
  (
    word: 'On Friday',
    meaning: 'Jimcaha',
    pronunciation: 'on fraay-dey',
    en: 'I do not work on Friday.',
    so: 'Ma shaqeeyo Jimcaha.',
  ),
], type: 'grammar phrase');

List<Json> questionWords() => words([
  (
    word: 'Do you…?',
    meaning: 'Ma …?',
    pronunciation: 'duu yuu',
    en: 'Do you work?',
    so: 'Ma shaqaysaa?',
  ),
  (
    word: 'Does he…?',
    meaning: 'Miyuu …?',
    pronunciation: 'daz hii',
    en: 'Does he study?',
    so: 'Miyuu wax bartaa?',
  ),
  (
    word: 'What time…?',
    meaning: 'Saacad imisa…?',
    pronunciation: 'wot taaym',
    en: 'What time do you wake up?',
    so: 'Saacad imisa ayaad kacdaa?',
  ),
  (
    word: 'Where…?',
    meaning: 'Xaggee…?',
    pronunciation: 'weer',
    en: 'Where do you work?',
    so: 'Xaggee ka shaqaysaa?',
  ),
  (
    word: 'When…?',
    meaning: 'Goorma…?',
    pronunciation: 'wen',
    en: 'When does he study?',
    so: 'Goorma ayuu wax bartaa?',
  ),
  (
    word: 'What…?',
    meaning: 'Maxay/maxaa…?',
    pronunciation: 'wot',
    en: 'What does she do after work?',
    so: 'Maxay samaysaa shaqada kadib?',
  ),
  (
    word: 'Yes, I do.',
    meaning: 'Haa, waan sameeyaa',
    pronunciation: 'yes aay duu',
    en: 'Do you study? Yes, I do.',
    so: 'Ma wax barataa? Haa.',
  ),
  (
    word: "No, I don't.",
    meaning: 'Maya, ma sameeyo',
    pronunciation: 'noo aay doont',
    en: "Do you work? No, I don't.",
    so: 'Ma shaqaysaa? Maya.',
  ),
  (
    word: 'Yes, he does.',
    meaning: 'Haa, wuu sameeyaa',
    pronunciation: 'yes hii daz',
    en: 'Does he work? Yes, he does.',
    so: 'Miyuu shaqeeyaa? Haa.',
  ),
  (
    word: "No, she doesn't.",
    meaning: 'Maya, ma samayso',
    pronunciation: 'noo shii da-zant',
    en: "Does she study? No, she doesn't.",
    so: 'Miyay wax barataa? Maya.',
  ),
], type: 'question or short answer');

List<Json> frequencyWords() => words([
  (
    word: 'Always',
    meaning: 'Mar kasta',
    pronunciation: 'ool-weyz',
    en: 'I always eat breakfast.',
    so: 'Mar kasta waan quraacdaa.',
  ),
  (
    word: 'Usually',
    meaning: 'Inta badan',
    pronunciation: 'yuu-zhu-wa-li',
    en: 'She usually goes early.',
    so: 'Inta badan goor hore ayay tagtaa.',
  ),
  (
    word: 'Often',
    meaning: 'Marar badan',
    pronunciation: 'of-an',
    en: 'We often study together.',
    so: 'Marar badan wadajir ayaan wax u barannaa.',
  ),
  (
    word: 'Sometimes',
    meaning: 'Mararka qaar',
    pronunciation: 'sam-taaymz',
    en: 'He sometimes plays football.',
    so: 'Mararka qaar kubad ayuu ciyaaraa.',
  ),
  (
    word: 'Rarely',
    meaning: 'Si dhif ah',
    pronunciation: 'reer-li',
    en: 'They rarely eat outside.',
    so: 'Si dhif ah ayay dibadda wax ugu cunaan.',
  ),
  (
    word: 'Never',
    meaning: 'Marnaba',
    pronunciation: 'ne-var',
    en: 'I never drink coffee at night.',
    so: 'Marnaba kafee ma cabo habeenkii.',
  ),
  (
    word: 'Every day',
    meaning: 'Maalin kasta',
    pronunciation: 'ev-ri dey',
    en: 'I study every day.',
    so: 'Maalin kasta wax ayaan bartaa.',
  ),
  (
    word: 'Every morning',
    meaning: 'Subax kasta',
    pronunciation: 'ev-ri moor-ning',
    en: 'She walks every morning.',
    so: 'Subax kasta way socotaa.',
  ),
  (
    word: 'Every week',
    meaning: 'Toddobaad kasta',
    pronunciation: 'ev-ri wiik',
    en: 'We meet every week.',
    so: 'Toddobaad kasta waan kulannaa.',
  ),
], type: 'frequency expression');

List<Json> routineWords() => words([
  (
    word: 'First',
    meaning: 'Marka hore',
    pronunciation: 'ferst',
    en: 'First, I wake up.',
    so: 'Marka hore, waan kacaa.',
  ),
  (
    word: 'Then',
    meaning: 'Kadib',
    pronunciation: 'dhen',
    en: 'Then, I eat breakfast.',
    so: 'Kadib, waan quraacdaa.',
  ),
  (
    word: 'After that',
    meaning: 'Intaas kadib',
    pronunciation: 'aaf-tar dhat',
    en: 'After that, I go to work.',
    so: 'Intaas kadib, waxaan aadaa shaqada.',
  ),
  (
    word: 'Finally',
    meaning: 'Ugu dambayn',
    pronunciation: 'faay-na-li',
    en: 'Finally, I go to bed.',
    so: 'Ugu dambayn, waxaan aadaa sariirta.',
  ),
  (
    word: "Six o'clock",
    meaning: 'Lixda saacad',
    pronunciation: 'siks o-klook',
    en: "I wake up at six o'clock.",
    so: 'Waxaan kacaa lixda saacad.',
  ),
  (
    word: 'At eight',
    meaning: 'Siddeedda',
    pronunciation: 'at eyt',
    en: 'I go to work at eight.',
    so: 'Waxaan shaqada aadaa siddeedda.',
  ),
  (
    word: 'Daily routine',
    meaning: 'Jadwal maalinle ah',
    pronunciation: 'dey-li ruu-tiin',
    en: 'This is a daily routine.',
    so: 'Kani waa jadwal maalinle ah.',
  ),
  (
    word: 'Time expression',
    meaning: 'Weedh waqti',
    pronunciation: 'taaym ek-spre-shan',
    en: 'In the evening is a time expression.',
    so: 'In the evening waa weedh waqti.',
  ),
], type: 'sequence or time phrase');

List<Json> routineQuestionWords() => words([
  (
    word: 'What time do you wake up?',
    meaning: 'Saacad imisa ayaad kacdaa?',
    pronunciation: 'wot taaym duu yuu weyk ap',
    en: 'What time do you wake up?',
    so: 'Saacad imisa ayaad kacdaa?',
  ),
  (
    word: 'When do you go to work?',
    meaning: 'Goorma ayaad shaqada tagtaa?',
    pronunciation: 'wen duu yuu goo tu werk',
    en: 'When do you go to work?',
    so: 'Goorma ayaad shaqada tagtaa?',
  ),
  (
    word: 'Do you eat breakfast?',
    meaning: 'Ma quraacataa?',
    pronunciation: 'duu yuu iit brek-fast',
    en: 'Do you eat breakfast?',
    so: 'Ma quraacataa?',
  ),
  (
    word: 'Where do you study?',
    meaning: 'Xaggee wax ku barataa?',
    pronunciation: 'weer duu yuu sta-di',
    en: 'Where do you study?',
    so: 'Xaggee wax ku barataa?',
  ),
  (
    word: 'What do you do in the evening?',
    meaning: 'Maxaad samaysaa fiidkii?',
    pronunciation: 'wot duu yuu duu in dhi iiv-ning',
    en: 'What do you do in the evening?',
    so: 'Maxaad samaysaa fiidkii?',
  ),
  (
    word: 'Does your brother work?',
    meaning: 'Walaalkaa ma shaqeeyaa?',
    pronunciation: 'daz yoor bra-dhar werk',
    en: 'Does your brother work?',
    so: 'Walaalkaa ma shaqeeyaa?',
  ),
  (
    word: 'What time does she go to school?',
    meaning: 'Saacad imisa ayay iskuulka tagtaa?',
    pronunciation: 'wot taaym daz shii goo tu skuul',
    en: 'What time does she go to school?',
    so: 'Saacad imisa ayay iskuulka tagtaa?',
  ),
  (
    word: 'Does he study at night?',
    meaning: 'Miyuu wax bartaa habeenkii?',
    pronunciation: 'daz hii sta-di at naayt',
    en: 'Does he study at night?',
    so: 'Miyuu wax bartaa habeenkii?',
  ),
], type: 'routine question');

List<Json> reviewWords() => words([
  (
    word: 'Morning routine',
    meaning: 'Jadwalka subaxda',
    pronunciation: 'moor-ning ruu-tiin',
    en: 'Review the morning routine.',
    so: 'Dib u eeg jadwalka subaxda.',
  ),
  (
    word: 'School activity',
    meaning: 'Hawl iskuul',
    pronunciation: 'skuul ak-ti-vi-ti',
    en: 'Name a school activity.',
    so: 'Magacow hawl iskuul.',
  ),
  (
    word: 'Work activity',
    meaning: 'Hawl shaqo',
    pronunciation: 'werk ak-ti-vi-ti',
    en: 'Describe a work activity.',
    so: 'Sharax hawl shaqo.',
  ),
  (
    word: 'Positive sentence',
    meaning: 'Jumlad xaqiijin ah',
    pronunciation: 'po-zi-tiv sen-tans',
    en: 'Write a positive sentence.',
    so: 'Qor jumlad xaqiijin ah.',
  ),
  (
    word: 'Negative sentence',
    meaning: 'Jumlad diidmo ah',
    pronunciation: 'ne-ga-tiv sen-tans',
    en: 'Write a negative sentence.',
    so: 'Qor jumlad diidmo ah.',
  ),
  (
    word: 'Question form',
    meaning: 'Qaabka su’aasha',
    pronunciation: 'kwes-chan foorm',
    en: 'Practice the question form.',
    so: 'Ku celceli qaabka su’aasha.',
  ),
  (
    word: 'Third person',
    meaning: 'Qofka saddexaad: he/she/it',
    pronunciation: 'therd per-san',
    en: 'Third person takes -s.',
    so: 'Qofka saddexaad wuxuu qaataa -s.',
  ),
  (
    word: 'Frequency',
    meaning: 'Inta jeer',
    pronunciation: 'frii-kwan-si',
    en: 'Always shows frequency.',
    so: 'Always wuxuu muujinayaa inta jeer.',
  ),
  (
    word: 'Sequence',
    meaning: 'Kala horreynta hawlaha',
    pronunciation: 'sii-kwans',
    en: 'Use sequence words.',
    so: 'Isticmaal erayada kala horreynta.',
  ),
  (
    word: 'Paragraph',
    meaning: 'Faqrad',
    pronunciation: 'pa-ra-graaf',
    en: 'Write a routine paragraph.',
    so: 'Qor faqrad routine ah.',
  ),
], type: 'review term');

List<Json> dialogues(int number) {
  final data = <int, List<Json>>{
    1: [
      dialogue('Subaxda arday', [
        line('A', 'What time do you wake up?', 'Saacad imisa ayaad kacdaa?'),
        line('B', 'I wake up at six.', 'Waxaan kacaa lixda.'),
        line('A', 'What do you do next?', 'Maxaad xigta samaysaa?'),
        line('B', 'I pray and eat breakfast.', 'Waan tukadaa oo quraacdaa.'),
      ]),
      dialogue('Shaqaale subaxdii', [
        line(
          'Worker',
          'I get up at six thirty.',
          'Waxaan sariirta ka kacaa lixda iyo badhka.',
        ),
        line(
          'Friend',
          'When do you leave home?',
          'Goorma ayaad guriga ka baxdaa?',
        ),
        line(
          'Worker',
          'I leave home at seven thirty.',
          'Waxaan guriga ka baxaa toddobada iyo badhka.',
        ),
        line('Friend', 'You start early.', 'Goor hore ayaad bilowdaa.'),
      ]),
    ],
    2: [
      dialogue('Laba arday', [
        line(
          'Hani',
          'Do you study English every day?',
          'Maalin kasta English ma barataa?',
        ),
        line('Ali', 'Yes, I do.', 'Haa.'),
        line(
          'Hani',
          'When do you do homework?',
          'Goorma ayaad shaqo-guri samaysaa?',
        ),
        line(
          'Ali',
          'I do homework after school.',
          'Waxaan sameeyaa iskuulka kadib.',
        ),
      ]),
      dialogue('Fasalka', [
        line('Teacher', 'Please write notes.', 'Fadlan qoraallo qor.'),
        line('Student', 'Can I ask a question?', 'Su’aal ma weydiin karaa?'),
        line('Teacher', 'Yes, ask your question.', 'Haa, weydii su’aashaada.'),
        line('Student', 'Thank you.', 'Mahadsanid.'),
      ]),
    ],
    3: [
      dialogue('Dukaanle', [
        line(
          'Trader',
          'I open the shop at seven.',
          'Waxaan dukaanka furaa toddobada.',
        ),
        line('Friend', 'When do you close it?', 'Goorma ayaad xirtaa?'),
        line('Trader', 'I close the shop at six.', 'Waxaan xiraa lixda.'),
        line('Friend', 'That is a long day.', 'Taasi waa maalin dheer.'),
      ]),
      dialogue('Shaqaale xafiis', [
        line('A', 'What do you do at work?', 'Maxaad ka samaysaa shaqada?'),
        line(
          'B',
          'I use a computer and send messages.',
          'Waxaan isticmaalaa kombiyuutar oo diraa farriimo.',
        ),
        line('A', 'Do you attend meetings?', 'Shirar ma ka qaybgaltaa?'),
        line('B', 'Yes, I do.', 'Haa.'),
      ]),
    ],
    4: [
      dialogue('Galabtii', [
        line(
          'A',
          'What do you do after school?',
          'Maxaad samaysaa iskuulka kadib?',
        ),
        line('B', 'I eat lunch and rest.', 'Waan qadeeyaa oo nastaa.'),
        line('A', 'Do you play football?', 'Kubad ma ciyaartaa?'),
        line('B', 'Sometimes.', 'Mararka qaar.'),
      ]),
      dialogue('Fiidkii', [
        line(
          'A',
          'What do you do after work?',
          'Maxaad samaysaa shaqada kadib?',
        ),
        line(
          'B',
          'I help my family and cook dinner.',
          'Waxaan caawiyaa qoyskayga oo kariyaa casho.',
        ),
        line(
          'A',
          'What do you do after dinner?',
          'Maxaad samaysaa cashada kadib?',
        ),
        line('B', 'I study English.', 'Waxaan bartaa English.'),
      ]),
    ],
    5: [
      dialogue('Habeenkii', [
        line(
          'A',
          'What time do you go to bed?',
          'Saacad imisa ayaad sariirta tagtaa?',
        ),
        line('B', 'I go to bed at ten.', 'Waxaan sariirta tagaa tobanka.'),
        line('A', 'Do you read before bed?', 'Ma akhridaa sariirta ka hor?'),
        line('B', 'Yes, I do.', 'Haa.'),
      ]),
      dialogue('Diyaargarowga berri', [
        line('A', 'What does she do at night?', 'Maxay samaysaa habeenkii?'),
        line('B', 'She prepares her clothes.', 'Waxay diyaarisaa dharkeeda.'),
        line('A', 'Does she set an alarm?', 'Digniin ma dhigataa?'),
        line('B', 'Yes, for six o’clock.', 'Haa, lixda.'),
      ]),
    ],
    6: [
      dialogue('Positive forms', [
        line('Teacher', 'I work. He…?', 'I work. He…?'),
        line('Student', 'He works.', 'He works.'),
        line('Teacher', 'I study. She…?', 'I study. She…?'),
        line('Student', 'She studies.', 'She studies.'),
      ]),
      dialogue('Jadwal shaqo', [
        line('A', 'Where does he work?', 'Xaggee ayuu ka shaqeeyaa?'),
        line('B', 'He works at a bank.', 'Wuxuu ka shaqeeyaa bangi.'),
        line('A', 'What does she teach?', 'Maxay dhigtaa?'),
        line('B', 'She teaches English.', 'Waxay dhigtaa English.'),
      ]),
    ],
    7: [
      dialogue('Negative routine', [
        line('A', 'Do you drink coffee?', 'Kafee ma cabtaa?'),
        line('B', 'No, I don’t drink coffee.', 'Maya, kafee ma cabo.'),
        line('A', 'Does he work at night?', 'Miyuu shaqeeyaa habeenkii?'),
        line(
          'B',
          'No, he doesn’t work at night.',
          'Maya, habeenkii ma shaqeeyo.',
        ),
      ]),
      dialogue('Sax falka', [
        line('Student', 'She doesn’t goes to school.', 'Iskuulka ma tagto.'),
        line(
          'Teacher',
          'Say: She doesn’t go to school.',
          'Dheh: She doesn’t go to school.',
        ),
        line('Student', 'She doesn’t go to school.', 'Iskuulka ma tagto.'),
        line('Teacher', 'Correct.', 'Waa sax.'),
      ]),
    ],
    8: [
      dialogue('Su’aalaha shaqada', [
        line('A', 'Do you work?', 'Ma shaqaysaa?'),
        line('B', 'Yes, I do.', 'Haa.'),
        line('A', 'Where do you work?', 'Xaggee ka shaqaysaa?'),
        line('B', 'I work in an office.', 'Waxaan ka shaqeeyaa xafiis.'),
      ]),
      dialogue('Su’aalaha ardayga', [
        line('A', 'Does she study English?', 'Miyay barataa English?'),
        line('B', 'Yes, she does.', 'Haa.'),
        line('A', 'When does she study?', 'Goorma ayay wax barataa?'),
        line('B', 'She studies in the evening.', 'Waxay wax barataa fiidkii.'),
      ]),
    ],
    9: [
      dialogue('Inta jeer', [
        line('A', 'Do you always eat breakfast?', 'Mar kasta ma quraacataa?'),
        line(
          'B',
          'Yes, I always eat breakfast.',
          'Haa, mar kasta waan quraacdaa.',
        ),
        line(
          'A',
          'Do you drink coffee at night?',
          'Kafee ma cabtaa habeenkii?',
        ),
        line('B', 'No, I never do.', 'Maya, marnaba.'),
      ]),
      dialogue('Ciyaarta', [
        line(
          'A',
          'How often does he play football?',
          'Immisa jeer ayuu kubad ciyaaraa?',
        ),
        line('B', 'He sometimes plays.', 'Mararka qaar ayuu ciyaaraa.'),
        line('A', 'Does he often exercise?', 'Marar badan ma jimicsadaa?'),
        line('B', 'Yes, he does.', 'Haa.'),
      ]),
    ],
    10: [
      dialogue('Routine isku xiran', [
        line('A', 'What do you do first?', 'Maxaad marka hore samaysaa?'),
        line(
          'B',
          'First, I wake up and pray.',
          'Marka hore waan kacaa oo tukadaa.',
        ),
        line(
          'A',
          'What do you do after that?',
          'Maxaad samaysaa intaas kadib?',
        ),
        line(
          'B',
          'I eat breakfast and go to work.',
          'Waan quraacdaa oo shaqada aadaa.',
        ),
      ]),
      dialogue('Dhammaadka maalinta', [
        line('A', 'What do you do finally?', 'Maxaad ugu dambayn samaysaa?'),
        line(
          'B',
          'Finally, I go to bed at ten.',
          'Ugu dambayn, sariirta ayaan aadaa tobanka.',
        ),
        line('A', 'Do you sleep early?', 'Goor hore ma seexataa?'),
        line('B', 'Usually, yes.', 'Inta badan, haa.'),
      ]),
    ],
    11: [
      dialogue('Laba shaqaale', [
        line('A', 'When do you start work?', 'Goorma ayaad shaqada bilowdaa?'),
        line('B', 'I start at eight.', 'Waxaan bilaabaa siddeedda.'),
        line('A', 'What do you do in the evening?', 'Maxaad samaysaa fiidkii?'),
        line('B', 'I study English.', 'Waxaan bartaa English.'),
      ]),
      dialogue('Ganacsade iyo saaxiib', [
        line(
          'Friend',
          'What time do you open the shop?',
          'Saacad imisa ayaad dukaanka furtaa?',
        ),
        line('Trader', 'I open it at seven.', 'Waxaan furaa toddobada.'),
        line(
          'Friend',
          'Does your brother help you?',
          'Walaalkaa ma ku caawiyaa?',
        ),
        line('Trader', 'Yes, he does.', 'Haa.'),
      ]),
    ],
    12: [
      dialogue('Review arday', [
        line('A', 'Do you study every day?', 'Maalin kasta ma wax barataa?'),
        line(
          'B',
          'Yes, I usually study after school.',
          'Haa, inta badan waxaan wax bartaa iskuulka kadib.',
        ),
        line('A', 'What time do you finish?', 'Saacad imisa ayaad dhamaysaa?'),
        line('B', 'I finish at five.', 'Waxaan dhammeeyaa shanta.'),
      ]),
      dialogue('Review shaqaale', [
        line('A', 'Does she work at night?', 'Miyay shaqaysaa habeenkii?'),
        line('B', 'No, she doesn’t.', 'Maya.'),
        line(
          'A',
          'What does she do in the evening?',
          'Maxay samaysaa fiidkii?',
        ),
        line('B', 'She often reads.', 'Marar badan way akhridaa.'),
      ]),
    ],
  };
  return data[number]!;
}

void main() {
  final lessons = <Json>[];

  void add({
    required int number,
    required String titleEnglish,
    required String titleSomali,
    required String description,
    required List<String> objectives,
    required String type,
    required int minutes,
    required List<Json> vocabulary,
    Json? grammarTopic,
    required List<Map<String, String>> examples,
    required String fillQuestion,
    required List<String> fillOptions,
    required String fillAnswer,
    required String grammarQuestion,
    required List<String> grammarOptions,
    required String grammarAnswer,
    required String mistakeQuestion,
    required List<String> mistakeOptions,
    required String mistakeAnswer,
    required String arrangeQuestion,
    required String arrangeAnswer,
    required String readingQuestion,
    required List<String> readingOptions,
    required String readingAnswer,
    required String dialogueQuestion,
    required List<String> dialogueOptions,
    required String dialogueAnswer,
    required String speaking,
    required String writing,
    required String summary,
    bool review = false,
  }) {
    final id = 'a1-u05-l${number.toString().padLeft(2, '0')}';
    lessons.add(
      lesson(
        number: number,
        titleEnglish: titleEnglish,
        titleSomali: titleSomali,
        description: description,
        objectives: objectives,
        type: type,
        minutes: minutes,
        vocabulary: vocabulary,
        grammarTopic: grammarTopic,
        examples: examples,
        dialogues: dialogues(number),
        exercises: practices(
          id,
          vocabulary,
          examples,
          fillQuestion: fillQuestion,
          fillOptions: fillOptions,
          fillAnswer: fillAnswer,
          grammarQuestion: grammarQuestion,
          grammarOptions: grammarOptions,
          grammarAnswer: grammarAnswer,
          mistakeQuestion: mistakeQuestion,
          mistakeOptions: mistakeOptions,
          mistakeAnswer: mistakeAnswer,
          arrangeQuestion: arrangeQuestion,
          arrangeAnswer: arrangeAnswer,
          readingQuestion: readingQuestion,
          readingOptions: readingOptions,
          readingAnswer: readingAnswer,
          dialogueQuestion: dialogueQuestion,
          dialogueOptions: dialogueOptions,
          dialogueAnswer: dialogueAnswer,
          speaking: speaking,
          writing: writing,
          review: review,
        ),
        speaking: speaking,
        writing: writing,
        summary: summary,
      ),
    );
  }

  List<Map<String, String>> e(
    String a,
    String sa,
    String b,
    String sb,
    String c,
    String sc,
    String d,
    String sd,
    String f,
    String sf,
    String g,
    String sg,
  ) => [
    example(a, sa),
    example(b, sb),
    example(c, sc),
    example(d, sd),
    example(f, sf),
    example(g, sg),
  ];

  final l1e = e(
    'I wake up at six o’clock.',
    'Waxaan hurdada ka kacaa lixda saacad.',
    'I brush my teeth every morning.',
    'Subax kasta ilkahayga waan cadayaa.',
    'I eat breakfast before school.',
    'Waxaan quraacdaa iskuulka ka hor.',
    'I leave home at seven.',
    'Waxaan guriga ka baxaa toddobada.',
    'She goes to work in the morning.',
    'Waxay shaqada tagtaa subaxdii.',
    'We drink tea at home.',
    'Guriga ayaan shaah ku cabnaa.',
  );
  add(
    number: 1,
    titleEnglish: 'Morning Activities',
    titleSomali: 'Hawlaha subaxdii',
    description:
        'Bar hawlaha laga bilaabo baraarugga ilaa guriga laga baxayo, iyo farqiga wake up/get up.',
    objectives: [
      'Magacow 13 hawlood oo subaxnimo.',
      'Wake up iyo get up kala saar.',
      'Routine subaxnimo oo waqti leh sheeg.',
    ],
    type: 'vocabulary',
    minutes: 27,
    vocabulary: morningWords(),
    examples: l1e,
    fillQuestion: 'I ___ my teeth every morning.',
    fillOptions: ['brush', 'eat', 'leave', 'drink'],
    fillAnswer: 'brush',
    grammarQuestion: 'She ___ to work in the morning.',
    grammarOptions: ['go', 'goes', 'going', 'does go'],
    grammarAnswer: 'goes',
    mistakeQuestion: 'Kee ayaa saxaya “She go to work”?',
    mistakeOptions: [
      'She goes to work.',
      'She going to work.',
      'She go works.',
      'She does goes to work.',
    ],
    mistakeAnswer: 'She goes to work.',
    arrangeQuestion: 'Kala hagaaji: breakfast / eat / I / school / before',
    arrangeAnswer: 'I eat breakfast before school.',
    readingQuestion:
        'Routine: “Hani wakes up at six and leaves home at seven.” Goormay guriga ka baxdaa?',
    readingOptions: ['Lixda', 'Toddobada', 'Siddeedda', 'Duhurkii'],
    readingAnswer: 'Toddobada',
    dialogueQuestion:
        'Wada hadalka subaxda: qofku muxuu sameeyaa wake up kadib?',
    dialogueOptions: [
      'Wuu tukadaa oo quraacdaa',
      'Dukaanka ayuu xiraa',
      'Wuu seexdaa',
      'Kulan ayuu tagaa',
    ],
    dialogueAnswer: 'Wuu tukadaa oo quraacdaa',
    speaking:
        'Sheeg shan hawlood oo routine subaxnimo male-awaal ah; ku dar laba waqti.',
    writing:
        'Qor lix jumladood oo hawlaha subaxdii ah, adigoo kala saaraya wake up iyo get up.',
    summary:
        'Wake up waa hurdada ka baraarug; get up waa sariirta ka soo kac. Waxaad baratay routine subaxnimo ilaa leave home.',
  );

  final l2e = e(
    'I go to school at seven.',
    'Waxaan iskuulka aadaa toddobada.',
    'We attend class every day.',
    'Maalin kasta fasalka waan ka qaybgalnaa.',
    'She reads a book after class.',
    'Waxay buug akhridaa fasalka kadib.',
    'I write notes in class.',
    'Fasalka waxaan ku qoraa qoraallo.',
    'They do homework at home.',
    'Waxay shaqo-guri ku sameeyaan guriga.',
    'He uses a computer at school.',
    'Wuxuu kombiyuutar ku isticmaalaa iskuulka.',
  );
  add(
    number: 2,
    titleEnglish: 'School and Study Activities',
    titleSomali: 'Hawlaha iskuulka iyo waxbarashada',
    description:
        'Bar hawlaha fasalka, waxbarashada iyo shaqo-guriga ee ardayga.',
    objectives: [
      'Magacow hawlaha iskuulka.',
      'Weydii time, subjects iyo homework.',
      'Sheeg routine waxbarasho.',
    ],
    type: 'vocabulary',
    minutes: 27,
    vocabulary: schoolWords(),
    examples: l2e,
    fillQuestion: 'I ___ notes in class.',
    fillOptions: ['write', 'writes', 'read', 'ask'],
    fillAnswer: 'write',
    grammarQuestion: 'Do you ___ English every day?',
    grammarOptions: ['studies', 'study', 'studying', 'studys'],
    grammarAnswer: 'study',
    mistakeQuestion: 'Kee ayaa sax ah?',
    mistakeOptions: [
      'What time you go to school?',
      'What time do you go to school?',
      'What time does you go?',
      'Do what time you go?',
    ],
    mistakeAnswer: 'What time do you go to school?',
    arrangeQuestion: 'Kala hagaaji: homework / after / do / I / school',
    arrangeAnswer: 'I do homework after school.',
    readingQuestion:
        'Routine: “Ali attends class, writes notes, and returns home at two.” Goormuu guriga ku noqdaa?',
    readingOptions: ['Kowda', 'Labada', 'Saddexda', 'Toddobada'],
    readingAnswer: 'Labada',
    dialogueQuestion: 'Wada hadalka ardayda: goormuu Ali homework sameeyaa?',
    dialogueOptions: [
      'Iskuulka ka hor',
      'Iskuulka kadib',
      'Habeen dambe',
      'Imtixaanka dhexdiisa',
    ],
    dialogueAnswer: 'Iskuulka kadib',
    speaking:
        'Ka hadal jadwal arday Soomaaliyeed ama arday male-awaal ah: school, class, study iyo homework.',
    writing:
        'Qor 6–8 jumladood oo routine arday ah; ku dar What time iyo When su’aalo.',
    summary:
        'Waxaad baratay school, class, notes, questions, homework, exam, practice iyo return home.',
  );

  final l3e = e(
    'I start work at eight.',
    'Waxaan shaqada bilaabaa siddeedda.',
    'He opens the shop at seven.',
    'Wuxuu dukaanka furaa toddobada.',
    'She helps customers.',
    'Waxay caawisaa macaamiisha.',
    'We attend a meeting at ten.',
    'Waxaan shir ka qaybgalnaa tobanka.',
    'The driver makes a phone call.',
    'Darawalku wicitaan ayuu sameeyaa.',
    'The teacher finishes work at three.',
    'Macallinku shaqada ayuu dhammeeyaa saddexda.',
  );
  add(
    number: 3,
    titleEnglish: 'Work and Business Activities',
    titleSomali: 'Hawlaha shaqada iyo ganacsiga',
    description:
        'Bar routine-ka shaqaale xafiis, ganacsade, dukaanle, macallin iyo darawal.',
    objectives: [
      'Magacow 14 hawlood oo shaqo.',
      'Routine shaqo ama ganacsi sharax.',
      'Start/finish iyo open/close kala saar.',
    ],
    type: 'vocabulary',
    minutes: 29,
    vocabulary: workWords(),
    examples: l3e,
    fillQuestion: 'The trader ___ the shop at seven.',
    fillOptions: ['open', 'opens', 'opening', 'does open'],
    fillAnswer: 'opens',
    grammarQuestion: 'Workers ___ customers.',
    grammarOptions: ['helps', 'help', 'helping', 'does help'],
    grammarAnswer: 'help',
    mistakeQuestion: 'Kee ayaa sax ah?',
    mistakeOptions: [
      'He close the shop.',
      'He closes the shop.',
      'He closing shop.',
      'He does closes the shop.',
    ],
    mistakeAnswer: 'He closes the shop.',
    arrangeQuestion: 'Kala hagaaji: meeting / attend / at / We / ten / a',
    arrangeAnswer: 'We attend a meeting at ten.',
    readingQuestion:
        '“A shopkeeper opens at seven and closes at six.” Goormuu dukaanka xiraa?',
    readingOptions: ['Toddobada', 'Lixda', 'Tobanka', 'Duhurkii'],
    readingAnswer: 'Lixda',
    dialogueQuestion: 'Shaqaalaha xafiisku muxuu sameeyaa?',
    dialogueOptions: [
      'Wuxuu seexdaa',
      'Kombiyuutar ayuu isticmaalaa oo farriimo diraa',
      'Kubad ayuu ciyaaraa',
      'Casho ayuu kariyaa',
    ],
    dialogueAnswer: 'Kombiyuutar ayuu isticmaalaa oo farriimo diraa',
    speaking:
        'Sharax routine ganacsade, shaqaale, macallin ama darawal male-awaal ah.',
    writing:
        'Qor 8 jumladood oo routine shaqo ah: start, customers, calls/messages, break iyo finish.',
    summary:
        'Waxaad baratay hawlaha shaqada iyo ganacsiga laga bilaabo start/open ilaa finish/close iyo return home.',
  );

  final l4e = e(
    'I eat lunch at one.',
    'Waxaan qadeeyaa kowda.',
    'She rests after work.',
    'Waxay nasataa shaqada kadib.',
    'He plays football after school.',
    'Wuxuu kubad ciyaaraa iskuulka kadib.',
    'We cook dinner at home.',
    'Guriga ayaan cashada ku karinnaa.',
    'I study before dinner.',
    'Waxaan wax bartaa cashada ka hor.',
    'They talk after dinner.',
    'Waxay wada hadlaan cashada kadib.',
  );
  add(
    number: 4,
    titleEnglish: 'Afternoon and Evening Activities',
    titleSomali: 'Hawlaha galabtii iyo fiidkii',
    description:
        'Bar hawlaha galabta iyo fiidka iyo time expressions before/after.',
    objectives: [
      'Magacow hawlaha galab/fiid.',
      'Before iyo after sax u isticmaal.',
      'Routine iskuul ama shaqo kadib sharax.',
    ],
    type: 'vocabulary',
    minutes: 29,
    vocabulary: afternoonWords(),
    examples: l4e,
    fillQuestion: 'I study ___ dinner.',
    fillOptions: ['before', 'after work', 'in', 'at'],
    fillAnswer: 'before',
    grammarQuestion: 'He ___ football after school.',
    grammarOptions: ['play', 'plays', 'playing', 'does plays'],
    grammarAnswer: 'plays',
    mistakeQuestion: 'Kee ayaa sax ah?',
    mistakeOptions: [
      'She rest after work.',
      'She rests after work.',
      'She resting after work.',
      'She does rests.',
    ],
    mistakeAnswer: 'She rests after work.',
    arrangeQuestion:
        'Kala hagaaji: family / after / talk / my / I / to / dinner',
    arrangeAnswer: 'I talk to my family after dinner.',
    readingQuestion:
        '“Hani eats lunch, rests, and studies before dinner.” Maxay samaysaa cashada ka hor?',
    readingOptions: [
      'Way nasataa',
      'Wax bay barataa',
      'Way qadaysaa',
      'Way shaqaysaa',
    ],
    readingAnswer: 'Wax bay barataa',
    dialogueQuestion: 'Qofka fiidkii muxuu sameeyaa shaqada kadib?',
    dialogueOptions: [
      'Qoyska ayuu caawiyaa oo casho kariyaa',
      'Iskuulka ayuu aadaa',
      'Dukaanka ayuu furaa',
      'Imtixaan ayuu qaataa',
    ],
    dialogueAnswer: 'Qoyska ayuu caawiyaa oo casho kariyaa',
    speaking:
        'Sharax routine galab iyo fiid male-awaal ah; isticmaal after school/work iyo before/after dinner.',
    writing: 'Qor siddeed jumladood oo afternoon/evening routine ah.',
    summary:
        'Time expressions-ku waxay isku xiraan hawlaha: in the afternoon/evening, after school/work, before/after dinner.',
  );

  final l5e = e(
    'I go to bed at ten.',
    'Waxaan sariirta aadaa tobanka.',
    'She sleeps early.',
    'Waxay seexataa goor hore.',
    'He prepares his clothes for tomorrow.',
    'Wuxuu dharkiisa u diyaariyaa berri.',
    'We read before bed.',
    'Waxaan akhrinnaa sariirta ka hor.',
    'I set an alarm for six.',
    'Waxaan digniin dhigtaa lixda.',
    'They sleep for eight hours.',
    'Waxay seexdaan siddeed saacadood.',
  );
  add(
    number: 5,
    titleEnglish: 'Night Activities',
    titleSomali: 'Hawlaha habeenkii',
    description: 'Bar hawlaha ka hor hurdada iyo farqiga go to bed/sleep.',
    objectives: [
      'Magacow hawlaha habeenkii.',
      'Go to bed iyo sleep kala saar.',
      'Routine habeen oo time leh sharax.',
    ],
    type: 'vocabulary',
    minutes: 24,
    vocabulary: nightWords(),
    examples: l5e,
    fillQuestion: 'I ___ an alarm for six.',
    fillOptions: ['set', 'sleep', 'read', 'prepare'],
    fillAnswer: 'set',
    grammarQuestion: 'She ___ early.',
    grammarOptions: ['sleep', 'sleeps', 'sleeping', 'does sleeps'],
    grammarAnswer: 'sleeps',
    mistakeQuestion: 'Kee ayaa farqiga saxda ah sheegaya?',
    mistakeOptions: [
      'Go to bed waa sariirta aad; sleep waa hurdo',
      'Go to bed waa shaqo aad',
      'Sleep waa digniin dhig',
      'Labaduba waa quraac',
    ],
    mistakeAnswer: 'Go to bed waa sariirta aad; sleep waa hurdo',
    arrangeQuestion: 'Kala hagaaji: bed / ten / go / at / I / to',
    arrangeAnswer: 'I go to bed at ten.',
    readingQuestion:
        '“Omar reads, brushes his teeth, and goes to bed at ten.” Goormuu sariirta tagaa?',
    readingOptions: ['Siddeedda', 'Sagaalka', 'Tobanka', 'Lixda'],
    readingAnswer: 'Tobanka',
    dialogueQuestion: 'Qofku ma akhriyaa sariirta ka hor?',
    dialogueOptions: [
      'Haa',
      'Maya',
      'Keliya subaxdii',
      'Wada hadalku ma sheegin',
    ],
    dialogueAnswer: 'Haa',
    speaking:
        'Sheeg routine habeen male-awaal ah laga bilaabo homework ilaa sleep.',
    writing:
        'Qor lix jumladood oo night activities ah; go to bed iyo sleep labadaba isticmaal.',
    summary:
        'Go to bed waa sariirta aadid; sleep waa hurdada lafteeda. Prepare, read, brush, set an alarm kadib ayaad seexan kartaa.',
  );

  final l6e = e(
    'I study English every day.',
    'Maalin kasta English waan bartaa.',
    'You work in a shop.',
    'Waxaad ka shaqaysaa dukaan.',
    'We eat lunch at one.',
    'Waxaan qadaynaa kowda.',
    'They play football.',
    'Waxay ciyaaraan kubad.',
    'He works at a bank.',
    'Wuxuu ka shaqeeyaa bangi.',
    'She teaches English.',
    'Waxay dhigtaa English.',
  );
  final l6g = grammar(
    titleEnglish: 'Present Simple positive',
    titleSomali: 'Present Simple xaqiijin ah',
    explanation:
        'Present Simple waxaa loo isticmaalaa caado, routine, jadwal iyo xaqiiqo fudud. I/you/we/they waxay qaataan base verb. He/she/it waxay qaataan -s ama -es. Consonant + y wuxuu noqdaa -ies: study→studies; vowel + y wuxuu qaataa -s: play→plays.',
    rule: 'I/you/we/they + base verb; he/she/it + verb-s/es/ies',
    structure: 'Subject + Present Simple verb + object/time',
    positive: l6e,
    negative: [
      example("I don't study at night.", 'Habeenkii wax ma barto.'),
      example("She doesn't work here.", 'Halkan kama shaqayso.'),
    ],
    questions: [
      example('Do they play football?', 'Kubad ma ciyaaraan?'),
      example('Does he work at a bank?', 'Bangi ma ka shaqeeyaa?'),
    ],
    mistakes: [
      'He work waa khalad; he works ayaa sax ah.',
      'Study→studies, laakiin play→plays.',
      'Go/wash/watch waxay qaataan -es.',
    ],
  );
  add(
    number: 6,
    titleEnglish: 'Present Simple Positive Sentences',
    titleSomali: 'Jumladda xaqiijinta ee Present Simple',
    description:
        'Bar Present Simple positive, base verb iyo third-person -s/-es/-ies.',
    objectives: [
      'Present Simple u isticmaal routine.',
      'He/she/it forms sax u qor.',
      's, es iyo ies kala dooro.',
    ],
    type: 'grammar',
    minutes: 32,
    vocabulary: positiveWords(),
    grammarTopic: l6g,
    examples: l6e,
    fillQuestion: 'She ___ English every day.',
    fillOptions: ['study', 'studies', 'studys', 'studying'],
    fillAnswer: 'studies',
    grammarQuestion: 'He ___ television at night.',
    grammarOptions: ['watch', 'watches', 'watchs', 'watchies'],
    grammarAnswer: 'watches',
    mistakeQuestion: 'Kee ayaa sax ah?',
    mistakeOptions: [
      'He go to work.',
      'He goes to work.',
      'He gos to work.',
      'He going to work.',
    ],
    mistakeAnswer: 'He goes to work.',
    arrangeQuestion: 'Kala hagaaji: bank / works / a / at / He',
    arrangeAnswer: 'He works at a bank.',
    readingQuestion:
        '“Amina studies English and teaches Somali.” Falkee ayaa -ies qaatay?',
    readingOptions: ['teaches', 'studies', 'English', 'Somali'],
    readingAnswer: 'studies',
    dialogueQuestion: 'Teacher-ku “I study” sidee ugu beddelay she?',
    dialogueOptions: ['She study', 'She studies', 'She studys', 'She is study'],
    dialogueAnswer: 'She studies',
    speaking:
        'Samee lix positive sentences: I, you, we, they, he iyo she; ku dar s/es/ies.',
    writing:
        'Qor toban positive sentences oo routine ah; ugu yaraan shan he/she ha noqdaan.',
    summary:
        'I/you/we/they + base verb. He/she/it + s/es/ies: works, goes, washes, watches, studies, laakiin plays.',
  );

  final l7e = e(
    "I don't work on Friday.",
    'Ma shaqeeyo Jimcaha.',
    "I don't drink coffee.",
    'Kafee ma cabo.',
    "We don't study at night.",
    'Habeenkii wax ma baranno.',
    "They don't live here.",
    'Halkan ma deggana.',
    "He doesn't work at night.",
    'Habeenkii ma shaqeeyo.',
    "She doesn't eat breakfast early.",
    'Goor hore ma quraacato.',
  );
  final l7g = grammar(
    titleEnglish: 'Present Simple negative',
    titleSomali: 'Present Simple diidmo ah',
    explanation:
        'I/you/we/they waxaa la socda do not/don’t. He/she/it waxaa la socda does not/doesn’t. Doesn’t ka dib falka waxaa lagu celiyaa base form.',
    rule: 'I/you/we/they + don’t + base; he/she/it + doesn’t + base',
    structure: 'Subject + do/does not + base verb + complement',
    positive: [
      example('She goes to school.', 'Waxay tagtaa iskuulka.'),
      example('He works at night.', 'Wuxuu shaqeeyaa habeenkii.'),
      example('They live here.', 'Halkan ayay deggan yihiin.'),
      example('We study English.', 'Waxaan barannaa English.'),
      example('I drink tea.', 'Shaah waan cabaa.'),
      example('You play football.', 'Kubad ayaad ciyaartaa.'),
    ],
    negative: l7e,
    questions: [
      example('Does she go to school?', 'Iskuulka ma tagtaa?'),
      example('Do they live here?', 'Halkan ma deggan yihiin?'),
    ],
    mistakes: [
      "She doesn’t goes waa khalad; She doesn’t go ayaa sax ah.",
      "He don't waa khalad; He doesn't ayaa sax ah.",
    ],
  );
  add(
    number: 7,
    titleEnglish: 'Present Simple Negative Sentences',
    titleSomali: 'Jumladda diidmada ee Present Simple',
    description: 'Bar do not/don’t iyo does not/doesn’t oo base verb la socda.',
    objectives: [
      'Don’t iyo doesn’t kala dooro.',
      'Positive u beddel negative.',
      'Doesn’t ka dib base verb isticmaal.',
    ],
    type: 'grammar',
    minutes: 29,
    vocabulary: negativeWords(),
    grammarTopic: l7g,
    examples: l7e,
    fillQuestion: "He ___ work at night.",
    fillOptions: ["don't", "doesn't", 'is not', 'not'],
    fillAnswer: "doesn't",
    grammarQuestion: "They ___ study at night.",
    grammarOptions: ["doesn't", "don't", 'is not', 'has not'],
    grammarAnswer: "don't",
    mistakeQuestion: 'Sax “She doesn’t goes to school.”',
    mistakeOptions: [
      "She doesn't go to school.",
      "She don't go to school.",
      'She not goes to school.',
      "She doesn't going school.",
    ],
    mistakeAnswer: "She doesn't go to school.",
    arrangeQuestion: 'Kala hagaaji: coffee / drink / do / I / not',
    arrangeAnswer: 'I do not drink coffee.',
    readingQuestion:
        '“Ali works in the day. He doesn’t work at night.” Goorma uusan shaqayn?',
    readingOptions: ['Maalintii', 'Habeenkii', 'Subaxdii', 'Duhurkii'],
    readingAnswer: 'Habeenkii',
    dialogueQuestion: 'Qofku kafee ma cabbaa?',
    dialogueOptions: ['Haa', 'Maya', 'Mar kasta', 'Wada hadalku ma sheegin'],
    dialogueAnswer: 'Maya',
    speaking:
        'Samee lix negative routine sentences: saddex don’t iyo saddex doesn’t.',
    writing:
        'U beddel lix positive sentences negative, adigoo falka base form ku celinaya.',
    summary:
        'Don’t: I/you/we/they. Doesn’t: he/she/it. Labadaba ka dib base verb: doesn’t go, ma aha doesn’t goes.',
  );

  final l8e = e(
    'Do you work?',
    'Ma shaqaysaa?',
    'Do they study English?',
    'English ma bartaan?',
    'Does he go to school?',
    'Iskuulka ma tagaa?',
    'Does she live in Mogadishu?',
    'Muqdisho ma deggan tahay?',
    'What time do you wake up?',
    'Saacad imisa ayaad kacdaa?',
    'What does she do after work?',
    'Maxay samaysaa shaqada kadib?',
  );
  final l8g = grammar(
    titleEnglish: 'Present Simple questions',
    titleSomali: 'Su’aalaha Present Simple',
    explanation:
        'Do waxaa lala isticmaalaa I/you/we/they. Does waxaa lala isticmaalaa he/she/it. Helper-ka kadib base verb ayaa yimaada. WH word wuxuu ka horreeyaa do/does.',
    rule: 'Do + I/you/we/they + base? Does + he/she/it + base?',
    structure: 'WH word + do/does + subject + base verb?',
    positive: [
      example('I work.', 'Waan shaqeeyaa.'),
      example('They study.', 'Wax bay bartaan.'),
      example('He works.', 'Wuu shaqeeyaa.'),
      example('She studies.', 'Wax bay barataa.'),
      example('We live here.', 'Halkan ayaan deggan nahay.'),
      example('You wake up early.', 'Goor hore ayaad kacdaa.'),
    ],
    negative: [
      example("No, I don't.", 'Maya.'),
      example("No, she doesn't.", 'Maya.'),
    ],
    questions: l8e,
    mistakes: [
      'Does he works? waa khalad; Does he work? ayaa sax ah.',
      'Do she… waa khalad; Does she… ayaa sax ah.',
    ],
  );
  add(
    number: 8,
    titleEnglish: 'Present Simple Questions',
    titleSomali: 'Su’aalaha Present Simple',
    description:
        'Bar do/does yes-no questions, WH questions iyo short answers.',
    objectives: [
      'Do iyo does questions samee.',
      'Base verb ku isticmaal su’aasha.',
      'Short answers sax ah bixi.',
    ],
    type: 'grammar',
    minutes: 31,
    vocabulary: questionWords(),
    grammarTopic: l8g,
    examples: l8e,
    fillQuestion: '___ she live in Mogadishu?',
    fillOptions: ['Do', 'Does', 'Is', 'Are'],
    fillAnswer: 'Does',
    grammarQuestion: '___ they study English?',
    grammarOptions: ['Does', 'Do', 'Is', 'Has'],
    grammarAnswer: 'Do',
    mistakeQuestion: 'Sax “Does he works?”',
    mistakeOptions: [
      'Does he work?',
      'Do he works?',
      'Does he working?',
      'He does works?',
    ],
    mistakeAnswer: 'Does he work?',
    arrangeQuestion: 'Kala hagaaji: do / Where / work / you',
    arrangeAnswer: 'Where do you work?',
    readingQuestion:
        '“Does Hani study at night? No, she doesn’t.” Hani habeenkii ma wax barataa?',
    readingOptions: ['Haa', 'Maya', 'Mararka qaar', 'Lama sheegin'],
    readingAnswer: 'Maya',
    dialogueQuestion: 'Shaqaaluhu xaggee ka shaqeeyaa?',
    dialogueOptions: ['Iskuul', 'Xafiis', 'Suuq', 'Isbitaal'],
    dialogueAnswer: 'Xafiis',
    speaking:
        'Weydii lix routine questions: laba do, laba does iyo laba WH; short answers ku dar.',
    writing: 'U beddel siddeed statements questions, kadib short answers qor.',
    summary:
        'Do + I/you/we/they; Does + he/she/it; helper-ka kadib base verb. Short answers: Yes, I do / No, she doesn’t.',
  );

  final l9e = e(
    'I always eat breakfast.',
    'Mar kasta waan quraacdaa.',
    'She usually goes to work early.',
    'Inta badan shaqada goor hore ayay tagtaa.',
    'We often study together.',
    'Marar badan wadajir ayaan wax u barannaa.',
    'He sometimes plays football.',
    'Mararka qaar kubad ayuu ciyaaraa.',
    'They rarely eat outside.',
    'Si dhif ah ayay dibadda wax ugu cunaan.',
    'I never drink coffee at night.',
    'Marnaba kafee ma cabo habeenkii.',
  );
  final l9g = grammar(
    titleEnglish: 'Adverbs of frequency',
    titleSomali: 'Erayada inta jeer',
    explanation:
        'Always, usually, often, sometimes, rarely iyo never waxay sheegaan inta jeer. Waxay main verb ka hor yimaadaan: I usually study. Verb to be ka dib ayay yimaadaan: She is always early.',
    rule:
        'Subject + frequency adverb + main verb; subject + be + frequency adverb',
    structure: 'Subject + always/usually/often/sometimes/rarely/never + verb',
    positive: l9e,
    negative: [
      example(
        'I never drink coffee at night.',
        'Marnaba kafee ma cabo habeenkii.',
      ),
      example(
        'They rarely eat outside.',
        'Si dhif ah ayay dibadda wax ugu cunaan.',
      ),
    ],
    questions: [
      example('Do you always eat breakfast?', 'Mar kasta ma quraacataa?'),
      example('How often does he play?', 'Immisa jeer ayuu ciyaaraa?'),
    ],
    mistakes: [
      'I study usually waa ka aan dabiici ahayn A1; I usually study ayaa fiican.',
      'She always is early halkii ka dheh She is always early.',
    ],
  );
  add(
    number: 9,
    titleEnglish: 'Adverbs of Frequency',
    titleSomali: 'Erayada muujinaya inta jeer',
    description: 'Bar always ilaa never iyo booska ay jumladda ka galaan.',
    objectives: [
      'Lix frequency adverbs kala saar.',
      'Adverb-ka main verb ka hor dhig.',
      'Verb to be ka dib dhig.',
    ],
    type: 'grammar',
    minutes: 27,
    vocabulary: frequencyWords(),
    grammarTopic: l9g,
    examples: l9e,
    fillQuestion: 'I ___ study at night. (inta badan)',
    fillOptions: ['usually', 'am usually', 'does usually', 'usual'],
    fillAnswer: 'usually',
    grammarQuestion: 'She is ___ early.',
    grammarOptions: ['always', 'always is', 'does always', 'early always'],
    grammarAnswer: 'always',
    mistakeQuestion: 'Kee ayaa sax ah?',
    mistakeOptions: [
      'I study usually at night.',
      'I usually study at night.',
      'I am usually study.',
      'I does usually study.',
    ],
    mistakeAnswer: 'I usually study at night.',
    arrangeQuestion: 'Kala hagaaji: football / sometimes / He / plays',
    arrangeAnswer: 'He sometimes plays football.',
    readingQuestion:
        '“Ali never drinks coffee at night.” Immisa jeer ayuu habeenkii kafee cabbaa?',
    readingOptions: ['Mar kasta', 'Inta badan', 'Mararka qaar', 'Marnaba'],
    readingAnswer: 'Marnaba',
    dialogueQuestion: 'Qofku quraac ma cunaa mar kasta?',
    dialogueOptions: ['Haa', 'Maya', 'Si dhif ah', 'Lama sheegin'],
    dialogueAnswer: 'Haa',
    speaking:
        'Samee lix jumladood oo isticmaala always, usually, often, sometimes, rarely iyo never.',
    writing:
        'Qor sagaal jumladood oo frequency expressions leh; mid verb to be ah ku dar.',
    summary:
        'Frequency adverb wuxuu main verb ka hor yimaadaa, laakiin be ka dib: I usually study; She is always early.',
  );

  final l10e = e(
    'First, I wake up at six.',
    'Marka hore, waxaan kacaa lixda.',
    'Then, I pray and eat breakfast.',
    'Kadib, waan tukadaa oo quraacdaa.',
    'After that, I go to work at eight.',
    'Intaas kadib, shaqada ayaan aadaa siddeedda.',
    'I finish work at four.',
    'Waxaan shaqada dhammeeyaa afarta.',
    'In the evening, I study English.',
    'Fiidkii, English ayaan bartaa.',
    'Finally, I go to bed at ten.',
    'Ugu dambayn, sariirta ayaan aadaa tobanka.',
  );
  final l10g = grammar(
    titleEnglish: 'Sequencing a routine',
    titleSomali: 'Isku xirka routine-ka',
    explanation:
        'First, then, after that iyo finally waxay hawlaha u kala hormariyaan si fudud. Time expressions sida at six iyo in the evening waxay sheegaan waqtiga.',
    rule:
        'First + first action; then/after that + next action; finally + last action',
    structure: 'Sequence word, + subject + Present Simple verb + time',
    positive: l10e,
    negative: [example("I don't work at night.", 'Habeenkii ma shaqeeyo.')],
    questions: [
      example('What do you do first?', 'Maxaad marka hore samaysaa?'),
      example('What do you do after that?', 'Maxaad samaysaa intaas kadib?'),
    ],
    mistakes: [
      'Ha ku bilaabin jumlad kasta then; erayada kala beddel.',
      'Routine-ka Present Simple ku qor.',
    ],
  );
  add(
    number: 10,
    titleEnglish: 'Talking About a Daily Routine',
    titleSomali: 'Ka hadalka jadwalka maalinlaha ah',
    description:
        'Isku xir hawlaha, waqtiga iyo sequence words si aad u samayso paragraph 6–10 jumladood ah.',
    objectives: [
      'Routine paragraph akhri oo faham.',
      'First/then/after that/finally isticmaal.',
      '6–10 jumladood oo isku xiran qor.',
    ],
    type: 'writing',
    minutes: 32,
    vocabulary: routineWords(),
    grammarTopic: l10g,
    examples: l10e,
    fillQuestion: '___, I wake up. Then, I eat breakfast.',
    fillOptions: ['Finally', 'First', 'Never', 'After work'],
    fillAnswer: 'First',
    grammarQuestion: 'Hawsha ugu dambaysa waxaa lagu bilaabaa…',
    grammarOptions: ['First', 'Then', 'Finally', 'Usually'],
    grammarAnswer: 'Finally',
    mistakeQuestion: 'Kee ayaa routine sax ah?',
    mistakeOptions: [
      'First I wakes up.',
      'First, I wake up.',
      'First, I waking up.',
      'First, does I wake up.',
    ],
    mistakeAnswer: 'First, I wake up.',
    arrangeQuestion: 'Kala hagaaji: work / After / I / that / go / to',
    arrangeAnswer: 'After that, I go to work.',
    readingQuestion:
        'Ahmed wakes at six, works at eight, finishes at four, studies in the evening, and sleeps at ten. Goormuu shaqada dhammeeyaa?',
    readingOptions: ['Lixda', 'Siddeedda', 'Afarta', 'Tobanka'],
    readingAnswer: 'Afarta',
    dialogueQuestion: 'Qofku maxuu ugu dambayn sameeyaa?',
    dialogueOptions: [
      'Wuu kacaa',
      'Wuu quraacdaa',
      'Wuxuu sariirta aadaa tobanka',
      'Wuxuu shaqada bilaabaa',
    ],
    dialogueAnswer: 'Wuxuu sariirta aadaa tobanka',
    speaking:
        'Sharax routine arday ama shaqaale male-awaal ah 6–10 jumladood, sequence words isticmaal.',
    writing:
        'Qor paragraph 8–10 jumladood ah oo routine male-awaal ah iyo waqtiyo leh.',
    summary:
        'First, then, after that iyo finally waxay routine-ka ka dhigaan mid isku xiran oo si fudud loo raaci karo.',
  );

  final l11e = e(
    'What time do you wake up?',
    'Saacad imisa ayaad kacdaa?',
    'When do you go to work?',
    'Goorma ayaad shaqada tagtaa?',
    'Do you eat breakfast?',
    'Ma quraacataa?',
    'Where do you study?',
    'Xaggee wax ku barataa?',
    'Does your brother work?',
    'Walaalkaa ma shaqeeyaa?',
    'Does he study at night?',
    'Miyuu wax bartaa habeenkii?',
  );
  final l11g = grammar(
    titleEnglish: "Asking about someone's routine",
    titleSomali: 'Weydiinta routine-ka qof kale',
    explanation:
        'Qofka aad la hadlayso waxaad u isticmaashaa do you. Qof kale he/she waxaad u isticmaashaa does. What time, when, where iyo what waxay weydiiyaan faahfaahin.',
    rule: 'WH + do + you + base? WH + does + he/she + base?',
    structure: 'Question word + do/does + subject + base verb?',
    positive: [
      example('I wake up at six.', 'Waxaan kacaa lixda.'),
      example(
        'She goes to school at seven.',
        'Waxay iskuulka tagtaa toddobada.',
      ),
      example('He works in a shop.', 'Wuxuu ka shaqeeyaa dukaan.'),
      example('We study at home.', 'Guriga ayaan wax ku barannaa.'),
      example('They eat breakfast.', 'Way quraacdaan.'),
      example('You work in the evening.', 'Fiidkii ayaad shaqaysaa.'),
    ],
    negative: [
      example("No, I don't.", 'Maya.'),
      example("No, he doesn't.", 'Maya.'),
    ],
    questions: l11e,
    mistakes: [
      'Does your brother works? waa khalad; Does your brother work? ayaa sax ah.',
      'What time you wake up? halkii ka dheh What time do you wake up?',
    ],
  );
  add(
    number: 11,
    titleEnglish: "Asking About Someone's Routine",
    titleSomali: 'Weydiinta jadwalka qof kale',
    description:
        'Bar wareysi routine ah oo u dhexeeya arday, shaqaale, ganacsade ama saaxiib.',
    objectives: [
      'Routine qof kale su’aalo ka weydii.',
      'Do you iyo does he/she kala saar.',
      'Role-play wareysi gaaban samee.',
    ],
    type: 'speaking',
    minutes: 29,
    vocabulary: routineQuestionWords(),
    grammarTopic: l11g,
    examples: l11e,
    fillQuestion: 'What time ___ she go to school?',
    fillOptions: ['do', 'does', 'is', 'has'],
    fillAnswer: 'does',
    grammarQuestion: '___ your brother work?',
    grammarOptions: ['Do', 'Does', 'Is', 'Are'],
    grammarAnswer: 'Does',
    mistakeQuestion: 'Sax “Does your brother works?”',
    mistakeOptions: [
      'Does your brother work?',
      'Do your brother works?',
      'Your brother does works?',
      'Does brother working?',
    ],
    mistakeAnswer: 'Does your brother work?',
    arrangeQuestion: 'Kala hagaaji: evening / do / What / the / in / you / do',
    arrangeAnswer: 'What do you do in the evening?',
    readingQuestion:
        '“Amina wakes at six and studies at school.” Xaggee ayay wax ku barataa?',
    readingOptions: ['Guriga', 'Iskuulka', 'Dukaanka', 'Xafiiska'],
    readingAnswer: 'Iskuulka',
    dialogueQuestion: 'Ganacsaduhu saacad imisa ayuu dukaanka furaa?',
    dialogueOptions: ['Lixda', 'Toddobada', 'Siddeedda', 'Tobanka'],
    dialogueAnswer: 'Toddobada',
    speaking:
        'Samee role-play laba qof oo jadwalkooda ka hadlaya; ugu yaraan lix su’aalood.',
    writing:
        'Qor wareysi routine ah: 6 su’aalood iyo 6 jawaabood oo arday ama shaqaale male-awaal ah.',
    summary:
        'Do you… qofka aad la hadlayso; Does he/she… qof kale. WH word wuxuu bixiyaa time, place ama activity.',
  );

  final l12e = e(
    'I wake up at six.',
    'Waxaan kacaa lixda.',
    'She studies English every day.',
    'Maalin kasta English ayay barataa.',
    "We don't work at night.",
    'Habeenkii ma shaqayno.',
    'Does he go to school?',
    'Iskuulka ma tagaa?',
    'I usually eat breakfast.',
    'Inta badan waan quraacdaa.',
    'Finally, they return home.',
    'Ugu dambayn, guriga ayay ku noqdaan.',
  );
  add(
    number: 12,
    titleEnglish: 'Unit Review',
    titleSomali: 'Dib-u-eegista Unit 5',
    description:
        'Dib u eeg activities, Present Simple positive/negative/questions, third person, frequency iyo routine paragraph.',
    objectives: [
      'Isku dar dhammaan grammar-ka Unit 5.',
      'Sax khaladaadka do/does iyo s/es/ies.',
      'Routine dhammaystiran qor oo ka hadal.',
    ],
    type: 'review',
    minutes: 40,
    vocabulary: reviewWords(),
    examples: l12e,
    fillQuestion: 'She ___ English every day.',
    fillOptions: ['study', 'studies', 'studys', 'studying'],
    fillAnswer: 'studies',
    grammarQuestion: 'Does he ___ at night?',
    grammarOptions: ['works', 'work', 'working', 'worked'],
    grammarAnswer: 'work',
    mistakeQuestion: 'Kee ayaa sax ah?',
    mistakeOptions: [
      "She doesn't goes.",
      "She doesn't go.",
      "She don't goes.",
      'She not go.',
    ],
    mistakeAnswer: "She doesn't go.",
    arrangeQuestion: 'Kala hagaaji: breakfast / usually / I / eat',
    arrangeAnswer: 'I usually eat breakfast.',
    readingQuestion:
        '“Ali works at eight, finishes at four, and studies in the evening.” Goormuu wax bartaa?',
    readingOptions: ['Subaxdii', 'Duhurkii', 'Fiidkii', 'Habeen dambe'],
    readingAnswer: 'Fiidkii',
    dialogueQuestion: 'Review dialogue: qofku habeenkii ma shaqeeyaa?',
    dialogueOptions: ['Haa', 'Maya', 'Mar kasta', 'Lama sheegin'],
    dialogueAnswer: 'Maya',
    speaking:
        'Ka hadal routine arday iyo routine shaqaale; positive, negative, question iyo frequency words ku dar.',
    writing:
        'Qor 8–10 jumladood oo routine ah; kadib laba negative iyo laba question ka samee.',
    summary:
        'Waxaad dib u eegtay activities, Present Simple, do/does, don’t/doesn’t, third-person forms, frequency iyo sequencing.',
    review: true,
  );

  final quiz = <Json>[
    exercise(
      'a1-u05-q01',
      'multipleChoice',
      'Wake up waa…',
      ['Sariirta aad', 'Hurdada ka baraarug', 'Qado cun', 'Shaqo dhammee'],
      'Hurdada ka baraarug',
      'Wake up waa hurdada ka baraarug.',
    ),
    exercise(
      'a1-u05-q02',
      'multipleChoice',
      '“Do homework” maxay ka dhigan tahay?',
      ['Shaqo-guri samee', 'Shir ka qaybgal', 'Dukaan fur', 'Quraac cun'],
      'Shaqo-guri samee',
      'Do homework waa shaqo-guri samee.',
    ),
    exercise(
      'a1-u05-q03',
      'multipleChoice',
      'Ganacsaduhu subaxdii dukaanka…',
      ['sleeps', 'opens', 'studies', 'reads'],
      'opens',
      'Open the shop waa dukaanka fur.',
    ),
    exercise(
      'a1-u05-q04',
      'multipleChoice',
      '“Take a break” waa…',
      ['Nasasho qaado', 'Imtixaan qaado', 'Farriin dir', 'Casho kari'],
      'Nasasho qaado',
      'Take a break waa nasasho qaado.',
    ),
    exercise(
      'a1-u05-q05',
      'multipleChoice',
      'Go to bed iyo sleep farqigoodu waa…',
      [
        'Midna ma jiro',
        'Go to bed waa sariirta aad; sleep waa hurdo',
        'Sleep waa shaqo',
        'Go to bed waa quraac',
      ],
      'Go to bed waa sariirta aad; sleep waa hurdo',
      'Labada hawlood waa isku dhow yihiin laakiin isku mid ma aha.',
    ),
    exercise(
      'a1-u05-q06',
      'multipleChoice',
      '“Attend class” waa…',
      [
        'Fasalka ka qaybgal',
        'Guriga ku noqo',
        'Shaqada bilow',
        'Telefishan daawo',
      ],
      'Fasalka ka qaybgal',
      'Attend class waa fasalka ka qaybgal.',
    ),
    exercise(
      'a1-u05-q07',
      'fillInTheBlank',
      'I ___ English every day.',
      ['studies', 'study', 'studys', 'studying'],
      'study',
      'I waxaa la socda base verb study.',
    ),
    exercise(
      'a1-u05-q08',
      'fillInTheBlank',
      'He ___ at a bank.',
      ['work', 'works', 'workes', 'working'],
      'works',
      'He + works.',
    ),
    exercise(
      'a1-u05-q09',
      'fillInTheBlank',
      'She ___ to school.',
      ['go', 'goes', 'gos', 'going'],
      'goes',
      'Go wuxuu he/she la noqdaa goes.',
    ),
    exercise(
      'a1-u05-q10',
      'fillInTheBlank',
      'He ___ television.',
      ['watch', 'watchs', 'watches', 'watchies'],
      'watches',
      'Watch wuxuu qaataa -es.',
    ),
    exercise(
      'a1-u05-q11',
      'fillInTheBlank',
      'She ___ English.',
      ['study', 'studys', 'studies', 'studyes'],
      'studies',
      'Consonant + y: study→studies.',
    ),
    exercise(
      'a1-u05-q12',
      'fillInTheBlank',
      'He ___ football.',
      ['plaies', 'plays', 'playes', 'play'],
      'plays',
      'Play wuxuu vowel + y leeyahay; wuxuu qaataa -s.',
    ),
    exercise(
      'a1-u05-q13',
      'fillInTheBlank',
      "I ___ drink coffee.",
      ["doesn't", "don't", 'am not', 'not'],
      "don't",
      "I waxaa la socda don't.",
    ),
    exercise(
      'a1-u05-q14',
      'fillInTheBlank',
      "She ___ work at night.",
      ["don't", "doesn't", 'is not', 'not'],
      "doesn't",
      "She waxaa la socda doesn't.",
    ),
    exercise(
      'a1-u05-q15',
      'multipleChoice',
      'Kee ayaa sax ah?',
      [
        "She doesn't goes.",
        "She doesn't go.",
        "She don't go.",
        'She not goes.',
      ],
      "She doesn't go.",
      "Doesn't ka dib base verb go.",
    ),
    exercise(
      'a1-u05-q16',
      'multipleChoice',
      'Negative-ka “They live here” waa…',
      [
        "They doesn't live here.",
        "They don't live here.",
        'They not lives here.',
        "They don't lives here.",
      ],
      "They don't live here.",
      "They + don't + live.",
    ),
    exercise(
      'a1-u05-q17',
      'multipleChoice',
      'Negative-ka “He works at night” waa…',
      [
        "He doesn't work at night.",
        "He don't works at night.",
        'He not work at night.',
        "He doesn't works at night.",
      ],
      "He doesn't work at night.",
      "He + doesn't + base work.",
    ),
    exercise(
      'a1-u05-q18',
      'fillInTheBlank',
      '___ you work?',
      ['Does', 'Do', 'Are', 'Is'],
      'Do',
      'You waxaa question ahaan la socda do.',
    ),
    exercise(
      'a1-u05-q19',
      'fillInTheBlank',
      '___ he go to school?',
      ['Do', 'Does', 'Is', 'Has'],
      'Does',
      'He waxaa question ahaan la socda does.',
    ),
    exercise(
      'a1-u05-q20',
      'multipleChoice',
      'Kee ayaa sax ah?',
      ['Does he works?', 'Does he work?', 'Do he work?', 'He does works?'],
      'Does he work?',
      'Does ka dib base verb work.',
    ),
    exercise(
      'a1-u05-q21',
      'multipleChoice',
      'Short answer-ka “Does she study?” waa…',
      ['Yes, she do.', 'Yes, she does.', 'Yes, she is.', 'Yes, she study.'],
      'Yes, she does.',
      'Does question wuxuu qaataa Yes, she does.',
    ),
    exercise(
      'a1-u05-q22',
      'multipleChoice',
      'Su’aasha saxda ah ee waqtiga waa…',
      [
        'What time you wake up?',
        'What time do you wake up?',
        'Do what time you wake?',
        'What do time wake up?',
      ],
      'What time do you wake up?',
      'WH + do + subject + base verb.',
    ),
    exercise(
      'a1-u05-q23',
      'fillInTheBlank',
      'I ___ eat breakfast. (mar kasta)',
      ['always', 'never', 'rarely', 'am always'],
      'always',
      'Always waa mar kasta, main verb ka hor.',
    ),
    exercise(
      'a1-u05-q24',
      'multipleChoice',
      '“Si dhif ah” waa…',
      ['often', 'usually', 'rarely', 'always'],
      'rarely',
      'Rarely waa si dhif ah.',
    ),
    exercise(
      'a1-u05-q25',
      'multipleChoice',
      'Kee ayaa sax ah?',
      [
        'She always is early.',
        'She is always early.',
        'She does always early.',
        'She early always.',
      ],
      'She is always early.',
      'Frequency adverb wuxuu be ka dib yimaadaa.',
    ),
    exercise(
      'a1-u05-q26',
      'readingComprehension',
      'Ahmed wakes at six, starts work at eight, and finishes at four. Goormuu shaqada bilaabaa?',
      ['Lixda', 'Siddeedda', 'Afarta', 'Tobanka'],
      'Siddeedda',
      'Routine-ku wuxuu sheegay starts work at eight.',
    ),
    exercise(
      'a1-u05-q27',
      'readingComprehension',
      'Hani studies after school and goes to bed at ten. Goormay wax barataa?',
      ['Iskuulka ka hor', 'Iskuulka kadib', 'Tobanka kadib', 'Subaxdii'],
      'Iskuulka kadib',
      'Waxay wax barataa after school.',
    ),
    exercise(
      'a1-u05-q28',
      'readingComprehension',
      'Ali never drinks coffee at night. Immisa jeer ayuu habeenkii kafee cabbaa?',
      ['Mar kasta', 'Inta badan', 'Mararka qaar', 'Marnaba'],
      'Marnaba',
      'Never waa marnaba.',
    ),
    exercise(
      'a1-u05-q29',
      'somaliToEnglish',
      'U beddel: “Waxay shaqada tagtaa siddeedda.”',
      [
        'She go to work at eight.',
        'She goes to work at eight.',
        'She does goes at eight.',
        'She going to work at eight.',
      ],
      'She goes to work at eight.',
      'She + goes + to work + at eight.',
    ),
    exercise(
      'a1-u05-q30',
      'somaliToEnglish',
      'U beddel: “Habeenkii ma shaqeeyo.”',
      [
        "He doesn't work at night.",
        "He don't works at night.",
        'He not work night.',
        "He doesn't works at night.",
      ],
      "He doesn't work at night.",
      "He + doesn't + base work + at night.",
    ),
  ];

  final unit = {
    'id': 'a1-u05',
    'levelId': 'A1',
    'unitNumber': 5,
    'titleEnglish': 'Daily Activities and Routines',
    'titleSomali': 'Hawlaha iyo Jadwalka Maalinlaha ah',
    'introductionSomali':
        'Unit-kan waxaad ku baranaysaa hawlaha subaxda ilaa habeenka, routine-ka ardayda, shaqaalaha iyo ganacsatada, iyo Present Simple positive, negative, questions iyo frequency words.',
    'requiredPreviousUnitId': 'a1-u04',
    'lessons': lessons,
    'unitQuiz': quiz,
    'passingScore': 70,
  };
  final output = const JsonEncoder.withIndent('  ').convert(unit);
  File('assets/content/a1/unit_05.json').writeAsStringSync('$output\n');
}
