import 'dart:convert';
import 'dart:io';

typedef Json = Map<String, dynamic>;
typedef Seed = ({
  String word,
  String meaning,
  String pronunciation,
  String en,
  String so,
});

Json vocabulary(Seed seed, {String type = 'time phrase'}) => {
  'englishWord': seed.word,
  'somaliMeaning': seed.meaning,
  'partOfSpeech': type,
  'pronunciation': seed.pronunciation,
  'exampleEnglish': seed.en,
  'exampleSomali': seed.so,
  'explanationSomali':
      '${seed.word} waxaa loola jeedaa ${seed.meaning}. Qoraalka pronunciation-ku waa hagitaan fudud, mana aha IPA.',
  'commonMistakeSomali': '',
};

List<Json> vocab(List<Seed> seeds, {String type = 'time phrase'}) =>
    seeds.map((seed) => vocabulary(seed, type: type)).toList();

Map<String, String> ex(String english, String somali) => {
  'english': english,
  'somali': somali,
};

Json line(String speaker, String english, String somali) => {
  'speaker': speaker,
  'english': english,
  'somali': somali,
};

Json dialogue(String title, List<Json> lines) => {
  'titleSomali': title,
  'lines': lines,
};

List<Json> twoDialogues({
  required String titleOne,
  required String questionOne,
  required String questionOneSomali,
  required String answerOne,
  required String answerOneSomali,
  required String titleTwo,
  required String questionTwo,
  required String questionTwoSomali,
  required String answerTwo,
  required String answerTwoSomali,
}) => [
  dialogue(titleOne, [
    line('A', questionOne, questionOneSomali),
    line('B', answerOne, answerOneSomali),
    line('A', 'Thank you.', 'Mahadsanid.'),
    line('B', 'You are welcome.', 'Adigaa mudan.'),
  ]),
  dialogue(titleTwo, [
    line('A', questionTwo, questionTwoSomali),
    line('B', answerTwo, answerTwoSomali),
    line('A', 'Is that correct?', 'Taasi ma sax baa?'),
    line('B', 'Yes, that is correct.', 'Haa, waa sax.'),
  ]),
];

Json exercise(
  String id,
  String type,
  String question,
  List<String> options,
  String answer,
  String explanation,
) => {
  'id': id,
  'type': type,
  'question': question,
  'options': options,
  'correctAnswer': answer,
  'explanationSomali': explanation,
};

Json grammar({
  required String titleEnglish,
  required String titleSomali,
  required String explanation,
  required String rule,
  required String structure,
  required List<Map<String, String>> examples,
  required List<String> mistakes,
  List<Map<String, String>> negative = const [],
  List<Map<String, String>> questions = const [],
}) => {
  'titleEnglish': titleEnglish,
  'titleSomali': titleSomali,
  'explanationSomali': explanation,
  'rule': rule,
  'sentenceStructure': structure,
  'positiveExamples': examples,
  'negativeExamples': negative,
  'questionExamples': questions,
  'commonMistakesSomali': mistakes,
  'practiceQuestions': const [],
};

List<Json> practices(
  String id,
  List<Json> words,
  List<Map<String, String>> examples, {
  required String fillQuestion,
  required List<String> fillOptions,
  required String fillAnswer,
  required String conversionQuestion,
  required List<String> conversionOptions,
  required String conversionAnswer,
  required String grammarQuestion,
  required List<String> grammarOptions,
  required String grammarAnswer,
  required String mistakeQuestion,
  required List<String> mistakeOptions,
  required String mistakeAnswer,
  required String arrangeQuestion,
  required String arrangeAnswer,
  required String readingQuestion,
  required List<String> readingOptions,
  required String readingAnswer,
  required String dialogueQuestion,
  required List<String> dialogueOptions,
  required String dialogueAnswer,
  required String speaking,
  required String writing,
  bool review = false,
}) {
  final result = <Json>[
    exercise(
      '$id-p01',
      'multipleChoice',
      '“${words[0]['englishWord']}” maxay ka dhigan tahay?',
      [
        words[2]['somaliMeaning'] as String,
        words[0]['somaliMeaning'] as String,
        words[3]['somaliMeaning'] as String,
        words[1]['somaliMeaning'] as String,
      ],
      words[0]['somaliMeaning'] as String,
      '${words[0]['englishWord']} macnihiisu waa ${words[0]['somaliMeaning']}.',
    ),
    exercise(
      '$id-p02',
      'fillInTheBlank',
      fillQuestion,
      fillOptions,
      fillAnswer,
      '“$fillAnswer” ayaa jumladda ama waqtiga ka dhigaya mid sax ah.',
    ),
    exercise(
      '$id-p03',
      'matchWords',
      'Isku aadi “${words[1]['englishWord']}” iyo macnihiisa.',
      [
        words[3]['somaliMeaning'] as String,
        words[2]['somaliMeaning'] as String,
        words[1]['somaliMeaning'] as String,
        words[0]['somaliMeaning'] as String,
      ],
      words[1]['somaliMeaning'] as String,
      '${words[1]['englishWord']} waxaa loola jeedaa ${words[1]['somaliMeaning']}.',
    ),
    exercise(
      '$id-p04',
      'multipleChoice',
      conversionQuestion,
      conversionOptions,
      conversionAnswer,
      'Beddelidda saxda ahi waa “$conversionAnswer”. Hubi saacadda xigta marka to la isticmaalo.',
    ),
    exercise(
      '$id-p05',
      'chooseGrammar',
      grammarQuestion,
      grammarOptions,
      grammarAnswer,
      'Qaabka saxda ahi waa “$grammarAnswer”. Waqtiga, maalinta ama bisha ayaa go’aamisa erayga la isticmaalayo.',
    ),
    exercise(
      '$id-p06',
      'multipleChoice',
      mistakeQuestion,
      mistakeOptions,
      mistakeAnswer,
      'Saxitaanku waa “$mistakeAnswer”.',
    ),
    exercise(
      '$id-p07',
      'arrangeSentence',
      arrangeQuestion,
      const [],
      arrangeAnswer,
      'Kala horreynta saxda ahi waa “$arrangeAnswer”.',
    ),
    exercise(
      '$id-p08',
      'englishToSomali',
      'Turjun: ${examples[0]['english']}',
      [
        examples[3]['somali']!,
        examples[2]['somali']!,
        examples[0]['somali']!,
        examples[1]['somali']!,
      ],
      examples[0]['somali']!,
      'Turjumaadda saxda ahi waxay ilaalinaysaa waqtiga iyo macnaha jumladda.',
    ),
    exercise(
      '$id-p09',
      'somaliToEnglish',
      'U beddel English: ${examples[1]['somali']}',
      [
        examples[4]['english']!,
        examples[1]['english']!,
        examples[0]['english']!,
        examples[3]['english']!,
      ],
      examples[1]['english']!,
      'Qaabka dabiiciga ah waa “${examples[1]['english']}”.',
    ),
    exercise(
      '$id-p10',
      'readingComprehension',
      readingQuestion,
      readingOptions,
      readingAnswer,
      'Jawaabta “$readingAnswer” waxay si toos ah uga timid waqtiga, taariikhda ama timetable-ka.',
    ),
    exercise(
      '$id-p11',
      'readingComprehension',
      dialogueQuestion,
      dialogueOptions,
      dialogueAnswer,
      'Wada hadalka si taxaddar leh u akhri; jawaabta saxda ahi waa “$dialogueAnswer”.',
    ),
    exercise(
      '$id-p12',
      'speakingPrompt',
      speaking,
      const [],
      'Teacher review',
      'Isticmaal waqti, taariikh ama jadwal male-awaal ah; xog dhab ah looma baahna.',
    ),
    exercise(
      '$id-p13',
      'shortWriting',
      writing,
      const [],
      'Teacher review',
      'Hubi capital letters-ka days/months iyo at/on/in.',
    ),
  ];
  if (review) result.addAll(reviewExtras(id));
  return result;
}

List<Json> reviewExtras(String id) => [
  exercise(
    '$id-p14',
    'multipleChoice',
    '6:05 waa…',
    ['five to six', 'five past six', 'six past five', 'half past six'],
    'five past six',
    '6:05 waa shan daqiiqo oo lixda dhaafay.',
  ),
  exercise(
    '$id-p15',
    'multipleChoice',
    '8:40 waa…',
    [
      'twenty past eight',
      'twenty to eight',
      'twenty to nine',
      'quarter to nine',
    ],
    'twenty to nine',
    '8:40 waxaa 20 daqiiqo ka harsan sagaalka.',
  ),
  exercise(
    '$id-p16',
    'multipleChoice',
    '9:45 waa…',
    [
      'quarter past nine',
      'quarter to ten',
      'half past nine',
      'fifteen to nine',
    ],
    'quarter to ten',
    '9:45 waxaa 15 daqiiqo ka harsan tobanka.',
  ),
  exercise(
    '$id-p17',
    'fillInTheBlank',
    'I work ___ Monday.',
    ['at', 'on', 'in', 'to'],
    'on',
    'Maalin waxaa lala isticmaalaa on.',
  ),
  exercise(
    '$id-p18',
    'fillInTheBlank',
    'The course starts ___ September.',
    ['at', 'on', 'in', 'from'],
    'in',
    'Bil waxaa lala isticmaalaa in.',
  ),
  exercise(
    '$id-p19',
    'fillInTheBlank',
    'The lesson starts ___ eight o’clock.',
    ['at', 'on', 'in', 'after'],
    'at',
    'Saacad gaar ah waxaa lala isticmaalaa at.',
  ),
  exercise(
    '$id-p20',
    'multipleChoice',
    'Maalinta ka dambaysa Monday waa…',
    ['Sunday', 'Tuesday', 'Thursday', 'Friday'],
    'Tuesday',
    'Tuesday ayaa ka dambaysa Monday.',
  ),
  exercise(
    '$id-p21',
    'multipleChoice',
    'Bisha ka dambaysa September waa…',
    ['August', 'October', 'November', 'December'],
    'October',
    'October waa bisha tobnaad.',
  ),
  exercise(
    '$id-p22',
    'multipleChoice',
    '21st waxaa loo akhriyaa…',
    ['twenty', 'twenty-one', 'twenty-first', 'twentieth-one'],
    'twenty-first',
    '21st waa twenty-first.',
  ),
  exercise(
    '$id-p23',
    'readingComprehension',
    'Timetable: English 8:00–9:00; Mathematics 9:15–10:15. Goormay Mathematics bilaabataa?',
    ['8:00', '9:00', '9:15', '10:15'],
    '9:15',
    'Timetable-ku wuxuu sheegay Mathematics 9:15–10:15.',
  ),
  exercise(
    '$id-p24',
    'speakingPrompt',
    'Akhri shan waqti, sheeg toddobada maalmood, kadib samee ballan on Wednesday at ten.',
    const [],
    'Teacher review',
    'Past/to, capital letters iyo at/on si sax ah u isticmaal.',
  ),
  exercise(
    '$id-p25',
    'shortWriting',
    'Qor paragraph toddobaad male-awaal ah oo 8 jumladood leh; ku dar days, times, at/on/in iyo appointment.',
    const [],
    'Teacher review',
    'Maalmaha iyo bilaha capital letter ku bilow.',
  ),
];

Json lesson({
  required int number,
  required String titleEnglish,
  required String titleSomali,
  required String description,
  required List<String> objectives,
  required String type,
  required int minutes,
  required List<Json> vocabulary,
  Json? grammarTopic,
  required List<Map<String, String>> examples,
  required List<Json> dialogues,
  required List<Json> exercises,
  required String speaking,
  required String writing,
  required String summary,
}) {
  final id = 'a1-u06-l${number.toString().padLeft(2, '0')}';
  return {
    'id': id,
    'levelId': 'A1',
    'unitId': 'a1-u06',
    'lessonNumber': number,
    'titleEnglish': titleEnglish,
    'titleSomali': titleSomali,
    'shortDescriptionSomali': description,
    'learningObjectives': objectives,
    'lessonType': type,
    'estimatedMinutes': minutes,
    'difficulty': 'beginner',
    'isLocked': number != 1,
    'requiredPreviousLessonId': number == 1
        ? null
        : 'a1-u06-l${(number - 1).toString().padLeft(2, '0')}',
    'vocabulary': vocabulary,
    'grammar': grammarTopic,
    'examples': examples,
    'dialogues': dialogues,
    'practiceExercises': exercises,
    'speakingPractice': speaking,
    'writingPractice': writing,
    'summarySomali': summary,
    'quizQuestions': exercises
        .take(3)
        .toList()
        .asMap()
        .entries
        .map(
          (entry) => {
            ...entry.value,
            'id': '$id-q${(entry.key + 1).toString().padLeft(2, '0')}',
          },
        )
        .toList(),
  };
}

List<Map<String, String>> examples(List<(String, String)> values) =>
    values.map((value) => ex(value.$1, value.$2)).toList();

void main() {
  final lessons = <Json>[];

  void add({
    required int number,
    required String titleEnglish,
    required String titleSomali,
    required String description,
    required List<String> objectives,
    required String type,
    required int minutes,
    required List<Json> vocabulary,
    Json? grammarTopic,
    required List<Map<String, String>> lessonExamples,
    required List<Json> lessonDialogues,
    required String fillQuestion,
    required List<String> fillOptions,
    required String fillAnswer,
    required String conversionQuestion,
    required List<String> conversionOptions,
    required String conversionAnswer,
    required String grammarQuestion,
    required List<String> grammarOptions,
    required String grammarAnswer,
    required String mistakeQuestion,
    required List<String> mistakeOptions,
    required String mistakeAnswer,
    required String arrangeQuestion,
    required String arrangeAnswer,
    required String readingQuestion,
    required List<String> readingOptions,
    required String readingAnswer,
    required String dialogueQuestion,
    required List<String> dialogueOptions,
    required String dialogueAnswer,
    required String speaking,
    required String writing,
    required String summary,
    bool review = false,
  }) {
    final id = 'a1-u06-l${number.toString().padLeft(2, '0')}';
    lessons.add(
      lesson(
        number: number,
        titleEnglish: titleEnglish,
        titleSomali: titleSomali,
        description: description,
        objectives: objectives,
        type: type,
        minutes: minutes,
        vocabulary: vocabulary,
        grammarTopic: grammarTopic,
        examples: lessonExamples,
        dialogues: lessonDialogues,
        exercises: practices(
          id,
          vocabulary,
          lessonExamples,
          fillQuestion: fillQuestion,
          fillOptions: fillOptions,
          fillAnswer: fillAnswer,
          conversionQuestion: conversionQuestion,
          conversionOptions: conversionOptions,
          conversionAnswer: conversionAnswer,
          grammarQuestion: grammarQuestion,
          grammarOptions: grammarOptions,
          grammarAnswer: grammarAnswer,
          mistakeQuestion: mistakeQuestion,
          mistakeOptions: mistakeOptions,
          mistakeAnswer: mistakeAnswer,
          arrangeQuestion: arrangeQuestion,
          arrangeAnswer: arrangeAnswer,
          readingQuestion: readingQuestion,
          readingOptions: readingOptions,
          readingAnswer: readingAnswer,
          dialogueQuestion: dialogueQuestion,
          dialogueOptions: dialogueOptions,
          dialogueAnswer: dialogueAnswer,
          speaking: speaking,
          writing: writing,
          review: review,
        ),
        speaking: speaking,
        writing: writing,
        summary: summary,
      ),
    );
  }

  final l1e = examples([
    ('It is one o’clock.', 'Waa kowda saacad.'),
    ('It is two o’clock.', 'Waa labada saacad.'),
    ('It is three ten.', 'Waa saddexda iyo toban daqiiqo.'),
    ('It is four twenty.', 'Waa afarta iyo labaatan daqiiqo.'),
    ('It is five twenty-five.', 'Waa shanta iyo shan iyo labaatan daqiiqo.'),
    ('It is six thirty.', 'Waa lixda iyo badhka.'),
    ('It is seven fifteen.', 'Waa toddobada iyo rubuc.'),
    ('It is eight forty.', 'Waa siddeedda iyo afartan daqiiqo.'),
    ('It is nine forty-five.', 'Waa sagaalka iyo shan iyo afartan daqiiqo.'),
    ('It is ten fifty.', 'Waa tobanka iyo konton daqiiqo.'),
    ('It is noon.', 'Waa duhur.'),
    ('It is midnight.', 'Waa saqda dhexe.'),
  ]);
  final l1v = vocab([
    (
      word: 'What time is it?',
      meaning: 'Saacaddu waa imisa?',
      pronunciation: 'wot taaym iz it',
      en: 'What time is it?',
      so: 'Saacaddu waa imisa?',
    ),
    (
      word: "What's the time?",
      meaning: 'Waa imisa saacaddu?',
      pronunciation: 'wots dha taaym',
      en: "What's the time?",
      so: 'Waa imisa saacaddu?',
    ),
    (
      word: 'Do you know the time?',
      meaning: 'Ma taqaan saacadda?',
      pronunciation: 'duu yuu noo dha taaym',
      en: 'Do you know the time?',
      so: 'Ma taqaan saacadda?',
    ),
    (
      word: "O'clock",
      meaning: 'Saacad buuxda',
      pronunciation: 'o-klook',
      en: "It is six o'clock.",
      so: 'Waa lixda saacad.',
    ),
    (
      word: 'Noon',
      meaning: 'Duhurkii 12:00',
      pronunciation: 'nuun',
      en: 'It is noon.',
      so: 'Waa duhur.',
    ),
    (
      word: 'Midnight',
      meaning: 'Saqda dhexe 12:00 habeenimo',
      pronunciation: 'mid-naayt',
      en: 'It is midnight.',
      so: 'Waa saqda dhexe.',
    ),
    (
      word: 'Six thirty',
      meaning: '6:30',
      pronunciation: 'siks ther-ti',
      en: 'It is six thirty.',
      so: 'Waa 6:30.',
    ),
    (
      word: 'Seven fifteen',
      meaning: '7:15',
      pronunciation: 'se-van fif-tiin',
      en: 'It is seven fifteen.',
      so: 'Waa 7:15.',
    ),
    (
      word: 'Nine forty-five',
      meaning: '9:45',
      pronunciation: 'naayn foor-ti faayv',
      en: 'It is nine forty-five.',
      so: 'Waa 9:45.',
    ),
    (
      word: 'Start work',
      meaning: 'Shaqada bilow',
      pronunciation: 'staart werk',
      en: 'I start work at eight.',
      so: 'Waxaan shaqada bilaabaa siddeedda.',
    ),
    (
      word: 'Begin',
      meaning: 'Bilow',
      pronunciation: 'bi-gin',
      en: 'The lesson begins at nine.',
      so: 'Casharku wuxuu bilaabmaa sagaalka.',
    ),
    (
      word: 'Digital time',
      meaning: 'Saacad tirooyin ah',
      pronunciation: 'di-ji-tal taaym',
      en: '6:30 is six thirty.',
      so: '6:30 waa six thirty.',
    ),
  ]);
  final l1g = grammar(
    titleEnglish: 'Asking and telling time',
    titleSomali: 'Weydiinta iyo sheegidda saacadda',
    explanation:
        'What time is it? waxay weydiinaysaa waqtiga hadda. What time do/does…? waxay weydiinaysaa goorta hawl joogto ahi dhacdo. Digital time-ka waxaa loo akhriyi karaa saacadda kadib daqiiqadaha.',
    rule: 'What time + is it? / What time + do/does + subject + base verb?',
    structure: 'It is + hour/minutes',
    examples: l1e.take(6).toList(),
    questions: examples([
      ('What time is it?', 'Saacaddu waa imisa?'),
      ('What time do you start work?', 'Saacad imisa ayaad shaqada bilowdaa?'),
      (
        'What time does the lesson begin?',
        'Saacad imisa ayuu casharku bilaabmaa?',
      ),
    ]),
    mistakes: [
      "O’clock waxaa la isticmaalaa saacad buuxda oo keliya.",
      '6:30 waxaa la oran karaa six thirty.',
    ],
  );
  add(
    number: 1,
    titleEnglish: 'Asking and Telling the Time',
    titleSomali: 'Weydiinta iyo sheegidda saacadda',
    description: 'Bar weydiinta saacadda, digital time, noon iyo midnight.',
    objectives: [
      'Saacadda weydii.',
      'Ugu yaraan 12 waqti akhri.',
      'Digital time erayo u beddel.',
    ],
    type: 'speaking',
    minutes: 31,
    vocabulary: l1v,
    grammarTopic: l1g,
    lessonExamples: l1e,
    lessonDialogues: twoDialogues(
      titleOne: 'Saacadda hadda',
      questionOne: 'What time is it?',
      questionOneSomali: 'Saacaddu waa imisa?',
      answerOne: 'It is six thirty.',
      answerOneSomali: 'Waa 6:30.',
      titleTwo: 'Bilowga casharka',
      questionTwo: 'What time does the lesson begin?',
      questionTwoSomali: 'Saacad imisa ayuu casharku bilaabmaa?',
      answerTwo: 'It begins at eight fifteen.',
      answerTwoSomali: 'Wuxuu bilaabmaa 8:15.',
    ),
    fillQuestion: 'It is six ___. (6:30)',
    fillOptions: ['thirteen', 'thirty', 'three', 'forty'],
    fillAnswer: 'thirty',
    conversionQuestion: '8:15 sidee digital ahaan loo akhriyaa?',
    conversionOptions: [
      'eight fifty',
      'eight fifteen',
      'fifteen eight',
      'eight forty-five',
    ],
    conversionAnswer: 'eight fifteen',
    grammarQuestion: 'Kee ayaa saacadda hadda weydiinaya?',
    grammarOptions: [
      'What time is it?',
      'Where is it?',
      'What day is it?',
      'How old is it?',
    ],
    grammarAnswer: 'What time is it?',
    mistakeQuestion: 'Kee ayaa sax ah 9:45?',
    mistakeOptions: [
      'nine forty-five',
      'nine fourteen-five',
      'forty-five nine',
      'nine four-five',
    ],
    mistakeAnswer: 'nine forty-five',
    arrangeQuestion: 'Kala hagaaji: time / What / it / is',
    arrangeAnswer: 'What time is it?',
    readingQuestion: '“The lesson begins at 8:15.” Goormuu casharku bilaabmaa?',
    readingOptions: ['8:05', '8:15', '8:30', '8:45'],
    readingAnswer: '8:15',
    dialogueQuestion: 'Wada hadalka koowaad saacaddu waa imisa?',
    dialogueOptions: ['6:15', '6:30', '7:30', '8:15'],
    dialogueAnswer: '6:30',
    speaking: 'Akhri 1:00, 2:10, 4:20, 6:30 iyo 9:45; kadib weydii saacadda.',
    writing: 'Qor shan digital times iyo qaabka English-ka ee loo akhriyo.',
    summary:
        'Waxaad baratay What time is it?, digital time, o’clock, noon iyo midnight.',
  );

  final l2e = examples([
    ('It is five past six.', 'Waa lixda iyo shan daqiiqo.'),
    ('It is ten past seven.', 'Waa toddobada iyo toban daqiiqo.'),
    ('It is twenty past eight.', 'Waa siddeedda iyo labaatan daqiiqo.'),
    (
      'It is twenty-five past nine.',
      'Waa sagaalka iyo shan iyo labaatan daqiiqo.',
    ),
    ('It is five to ten.', 'Waxaa shan daqiiqo ka harsan tobanka.'),
    ('It is ten to eleven.', 'Waxaa toban daqiiqo ka harsan kow iyo tobanka.'),
    (
      'It is twenty to twelve.',
      'Waxaa labaatan daqiiqo ka harsan laba iyo tobanka.',
    ),
    ('It is twenty-five to one.', 'Waxaa 25 daqiiqo ka harsan kowda.'),
  ]);
  final l2v = vocab([
    (
      word: 'Past',
      meaning: 'Saacadda dhaafay',
      pronunciation: 'paast',
      en: 'It is five past six.',
      so: 'Waa lixda iyo shan.',
    ),
    (
      word: 'To',
      meaning: 'Saacadda xigta ka harsan',
      pronunciation: 'tuu',
      en: 'It is ten to nine.',
      so: 'Waxaa toban ka harsan sagaalka.',
    ),
    (
      word: 'Five past',
      meaning: 'Shan daqiiqo dhaafay',
      pronunciation: 'faayv paast',
      en: 'It is five past six.',
      so: 'Waa lixda iyo shan.',
    ),
    (
      word: 'Ten past',
      meaning: 'Toban daqiiqo dhaafay',
      pronunciation: 'ten paast',
      en: 'It is ten past seven.',
      so: 'Waa toddobada iyo toban.',
    ),
    (
      word: 'Twenty past',
      meaning: 'Labaatan daqiiqo dhaafay',
      pronunciation: 'twen-ti paast',
      en: 'It is twenty past eight.',
      so: 'Waa siddeedda iyo labaatan.',
    ),
    (
      word: 'Twenty-five past',
      meaning: '25 daqiiqo dhaafay',
      pronunciation: 'twen-ti faayv paast',
      en: 'It is twenty-five past nine.',
      so: 'Waa sagaalka iyo 25.',
    ),
    (
      word: 'Five to',
      meaning: 'Shan daqiiqo ka harsan',
      pronunciation: 'faayv tuu',
      en: 'It is five to ten.',
      so: 'Shan ayaa ka harsan tobanka.',
    ),
    (
      word: 'Twenty to',
      meaning: 'Labaatan daqiiqo ka harsan',
      pronunciation: 'twen-ti tuu',
      en: 'It is twenty to twelve.',
      so: 'Labaatan ayaa ka harsan laba iyo tobanka.',
    ),
  ]);
  final l2g = grammar(
    titleEnglish: 'Past and to',
    titleSomali: 'Past iyo to',
    explanation:
        'Past wuxuu sheegaa daqiiqadaha saacadda hadda dhaafay, inta badan 1–30. To wuxuu sheegaa daqiiqadaha ka harsan saacadda xigta, inta badan 31–59.',
    rule: 'minutes + past + current hour; minutes remaining + to + next hour',
    structure: 'It is + minutes + past/to + hour',
    examples: l2e.take(6).toList(),
    mistakes: [
      '8:40 waa twenty to nine, ma aha twenty to eight.',
      'To marka la isticmaalo saacadda xigta sheeg.',
    ],
  );
  add(
    number: 2,
    titleEnglish: 'Past and To',
    titleSomali: 'Isticmaalka Past iyo To',
    description:
        'Bar daqiiqadaha saacadda dhaafay iyo kuwa ka harsan saacadda xigta.',
    objectives: [
      'Past sax u isticmaal.',
      'To iyo next hour sax u isticmaal.',
      'Digital time u beddel past/to.',
    ],
    type: 'grammar',
    minutes: 29,
    vocabulary: l2v,
    grammarTopic: l2g,
    lessonExamples: l2e,
    lessonDialogues: twoDialogues(
      titleOne: 'Waqtiga baska',
      questionOne: 'What time is it?',
      questionOneSomali: 'Saacaddu waa imisa?',
      answerOne: 'It is ten past seven.',
      answerOneSomali: 'Waa toddobada iyo toban.',
      titleTwo: 'Xiritaanka dukaanka',
      questionTwo: 'Is it eight forty?',
      questionTwoSomali: 'Ma 8:40 baa?',
      answerTwo: 'Yes, it is twenty to nine.',
      answerTwoSomali: 'Haa, labaatan ayaa ka harsan sagaalka.',
    ),
    fillQuestion: '6:05 is five ___ six.',
    fillOptions: ['to', 'past', 'at', 'in'],
    fillAnswer: 'past',
    conversionQuestion: '8:40 waa…',
    conversionOptions: [
      'twenty past eight',
      'twenty to eight',
      'twenty to nine',
      'forty to nine',
    ],
    conversionAnswer: 'twenty to nine',
    grammarQuestion: '9:50 waa…',
    grammarOptions: [
      'ten past nine',
      'ten to nine',
      'ten to ten',
      'fifty to ten',
    ],
    grammarAnswer: 'ten to ten',
    mistakeQuestion: 'Kee ayaa sax ah 7:10?',
    mistakeOptions: [
      'ten to seven',
      'ten past seven',
      'seven past ten',
      'twenty past seven',
    ],
    mistakeAnswer: 'ten past seven',
    arrangeQuestion: 'Kala hagaaji: nine / twenty / to / is / It',
    arrangeAnswer: 'It is twenty to nine.',
    readingQuestion:
        '“The shop closes at five to ten.” Digital time-keedu waa…',
    readingOptions: ['9:05', '9:50', '9:55', '10:05'],
    readingAnswer: '9:55',
    dialogueQuestion: '8:40 qaabka past/to waa kee?',
    dialogueOptions: [
      'twenty past eight',
      'twenty to nine',
      'ten to nine',
      'quarter to nine',
    ],
    dialogueAnswer: 'twenty to nine',
    speaking:
        'Akhri 6:05, 7:10, 8:20, 8:40 iyo 9:50 adigoo past/to isticmaalaya.',
    writing:
        'Shan digital times u beddel past/to; next hour si taxaddar leh u qor.',
    summary:
        'Past = daqiiqadaha dhaafay; to = daqiiqadaha ka harsan saacadda xigta.',
  );

  final l3e = examples([
    ('It is half past seven.', 'Waa toddobada iyo badhka.'),
    ('It is quarter past eight.', 'Waa siddeedda iyo rubuc.'),
    ('It is quarter to ten.', 'Waxaa rubuc ka harsan tobanka.'),
    ('It is half past twelve.', 'Waa laba iyo tobanka iyo badhka.'),
    ('6:30 is half past six.', '6:30 waa lixda iyo badhka.'),
    (
      '11:45 is quarter to twelve.',
      '11:45 waa rubuc ka harsan laba iyo tobanka.',
    ),
  ]);
  final l3v = vocab([
    (
      word: 'Half past',
      meaning: 'Saacadda iyo 30 daqiiqo',
      pronunciation: 'haaf paast',
      en: 'It is half past seven.',
      so: 'Waa toddobada iyo badhka.',
    ),
    (
      word: 'Quarter',
      meaning: 'Rubuc/15 daqiiqo',
      pronunciation: 'kwoor-tar',
      en: 'A quarter is fifteen minutes.',
      so: 'Rubuc waa 15 daqiiqo.',
    ),
    (
      word: 'Quarter past',
      meaning: 'Saacadda iyo 15 daqiiqo',
      pronunciation: 'kwoor-tar paast',
      en: 'It is quarter past eight.',
      so: 'Waa siddeedda iyo rubuc.',
    ),
    (
      word: 'Quarter to',
      meaning: '15 daqiiqo ka harsan saacadda xigta',
      pronunciation: 'kwoor-tar tuu',
      en: 'It is quarter to ten.',
      so: 'Rubuc ayaa ka harsan tobanka.',
    ),
    (
      word: 'Thirty minutes',
      meaning: '30 daqiiqo',
      pronunciation: 'ther-ti mi-nits',
      en: 'Half an hour is thirty minutes.',
      so: 'Nus saac waa 30 daqiiqo.',
    ),
    (
      word: 'Fifteen minutes',
      meaning: '15 daqiiqo',
      pronunciation: 'fif-tiin mi-nits',
      en: 'A quarter is fifteen minutes.',
      so: 'Rubuc waa 15 daqiiqo.',
    ),
  ]);
  final l3g = grammar(
    titleEnglish: 'Half and quarter',
    titleSomali: 'Nuska iyo rubuca saacadda',
    explanation:
        'Half past waa 30 daqiiqo oo saacadda dhaafay. Quarter past waa 15 daqiiqo dhaafay. Quarter to waa 15 daqiiqo ka harsan saacadda xigta.',
    rule: '30 = half past; :15 = quarter past; :45 = quarter to next hour',
    structure: 'It is + half/quarter + past/to + hour',
    examples: l3e,
    mistakes: [
      '9:45 waa quarter to ten, ma aha quarter to nine.',
      'Quarter waxaa loola jeedaa 15 daqiiqo.',
    ],
  );
  add(
    number: 3,
    titleEnglish: 'Half Past and Quarter',
    titleSomali: 'Nuska iyo Rubuca Saacadda',
    description:
        'Bar half past, quarter past iyo quarter to iyo digital equivalents.',
    objectives: [
      'Half past aqoonso.',
      'Quarter past iyo quarter to kala saar.',
      'Digital time la barbar dhig.',
    ],
    type: 'grammar',
    minutes: 27,
    vocabulary: l3v,
    grammarTopic: l3g,
    lessonExamples: l3e,
    lessonDialogues: twoDialogues(
      titleOne: 'Waqtiga casharka',
      questionOne: 'What time is the class?',
      questionOneSomali: 'Saacad imisa ayuu fasalku yahay?',
      answerOne: 'It is at half past seven.',
      answerOneSomali: 'Waa toddobada iyo badhka.',
      titleTwo: 'Ballanta',
      questionTwo: 'Is the appointment at 9:45?',
      questionTwoSomali: 'Ballantu ma 9:45 baa?',
      answerTwo: 'Yes, at quarter to ten.',
      answerTwoSomali: 'Haa, rubuc ka harsan tobanka.',
    ),
    fillQuestion: '7:30 is ___ past seven.',
    fillOptions: ['quarter', 'half', 'twenty', 'five'],
    fillAnswer: 'half',
    conversionQuestion: '9:45 waa…',
    conversionOptions: [
      'quarter past nine',
      'quarter to nine',
      'quarter to ten',
      'half past nine',
    ],
    conversionAnswer: 'quarter to ten',
    grammarQuestion: '8:15 waa…',
    grammarOptions: [
      'half past eight',
      'quarter past eight',
      'quarter to eight',
      'quarter to nine',
    ],
    grammarAnswer: 'quarter past eight',
    mistakeQuestion: 'Kee ayaa sax ah 11:45?',
    mistakeOptions: [
      'quarter past eleven',
      'quarter to eleven',
      'quarter to twelve',
      'half to twelve',
    ],
    mistakeAnswer: 'quarter to twelve',
    arrangeQuestion: 'Kala hagaaji: past / half / twelve / It / is',
    arrangeAnswer: 'It is half past twelve.',
    readingQuestion:
        '“The class starts at quarter past eight.” Digital time-keedu waa…',
    readingOptions: ['7:45', '8:15', '8:30', '8:45'],
    readingAnswer: '8:15',
    dialogueQuestion: 'Ballantu waa 9:45; eray ahaan waa…',
    dialogueOptions: [
      'quarter past nine',
      'quarter to ten',
      'half past nine',
      'ten to ten',
    ],
    dialogueAnswer: 'quarter to ten',
    speaking: 'Akhri 7:30, 8:15, 9:45, 12:30 iyo 11:45.',
    writing:
        'Qor laba half past, laba quarter past iyo laba quarter to tusaale.',
    summary:
        'Half past = :30; quarter past = :15; quarter to = :45 oo saacadda xigta la sheegayo.',
  );

  final l4e = examples([
    ('I study in the morning.', 'Waxaan wax bartaa subaxdii.'),
    ('We eat lunch at noon.', 'Waxaan qadeynaa duhurkii.'),
    ('She works in the afternoon.', 'Waxay shaqaysaa galabtii.'),
    ('They visit us in the evening.', 'Waxay na soo booqdaan fiidkii.'),
    ('He sleeps at night.', 'Wuxuu seexdaa habeenkii.'),
    ('The shop closes at midnight.', 'Dukaanku wuxuu xirmaa saqda dhexe.'),
  ]);
  final l4v = vocab([
    (
      word: 'Morning',
      meaning: 'Subax',
      pronunciation: 'moor-ning',
      en: 'I study in the morning.',
      so: 'Subaxdii wax ayaan bartaa.',
    ),
    (
      word: 'Noon',
      meaning: 'Duhur',
      pronunciation: 'nuun',
      en: 'We eat at noon.',
      so: 'Duhurkii ayaan wax cunnaa.',
    ),
    (
      word: 'Afternoon',
      meaning: 'Galab',
      pronunciation: 'aaf-tar-nuun',
      en: 'She works in the afternoon.',
      so: 'Galabtii ayay shaqaysaa.',
    ),
    (
      word: 'Evening',
      meaning: 'Fiid',
      pronunciation: 'iiv-ning',
      en: 'They visit in the evening.',
      so: 'Fiidkii ayay soo booqdaan.',
    ),
    (
      word: 'Night',
      meaning: 'Habeen',
      pronunciation: 'naayt',
      en: 'He sleeps at night.',
      so: 'Habeenkii ayuu seexdaa.',
    ),
    (
      word: 'Midnight',
      meaning: 'Saqda dhexe',
      pronunciation: 'mid-naayt',
      en: 'It opens at midnight.',
      so: 'Wuxuu furmaa saqda dhexe.',
    ),
    (
      word: 'Early',
      meaning: 'Goor hore',
      pronunciation: 'er-li',
      en: 'I wake up early.',
      so: 'Goor hore ayaan kacaa.',
    ),
    (
      word: 'Late',
      meaning: 'Goor dambe',
      pronunciation: 'leyt',
      en: 'He works late.',
      so: 'Goor dambe ayuu shaqeeyaa.',
    ),
    (
      word: 'In the morning',
      meaning: 'Subaxdii',
      pronunciation: 'in dha moor-ning',
      en: 'I pray in the morning.',
      so: 'Subaxdii waan tukadaa.',
    ),
    (
      word: 'At noon',
      meaning: 'Duhurkii',
      pronunciation: 'at nuun',
      en: 'We meet at noon.',
      so: 'Duhurkii ayaan kulannaa.',
    ),
    (
      word: 'In the afternoon',
      meaning: 'Galabtii',
      pronunciation: 'in dhi aaf-tar-nuun',
      en: 'I rest in the afternoon.',
      so: 'Galabtii waan nastaa.',
    ),
    (
      word: 'In the evening',
      meaning: 'Fiidkii',
      pronunciation: 'in dhi iiv-ning',
      en: 'She reads in the evening.',
      so: 'Fiidkii way akhridaa.',
    ),
    (
      word: 'At night',
      meaning: 'Habeenkii',
      pronunciation: 'at naayt',
      en: 'They study at night.',
      so: 'Habeenkii wax bay bartaan.',
    ),
    (
      word: 'At midnight',
      meaning: 'Saqda dhexe',
      pronunciation: 'at mid-naayt',
      en: 'The day changes at midnight.',
      so: 'Maalintu waxay is beddeshaa saqda dhexe.',
    ),
  ], type: 'part of day');
  add(
    number: 4,
    titleEnglish: 'Parts of the Day',
    titleSomali: 'Qaybaha maalinta',
    description:
        'Bar morning, noon, afternoon, evening, night iyo prepositions-kooda.',
    objectives: [
      'Qaybaha maalinta magacow.',
      'Evening iyo night kala saar.',
      'In iyo at sax u isticmaal.',
    ],
    type: 'vocabulary',
    minutes: 25,
    vocabulary: l4v,
    grammarTopic: grammar(
      titleEnglish: 'Prepositions with parts of the day',
      titleSomali: 'In iyo at ee qaybaha maalinta',
      explanation:
          'Morning, afternoon iyo evening waxaa lala isticmaalaa in. Noon, night iyo midnight waxaa lala isticmaalaa at. Evening waa fiidka; night waa habeenka dambe iyo waqtiga hurdada.',
      rule: 'in the morning/afternoon/evening; at noon/night/midnight',
      structure: 'Activity + in/at + part of day',
      examples: l4e,
      mistakes: [
        'At night ayaa caado guud lagu yiraahdaa, ma aha in the night.',
        'Evening iyo night isku mid ma aha.',
      ],
    ),
    lessonExamples: l4e,
    lessonDialogues: twoDialogues(
      titleOne: 'Jadwalka fiidka',
      questionOne: 'What do you do in the evening?',
      questionOneSomali: 'Maxaad samaysaa fiidkii?',
      answerOne: 'I study English.',
      answerOneSomali: 'English ayaan bartaa.',
      titleTwo: 'Shaqada habeenkii',
      questionTwo: 'Do you work at night?',
      questionTwoSomali: 'Ma shaqaysaa habeenkii?',
      answerTwo: 'No, I work in the afternoon.',
      answerTwoSomali: 'Maya, galabtii ayaan shaqeeyaa.',
    ),
    fillQuestion: 'We eat lunch ___ noon.',
    fillOptions: ['in', 'on', 'at', 'to'],
    fillAnswer: 'at',
    conversionQuestion: '“Fiidkii” waa…',
    conversionOptions: [
      'in the morning',
      'at noon',
      'in the evening',
      'at midnight',
    ],
    conversionAnswer: 'in the evening',
    grammarQuestion: 'Kee ayaa sax ah?',
    grammarOptions: ['in night', 'at night', 'on night', 'to night'],
    grammarAnswer: 'at night',
    mistakeQuestion: 'Sax “I study at the morning.”',
    mistakeOptions: [
      'I study in the morning.',
      'I study on morning.',
      'I study at morning.',
      'I study to morning.',
    ],
    mistakeAnswer: 'I study in the morning.',
    arrangeQuestion: 'Kala hagaaji: evening / visit / They / the / in / us',
    arrangeAnswer: 'They visit us in the evening.',
    readingQuestion:
        '“Amina works in the afternoon and reads at night.” Goormay shaqaysaa?',
    readingOptions: ['Subaxdii', 'Duhurkii', 'Galabtii', 'Habeenkii'],
    readingAnswer: 'Galabtii',
    dialogueQuestion: 'Qofku maxuu sameeyaa fiidkii?',
    dialogueOptions: [
      'Wuu shaqeeyaa',
      'English ayuu bartaa',
      'Wuu seexdaa',
      'Dukaan ayuu furaa',
    ],
    dialogueAnswer: 'English ayuu bartaa',
    speaking: 'Sharax hawl morning, noon, afternoon, evening iyo night ah.',
    writing:
        'Qor siddeed jumladood oo qaybaha maalinta leh; in/at sax u isticmaal.',
    summary:
        'In the morning/afternoon/evening; at noon/night/midnight. Evening waa fiid, night-na waa habeen.',
  );

  final days = <Seed>[
    (
      word: 'Monday',
      meaning: 'Isniin',
      pronunciation: 'man-dey',
      en: 'I work on Monday.',
      so: 'Waxaan shaqeeyaa Isniinta.',
    ),
    (
      word: 'Tuesday',
      meaning: 'Talaado',
      pronunciation: 'tyuuz-dey',
      en: 'We study on Tuesday.',
      so: 'Waxaan wax barannaa Talaadada.',
    ),
    (
      word: 'Wednesday',
      meaning: 'Arbaco',
      pronunciation: 'wenz-dey',
      en: 'The meeting is on Wednesday.',
      so: 'Kulanku waa Arbacada.',
    ),
    (
      word: 'Thursday',
      meaning: 'Khamiis',
      pronunciation: 'therz-dey',
      en: 'The course ends on Thursday.',
      so: 'Koorsadu waxay dhammaataa Khamiista.',
    ),
    (
      word: 'Friday',
      meaning: 'Jimce',
      pronunciation: 'fraay-dey',
      en: 'The office is closed on Friday.',
      so: 'Xafiisku waa xiran yahay Jimcaha.',
    ),
    (
      word: 'Saturday',
      meaning: 'Sabti',
      pronunciation: 'sa-tar-dey',
      en: 'I visit family on Saturday.',
      so: 'Waxaan qoyska booqdaa Sabtida.',
    ),
    (
      word: 'Sunday',
      meaning: 'Axad',
      pronunciation: 'san-dey',
      en: 'Today is Sunday.',
      so: 'Maanta waa Axad.',
    ),
    (
      word: 'Today',
      meaning: 'Maanta',
      pronunciation: 'tu-dey',
      en: 'Today is Monday.',
      so: 'Maanta waa Isniin.',
    ),
    (
      word: 'Tomorrow',
      meaning: 'Berri',
      pronunciation: 'ta-mo-roo',
      en: 'Tomorrow is Tuesday.',
      so: 'Berri waa Talaado.',
    ),
    (
      word: 'Yesterday',
      meaning: 'Shalay',
      pronunciation: 'yes-tar-dey',
      en: 'Yesterday was Sunday.',
      so: 'Shalay waxay ahayd Axad.',
    ),
  ];
  final l5e = examples([
    ('Today is Monday.', 'Maanta waa Isniin.'),
    ('Tomorrow is Tuesday.', 'Berri waa Talaado.'),
    ('Yesterday was Sunday.', 'Shalay waxay ahayd Axad.'),
    ('I work on Monday.', 'Waxaan shaqeeyaa Isniinta.'),
    (
      'We study from Monday to Thursday.',
      'Waxaan wax barannaa Isniin ilaa Khamiis.',
    ),
    ('The office is closed on Friday.', 'Xafiisku waa xiran yahay Jimcaha.'),
  ]);
  add(
    number: 5,
    titleEnglish: 'Days of the Week',
    titleSomali: 'Maalmaha toddobaadka',
    description: 'Bar toddobada maalmood, capital letters iyo on + day.',
    objectives: [
      'Maalmaha sida ay isugu xigaan u sheeg.',
      'Capital letter ku bilow.',
      'On + day isticmaal.',
    ],
    type: 'vocabulary',
    minutes: 27,
    vocabulary: vocab(days, type: 'day or relative day'),
    grammarTopic: grammar(
      titleEnglish: 'Days and capital letters',
      titleSomali: 'Maalmaha iyo xarafka weyn',
      explanation:
          'Magacyada maalmaha English-ka mar walba capital letter ayay ku bilaabmaan. Maalin waxaa lala isticmaalaa on. From…to wuxuu muujinayaa bilow iyo dhammaad.',
      rule: 'on + Day; from + Day + to + Day',
      structure: 'Activity + on/from/to + Day',
      examples: l5e,
      mistakes: [
        'monday waa khalad; Monday ayaa sax ah.',
        'In Monday waa khalad; on Monday ayaa sax ah.',
      ],
    ),
    lessonExamples: l5e,
    lessonDialogues: twoDialogues(
      titleOne: 'Jadwalka iskuulka',
      questionOne: 'What days do you study?',
      questionOneSomali: 'Maalmahee ayaad wax barataa?',
      answerOne: 'From Monday to Thursday.',
      answerOneSomali: 'Isniin ilaa Khamiis.',
      titleTwo: 'Xafiiska Jimcaha',
      questionTwo: 'Is the office open on Friday?',
      questionTwoSomali: 'Xafiisku ma furan yahay Jimcaha?',
      answerTwo: 'No, it is closed.',
      answerTwoSomali: 'Maya, waa xiran yahay.',
    ),
    fillQuestion: 'I work ___ Monday.',
    fillOptions: ['at', 'on', 'in', 'from'],
    fillAnswer: 'on',
    conversionQuestion: 'Maalinta ka dambaysa Wednesday waa…',
    conversionOptions: ['Tuesday', 'Thursday', 'Friday', 'Sunday'],
    conversionAnswer: 'Thursday',
    grammarQuestion: 'Kee ayaa sax loo qoray?',
    grammarOptions: ['monday', 'Monday', 'MONday', 'monDay'],
    grammarAnswer: 'Monday',
    mistakeQuestion: 'Sax “We study in Tuesday.”',
    mistakeOptions: [
      'We study on Tuesday.',
      'We study at Tuesday.',
      'We study to Tuesday.',
      'We study Tuesday in.',
    ],
    mistakeAnswer: 'We study on Tuesday.',
    arrangeQuestion: 'Kala hagaaji: Friday / closed / on / is / office / The',
    arrangeAnswer: 'The office is closed on Friday.',
    readingQuestion:
        '“We study from Monday to Thursday.” Ma wax bay bartaan Friday?',
    readingOptions: ['Haa', 'Maya', 'Keliya subaxdii', 'Lama sheegin'],
    readingAnswer: 'Maya',
    dialogueQuestion: 'Xafiisku Friday ma furan yahay?',
    dialogueOptions: [
      'Haa',
      'Maya, waa xiran yahay',
      'Duhurkii oo keliya',
      'Habeenkii oo keliya',
    ],
    dialogueAnswer: 'Maya, waa xiran yahay',
    speaking:
        'Magacow toddobada maalmood sida ay isugu xigaan; hawl kasta maalin la xiriiri.',
    writing:
        'Qor maalmaha toddobaadka, kadib toddoba jumladood oo on + day leh.',
    summary:
        'Days-ku capital letter ayay ku bilaabmaan; on Monday, from Monday to Thursday.',
  );

  final l6v = vocab([
    (
      word: 'Today',
      meaning: 'Maanta',
      pronunciation: 'tu-dey',
      en: 'Today is Sunday.',
      so: 'Maanta waa Axad.',
    ),
    (
      word: 'Tomorrow',
      meaning: 'Berri',
      pronunciation: 'ta-mo-roo',
      en: 'Tomorrow is Monday.',
      so: 'Berri waa Isniin.',
    ),
    (
      word: 'Yesterday',
      meaning: 'Shalay',
      pronunciation: 'yes-tar-dey',
      en: 'Yesterday was Saturday.',
      so: 'Shalay waxay ahayd Sabti.',
    ),
    (
      word: 'The day before yesterday',
      meaning: 'Doraad',
      pronunciation: 'dha dey bi-foor yes-tar-dey',
      en: 'The visit was the day before yesterday.',
      so: 'Booqashadu waxay ahayd doraad.',
    ),
    (
      word: 'The day after tomorrow',
      meaning: 'Saadambe',
      pronunciation: 'dha dey aaf-tar ta-mo-roo',
      en: 'The class is the day after tomorrow.',
      so: 'Casharku waa saadambe.',
    ),
    (
      word: 'This morning',
      meaning: 'Saaka',
      pronunciation: 'dhis moor-ning',
      en: 'I have class this morning.',
      so: 'Saaka waxaan leeyahay cashar.',
    ),
    (
      word: 'This afternoon',
      meaning: 'Galabta',
      pronunciation: 'dhis aaf-tar-nuun',
      en: 'We meet this afternoon.',
      so: 'Galabta ayaan kulannaa.',
    ),
    (
      word: 'This evening',
      meaning: 'Fiidkan',
      pronunciation: 'dhis iiv-ning',
      en: 'I have a lesson this evening.',
      so: 'Fiidkan waxaan leeyahay cashar.',
    ),
    (
      word: 'Tonight',
      meaning: 'Caawa',
      pronunciation: 'tu-naayt',
      en: 'I study tonight.',
      so: 'Caawa wax ayaan bartaa.',
    ),
  ], type: 'relative time expression');
  final l6e = examples([
    ('Today is Sunday.', 'Maanta waa Axad.'),
    ('Tomorrow is Monday.', 'Berri waa Isniin.'),
    ('Yesterday was Saturday.', 'Shalay waxay ahayd Sabti.'),
    ('I have a lesson this evening.', 'Fiidkan waxaan leeyahay cashar.'),
    ('We meet tomorrow.', 'Berri ayaan kulannaa.'),
    ('The exam is the day after tomorrow.', 'Imtixaanku waa saadambe.'),
  ]);
  add(
    number: 6,
    titleEnglish: 'Today, Tomorrow and Yesterday',
    titleSomali: 'Maanta, berri iyo shalay',
    description:
        'Bar relative-day expressions adigoon gelin past/future grammar qoto dheer.',
    objectives: [
      'Today/tomorrow/yesterday kala saar.',
      'This morning/evening iyo tonight isticmaal.',
      'Doraad iyo saadambe faham.',
    ],
    type: 'vocabulary',
    minutes: 24,
    vocabulary: l6v,
    grammarTopic: grammar(
      titleEnglish: 'Relative days',
      titleSomali: 'Maalmaha la xiriira maanta',
      explanation:
          'Today waa maanta, tomorrow waa berri, yesterday waa shalay. Was iyo will waxaa halkan loogu isticmaalayaa qaabab diyaar ah oo fudud; tense-kooda qoto dheer hadda lama baranayo.',
      rule: 'Today is…; Yesterday was…; We meet tomorrow.',
      structure: 'Relative time + simple sentence',
      examples: l6e,
      mistakes: [
        'Tonight waa caawa; this evening waa fiidkan.',
        'Future/past grammar qoto dheer looma baahna casharkan.',
      ],
    ),
    lessonExamples: l6e,
    lessonDialogues: twoDialogues(
      titleOne: 'Casharka berri',
      questionOne: 'Do we have class tomorrow?',
      questionOneSomali: 'Berri cashar ma leenahay?',
      answerOne: 'Yes, at ten.',
      answerOneSomali: 'Haa, tobanka.',
      titleTwo: 'Qorshaha fiidka',
      questionTwo: 'Are you free this evening?',
      questionTwoSomali: 'Fiidkan ma bannaan tahay?',
      answerTwo: 'No, I have a lesson.',
      answerTwoSomali: 'Maya, cashar ayaan leeyahay.',
    ),
    fillQuestion: '___ is Monday. (berri)',
    fillOptions: ['Today', 'Tomorrow', 'Yesterday', 'Tonight'],
    fillAnswer: 'Tomorrow',
    conversionQuestion: '“Saadambe” waa…',
    conversionOptions: [
      'the day before yesterday',
      'the day after tomorrow',
      'this evening',
      'tonight',
    ],
    conversionAnswer: 'the day after tomorrow',
    grammarQuestion: 'Kee ayaa “shalay” ah?',
    grammarOptions: ['today', 'tomorrow', 'yesterday', 'tonight'],
    grammarAnswer: 'yesterday',
    mistakeQuestion: 'Kee ayaa sax ah?',
    mistakeOptions: [
      'Today was Sunday.',
      'Today is Sunday.',
      'Tomorrow was Monday.',
      'Yesterday is Saturday.',
    ],
    mistakeAnswer: 'Today is Sunday.',
    arrangeQuestion: 'Kala hagaaji: lesson / evening / have / this / I / a',
    arrangeAnswer: 'I have a lesson this evening.',
    readingQuestion:
        '“Today is Sunday. Tomorrow is Monday.” Maanta waa maalintee?',
    readingOptions: ['Saturday', 'Sunday', 'Monday', 'Tuesday'],
    readingAnswer: 'Sunday',
    dialogueQuestion: 'Ballanta berri saacad imisa ayay tahay?',
    dialogueOptions: ['Siddeedda', 'Sagaalka', 'Tobanka', 'Kowda'],
    dialogueAnswer: 'Tobanka',
    speaking:
        'Samee jumlado today, tomorrow, yesterday, this evening iyo tonight leh.',
    writing:
        'Qor sagaal jumladood, mid kasta relative-time expression kala duwan ha yeesho.',
    summary:
        'Today=maanta, tomorrow=berri, yesterday=shalay, day before yesterday=doraad, day after tomorrow=saadambe.',
  );

  final months = <Seed>[
    (
      word: 'January',
      meaning: 'Jannaayo',
      pronunciation: 'jan-yu-we-ri',
      en: 'January is the first month.',
      so: 'Jannaayo waa bisha koowaad.',
    ),
    (
      word: 'February',
      meaning: 'Febraayo',
      pronunciation: 'feb-ru-we-ri',
      en: 'February is the second month.',
      so: 'Febraayo waa bisha labaad.',
    ),
    (
      word: 'March',
      meaning: 'Maarso',
      pronunciation: 'maarch',
      en: 'The course begins in March.',
      so: 'Koorsadu waxay bilaabataa Maarso.',
    ),
    (
      word: 'April',
      meaning: 'Abriil',
      pronunciation: 'ey-pral',
      en: 'School is open in April.',
      so: 'Iskuulku wuu furan yahay Abriil.',
    ),
    (
      word: 'May',
      meaning: 'Maajo',
      pronunciation: 'mey',
      en: 'The meeting is in May.',
      so: 'Kulanku waa Maajo.',
    ),
    (
      word: 'June',
      meaning: 'Juun',
      pronunciation: 'juun',
      en: 'The school closes in June.',
      so: 'Iskuulku wuxuu xirmaa Juun.',
    ),
    (
      word: 'July',
      meaning: 'Luulyo',
      pronunciation: 'ju-laay',
      en: 'The exam is in July.',
      so: 'Imtixaanku waa Luulyo.',
    ),
    (
      word: 'August',
      meaning: 'Agoosto',
      pronunciation: 'oo-gast',
      en: 'The shop opens in August.',
      so: 'Dukaanku wuxuu furmaa Agoosto.',
    ),
    (
      word: 'September',
      meaning: 'Sebteembar',
      pronunciation: 'sep-tem-bar',
      en: 'My course starts in September.',
      so: 'Koorsadaydu waxay bilaabataa Sebteembar.',
    ),
    (
      word: 'October',
      meaning: 'Oktoobar',
      pronunciation: 'ok-too-bar',
      en: 'October is the tenth month.',
      so: 'Oktoobar waa bisha tobnaad.',
    ),
    (
      word: 'November',
      meaning: 'Nofeembar',
      pronunciation: 'noo-vem-bar',
      en: 'My birthday is in November.',
      so: 'Maalinta dhalashadaydu waa Nofeembar.',
    ),
    (
      word: 'December',
      meaning: 'Diseembar',
      pronunciation: 'di-sem-bar',
      en: 'December is the last month.',
      so: 'Diseembar waa bisha ugu dambaysa.',
    ),
  ];
  final l7e = examples([
    ('January is the first month.', 'Jannaayo waa bisha koowaad.'),
    (
      'My course starts in September.',
      'Koorsadaydu waxay bilaabataa Sebteembar.',
    ),
    (
      'Ramadan may occur in different Gregorian months.',
      'Ramadaan wuxuu ku beegmi karaa bilo Gregorian oo kala duwan.',
    ),
    ('The school closes in June.', 'Iskuulku wuxuu xirmaa Juun.'),
    ('My birthday is in November.', 'Maalinta dhalashadaydu waa Nofeembar.'),
    ('December is the twelfth month.', 'Diseembar waa bisha laba iyo tobnaad.'),
  ]);
  add(
    number: 7,
    titleEnglish: 'Months of the Year',
    titleSomali: 'Bilaha sannadka',
    description: 'Bar 12-ka bilood ee Gregorian-ka iyo in + month.',
    objectives: [
      'Bilaha sida ay isugu xigaan u sheeg.',
      'Pronunciation-ka bilaha adag ku celceli.',
      'Gregorian iyo Islamic months kala faham.',
    ],
    type: 'vocabulary',
    minutes: 30,
    vocabulary: vocab(months, type: 'Gregorian month'),
    grammarTopic: grammar(
      titleEnglish: 'Months and capital letters',
      titleSomali: 'Bilaha iyo xarafka weyn',
      explanation:
          'Bilaha Gregorian-ka English-ka capital letter ayay ku bilaabmaan, waxaana lala isticmaalaa in. Bilaha Gregorian iyo bilaha Hijriga waa laba nidaam oo kala duwan.',
      rule: 'in + Month; Month starts with a capital letter',
      structure: 'Event + in + Month',
      examples: l7e,
      mistakes: [
        'september waa khalad; September ayaa sax ah.',
        'At July waa khalad; in July ayaa sax ah.',
        'Gregorian months ha lagu khaldin Islamic months.',
      ],
    ),
    lessonExamples: l7e,
    lessonDialogues: twoDialogues(
      titleOne: 'Bilowga koorsada',
      questionOne: 'When does the course start?',
      questionOneSomali: 'Goorma ayay koorsadu bilaabataa?',
      answerOne: 'It starts in September.',
      answerOneSomali: 'Waxay bilaabataa Sebteembar.',
      titleTwo: 'Xiritaanka iskuulka',
      questionTwo: 'When does the school close?',
      questionTwoSomali: 'Goorma ayuu iskuulku xirmaa?',
      answerTwo: 'It closes in June.',
      answerTwoSomali: 'Wuxuu xirmaa Juun.',
    ),
    fillQuestion: 'The course starts ___ September.',
    fillOptions: ['at', 'on', 'in', 'to'],
    fillAnswer: 'in',
    conversionQuestion: 'Bisha ka dambaysa August waa…',
    conversionOptions: ['July', 'September', 'October', 'November'],
    conversionAnswer: 'September',
    grammarQuestion: 'Kee ayaa sax loo qoray?',
    grammarOptions: ['february', 'February', 'FEBruary', 'febRuary'],
    grammarAnswer: 'February',
    mistakeQuestion: 'Sax “The exam is at July.”',
    mistakeOptions: [
      'The exam is in July.',
      'The exam is on July.',
      'The exam is to July.',
      'The exam is July at.',
    ],
    mistakeAnswer: 'The exam is in July.',
    arrangeQuestion: 'Kala hagaaji: November / birthday / in / is / My',
    arrangeAnswer: 'My birthday is in November.',
    readingQuestion:
        '“The school closes in June and opens in August.” Goormuu furmaa?',
    readingOptions: ['June', 'July', 'August', 'September'],
    readingAnswer: 'August',
    dialogueQuestion: 'Koorsadu goormay bilaabataa?',
    dialogueOptions: ['June', 'August', 'September', 'December'],
    dialogueAnswer: 'September',
    speaking:
        'Magacow 12-ka bilood sida ay isugu xigaan; February, August iyo September si cad u sheeg.',
    writing: 'Qor bilaha sannadka, kadib lix event + in + month jumladood.',
    summary:
        'Waxaad baratay bilaha Gregorian-ka. Bilaha capital letter ayay ku bilaabmaan, waxaana lala isticmaalaa in.',
  );

  final ordinals = <Seed>[
    (
      word: 'First',
      meaning: 'Koowaad (1st)',
      pronunciation: 'ferst',
      en: 'The course starts on the first.',
      so: 'Koorsadu waxay bilaabataa maalinta koowaad.',
    ),
    (
      word: 'Second',
      meaning: 'Labaad (2nd)',
      pronunciation: 'se-kand',
      en: 'Today is the second.',
      so: 'Maanta waa maalinta labaad.',
    ),
    (
      word: 'Third',
      meaning: 'Saddexaad (3rd)',
      pronunciation: 'therd',
      en: 'The meeting is on the third.',
      so: 'Kulanku waa maalinta saddexaad.',
    ),
    (
      word: 'Fourth',
      meaning: 'Afraad (4th)',
      pronunciation: 'foorth',
      en: 'The class is on the fourth.',
      so: 'Casharku waa maalinta afraad.',
    ),
    (
      word: 'Fifth',
      meaning: 'Shanaad (5th)',
      pronunciation: 'fifth',
      en: 'Today is the fifth of July.',
      so: 'Maanta waa shanta Luulyo.',
    ),
    (
      word: 'Sixth',
      meaning: 'Lixaad (6th)',
      pronunciation: 'siksth',
      en: 'The visit is on the sixth.',
      so: 'Booqashadu waa maalinta lixaad.',
    ),
    (
      word: 'Seventh',
      meaning: 'Toddobaad (7th)',
      pronunciation: 'se-vanth',
      en: 'The exam is on the seventh.',
      so: 'Imtixaanku waa maalinta toddobaad.',
    ),
    (
      word: 'Eighth',
      meaning: 'Siddeedaad (8th)',
      pronunciation: 'eytth',
      en: 'The shop opens on the eighth.',
      so: 'Dukaanku wuxuu furmaa maalinta siddeedaad.',
    ),
    (
      word: 'Ninth',
      meaning: 'Sagaalaad (9th)',
      pronunciation: 'naaynth',
      en: 'The lesson is on the ninth.',
      so: 'Casharku waa maalinta sagaalaad.',
    ),
    (
      word: 'Tenth',
      meaning: 'Tobnaad (10th)',
      pronunciation: 'tenth',
      en: 'The meeting is on the tenth.',
      so: 'Kulanku waa maalinta tobnaad.',
    ),
    (
      word: 'Eleventh',
      meaning: 'Kow iyo tobnaad (11th)',
      pronunciation: 'i-le-vanth',
      en: 'The exam is on the eleventh.',
      so: 'Imtixaanku waa kow iyo tobanka.',
    ),
    (
      word: 'Twelfth',
      meaning: 'Laba iyo tobnaad (12th)',
      pronunciation: 'twelfth',
      en: 'The exam is on 12 June.',
      so: 'Imtixaanku waa 12 Juun.',
    ),
    (
      word: 'Thirteenth',
      meaning: 'Saddex iyo tobnaad (13th)',
      pronunciation: 'ther-tiinth',
      en: 'The class is on the thirteenth.',
      so: 'Casharku waa 13-ka.',
    ),
    (
      word: 'Twentieth',
      meaning: 'Labaatanaad (20th)',
      pronunciation: 'twen-ti-ath',
      en: 'The meeting is on the twentieth.',
      so: 'Kulanku waa 20-ka.',
    ),
    (
      word: 'Twenty-first',
      meaning: 'Kow iyo labaatanaad (21st)',
      pronunciation: 'twen-ti-ferst',
      en: 'The course starts on 21 September.',
      so: 'Koorsadu waxay bilaabataa 21 Sebteembar.',
    ),
    (
      word: 'Thirtieth',
      meaning: 'Soddonaad (30th)',
      pronunciation: 'ther-ti-ath',
      en: 'The office closes on the thirtieth.',
      so: 'Xafiisku wuxuu xirmaa 30-ka.',
    ),
    (
      word: 'Thirty-first',
      meaning: 'Kow iyo soddonaad (31st)',
      pronunciation: 'ther-ti-ferst',
      en: 'The date is 31 December.',
      so: 'Taariikhdu waa 31 Diseembar.',
    ),
  ];
  final l8e = examples([
    ('Today is the fifth of July.', 'Maanta waa shanta Luulyo.'),
    ('The exam is on 12 June.', 'Imtixaanku waa 12 Juun.'),
    (
      'The course starts on the first of September.',
      'Koorsadu waxay bilaabataa koowda Sebteembar.',
    ),
    ('The date is 5 July 2026.', 'Taariikhdu waa 5 Luulyo 2026.'),
    (
      'The American form is July 5, 2026.',
      'Qaabka Maraykanku waa July 5, 2026.',
    ),
    ('The meeting is on 21 September.', 'Kulanku waa 21 Sebteembar.'),
  ]);
  add(
    number: 8,
    titleEnglish: 'Dates and Ordinal Numbers',
    titleSomali: 'Taariikhaha iyo tirooyinka kala horreynta',
    description:
        'Bar ordinal numbers, dates iyo British/American date formats.',
    objectives: [
      'Ordinal numbers akhri.',
      'Taariikh weydii oo sheeg.',
      'Labada date format faham.',
    ],
    type: 'grammar',
    minutes: 34,
    vocabulary: vocab(ordinals, type: 'ordinal number'),
    grammarTopic: grammar(
      titleEnglish: 'Dates and ordinal numbers',
      titleSomali: 'Taariikhaha iyo ordinal numbers',
      explanation:
          'Ordinal numbers waxay muujiyaan kala horreynta: first, second, third. Taariikhda British-ka waa day month year; American-ku waa month day, year. Labaduba waa sax.',
      rule: 'British: 5 July 2026; American: July 5, 2026; on + date',
      structure: 'Event + on + date',
      examples: l8e,
      questions: examples([
        ("What's today's date?", 'Waa maxay taariikhda maanta?'),
        ('When is your exam?', 'Goorma ayuu imtixaankaagu yahay?'),
        ('When does the course start?', 'Goorma ayay koorsadu bilaabataa?'),
      ]),
      mistakes: [
        '1st waa first, 2nd second, 3rd third.',
        'Taariikh gaar ah waxaa lala isticmaalaa on.',
      ],
    ),
    lessonExamples: l8e,
    lessonDialogues: twoDialogues(
      titleOne: 'Taariikhda imtixaanka',
      questionOne: 'When is the exam?',
      questionOneSomali: 'Goorma ayuu imtixaanku yahay?',
      answerOne: 'It is on 12 June.',
      answerOneSomali: 'Waa 12 Juun.',
      titleTwo: 'Bilowga koorsada',
      questionTwo: 'When does the course start?',
      questionTwoSomali: 'Goorma ayay koorsadu bilaabataa?',
      answerTwo: 'On the first of September.',
      answerTwoSomali: 'Koowda Sebteembar.',
    ),
    fillQuestion: 'The exam is ___ 12 June.',
    fillOptions: ['at', 'on', 'in', 'to'],
    fillAnswer: 'on',
    conversionQuestion: '21st waa…',
    conversionOptions: [
      'twenty-one',
      'twentieth',
      'twenty-first',
      'twenty-oneth',
    ],
    conversionAnswer: 'twenty-first',
    grammarQuestion: 'Qaabka British-ka saxda ahi waa…',
    grammarOptions: [
      'July 5, 2026',
      '5 July 2026',
      '2026 July the five',
      'July 2026 5th is',
    ],
    grammarAnswer: '5 July 2026',
    mistakeQuestion: 'Kee ayaa sax ah?',
    mistakeOptions: [
      'The exam is in 12 June.',
      'The exam is on 12 June.',
      'The exam is at 12 June.',
      'The exam is to 12 June.',
    ],
    mistakeAnswer: 'The exam is on 12 June.',
    arrangeQuestion: 'Kala hagaaji: fifth / Today / July / the / is / of',
    arrangeAnswer: 'Today is the fifth of July.',
    readingQuestion:
        '“The course starts on 1 September; the exam is on 21 September.” Imtixaanku goormuu yahay?',
    readingOptions: [
      '1 September',
      '5 September',
      '12 September',
      '21 September',
    ],
    readingAnswer: '21 September',
    dialogueQuestion: 'Imtixaanku goormuu yahay?',
    dialogueOptions: ['1 June', '5 June', '12 June', '21 June'],
    dialogueAnswer: '12 June',
    speaking:
        'Sheeg 1st, 2nd, 3rd, 5th, 12th, 21st iyo 31st; kadib taariikh tusaale ah sheeg.',
    writing: 'Qor shan taariikhood British iyo American format labadaba.',
    summary:
        'Ordinal numbers waxay muujiyaan kala horreynta; on + date. British iyo American formats labaduba waa sax.',
  );

  final l9e = examples([
    ('I wake up at six o’clock.', 'Waxaan kacaa lixda.'),
    ('We eat lunch at noon.', 'Waxaan qadeynaa duhurkii.'),
    ('The meeting is on Monday.', 'Kulanku waa Isniinta.'),
    ('The exam is on 5 July.', 'Imtixaanku waa 5 Luulyo.'),
    ('The course starts in January.', 'Koorsadu waxay bilaabataa Jannaayo.'),
    ('She works in the morning.', 'Waxay shaqaysaa subaxdii.'),
    ('The shop closes at midnight.', 'Dukaanku wuxuu xirmaa saqda dhexe.'),
    ('We study on Friday morning.', 'Waxaan wax barannaa subaxda Jimcaha.'),
    ('The office opens in 2026.', 'Xafiisku wuxuu furmaa 2026.'),
    ('He reads in the evening.', 'Wuxuu akhriyaa fiidkii.'),
    ('I sleep at night.', 'Habeenkii waan seexdaa.'),
    ('The visit is on my birthday.', 'Booqashadu waa maalinta dhalashadayda.'),
    ('Class starts at eight fifteen.', 'Fasalku wuxuu bilaabmaa 8:15.'),
    ('They travel in August.', 'Waxay safraan Agoosto.'),
    ('We meet on Wednesday.', 'Waxaan kulannaa Arbacada.'),
    ('I rest in the afternoon.', 'Galabtii waan nastaa.'),
    ('The call is at ten.', 'Wicitaanku waa tobanka.'),
    ('School closes in June.', 'Iskuulku wuxuu xirmaa Juun.'),
    ('The lesson is on 12 March.', 'Casharku waa 12 Maarso.'),
    (
      'The day changes at midnight.',
      'Maalintu waxay is beddeshaa saqda dhexe.',
    ),
  ]);
  final l9v = vocab([
    (
      word: 'At',
      meaning: 'Waqti gaar ah',
      pronunciation: 'at',
      en: 'The class starts at six.',
      so: 'Fasalku wuxuu bilaabmaa lixda.',
    ),
    (
      word: 'On',
      meaning: 'Maalin ama taariikh',
      pronunciation: 'on',
      en: 'We meet on Monday.',
      so: 'Waxaan kulannaa Isniinta.',
    ),
    (
      word: 'In',
      meaning: 'Bil, sannad ama qayb maalinta',
      pronunciation: 'in',
      en: 'The course starts in January.',
      so: 'Koorsadu waxay bilaabataa Jannaayo.',
    ),
    (
      word: "At six o'clock",
      meaning: 'Lixda saacad',
      pronunciation: 'at siks o-klook',
      en: 'I wake up at six o’clock.',
      so: 'Waxaan kacaa lixda.',
    ),
    (
      word: 'At noon',
      meaning: 'Duhurkii',
      pronunciation: 'at nuun',
      en: 'We eat at noon.',
      so: 'Duhurkii ayaan wax cunnaa.',
    ),
    (
      word: 'At night',
      meaning: 'Habeenkii',
      pronunciation: 'at naayt',
      en: 'I sleep at night.',
      so: 'Habeenkii waan seexdaa.',
    ),
    (
      word: 'On Monday',
      meaning: 'Isniinta',
      pronunciation: 'on man-dey',
      en: 'I work on Monday.',
      so: 'Waxaan shaqeeyaa Isniinta.',
    ),
    (
      word: 'On 5 July',
      meaning: '5 Luulyo',
      pronunciation: 'on dha fifth av ju-laay',
      en: 'The exam is on 5 July.',
      so: 'Imtixaanku waa 5 Luulyo.',
    ),
    (
      word: 'In January',
      meaning: 'Jannaayo gudaheeda',
      pronunciation: 'in jan-yu-we-ri',
      en: 'School opens in January.',
      so: 'Iskuulku wuxuu furmaa Jannaayo.',
    ),
    (
      word: 'In 2026',
      meaning: 'Sannadka 2026',
      pronunciation: 'in twen-ti twen-ti siks',
      en: 'The course starts in 2026.',
      so: 'Koorsadu waxay bilaabataa 2026.',
    ),
    (
      word: 'In the morning',
      meaning: 'Subaxdii',
      pronunciation: 'in dha moor-ning',
      en: 'She studies in the morning.',
      so: 'Subaxdii ayay wax barataa.',
    ),
    (
      word: 'In the evening',
      meaning: 'Fiidkii',
      pronunciation: 'in dhi iiv-ning',
      en: 'He reads in the evening.',
      so: 'Fiidkii ayuu akhriyaa.',
    ),
  ], type: 'preposition of time');
  add(
    number: 9,
    titleEnglish: 'Prepositions of Time — At, On and In',
    titleSomali: 'Erayada waqtiga ee At, On iyo In',
    description:
        'Bar at waqti gaar ah, on maalin/taariikh, iyo in bil/sannad/qayb maalinta.',
    objectives: [
      'At/on/in kala dooro.',
      '20 tusaale akhri.',
      'At night exception-ka xasuuso.',
    ],
    type: 'grammar',
    minutes: 36,
    vocabulary: l9v,
    grammarTopic: grammar(
      titleEnglish: 'At, on and in',
      titleSomali: 'At, on iyo in',
      explanation:
          'At waxaa loo adeegsadaa saacad iyo points sida noon/night. On waxaa loo adeegsadaa days iyo dates. In waxaa loo adeegsadaa months, years iyo morning/afternoon/evening.',
      rule: 'at + exact time; on + day/date; in + month/year/part of day',
      structure: 'Activity/event + at/on/in + time',
      examples: l9e,
      mistakes: [
        'In Monday ❌; on Monday ✅.',
        'At July ❌; in July ✅.',
        'On six o’clock ❌; at six o’clock ✅.',
        'Caado guud: at night.',
      ],
    ),
    lessonExamples: l9e,
    lessonDialogues: twoDialogues(
      titleOne: 'Kulanka',
      questionOne: 'When is the meeting?',
      questionOneSomali: 'Goorma ayuu kulanku yahay?',
      answerOne: 'On Monday at ten.',
      answerOneSomali: 'Isniinta tobanka.',
      titleTwo: 'Koorsada',
      questionTwo: 'When does the course start?',
      questionTwoSomali: 'Goorma ayay koorsadu bilaabataa?',
      answerTwo: 'In September.',
      answerTwoSomali: 'Sebteembar.',
    ),
    fillQuestion: 'The meeting is ___ Monday.',
    fillOptions: ['at', 'on', 'in', 'to'],
    fillAnswer: 'on',
    conversionQuestion: 'Kee ayaa bil la socda?',
    conversionOptions: ['at January', 'on January', 'in January', 'to January'],
    conversionAnswer: 'in January',
    grammarQuestion: 'I wake up ___ six o’clock.',
    grammarOptions: ['at', 'on', 'in', 'from'],
    grammarAnswer: 'at',
    mistakeQuestion: 'Sax “The exam is at July.”',
    mistakeOptions: [
      'The exam is in July.',
      'The exam is on July.',
      'The exam is at July.',
      'The exam is to July.',
    ],
    mistakeAnswer: 'The exam is in July.',
    arrangeQuestion: 'Kala hagaaji: morning / works / the / in / She',
    arrangeAnswer: 'She works in the morning.',
    readingQuestion:
        '“The meeting is on Wednesday at two in the afternoon.” Maalintee iyo saacaddee?',
    readingOptions: [
      'Monday at two',
      'Wednesday at two',
      'Wednesday at twelve',
      'Friday at two',
    ],
    readingAnswer: 'Wednesday at two',
    dialogueQuestion: 'Kulanku goormuu yahay?',
    dialogueOptions: [
      'Monday at ten',
      'Monday in ten',
      'September at ten',
      'Friday at noon',
    ],
    dialogueAnswer: 'Monday at ten',
    speaking: 'Samee shan at, shan on iyo shan in jumladood oo hadal ah.',
    writing: 'Qor 15 jumladood: shan at, shan on, shan in; at night ku dar.',
    summary:
        'At + exact time/noon/night; on + day/date; in + month/year/morning/afternoon/evening.',
  );

  final l10e = examples([
    (
      'The English lesson starts at eight.',
      'Casharka English-ku wuxuu bilaabmaa siddeedda.',
    ),
    (
      'Mathematics finishes at ten fifteen.',
      'Xisaabtu waxay dhammaataa 10:15.',
    ),
    (
      'The break is from ten fifteen to ten thirty.',
      'Nasashadu waa 10:15 ilaa 10:30.',
    ),
    (
      'The work meeting is from two to three.',
      'Kulanka shaqadu waa laba ilaa saddex.',
    ),
    (
      'The shop closes at eight p.m.',
      'Dukaanku wuxuu xirmaa siddeedda fiidnimo.',
    ),
    ('I study after lunch.', 'Waxaan wax bartaa qadada kadib.'),
  ]);
  final l10v = vocab([
    (
      word: 'Schedule',
      meaning: 'Jadwal hawleed',
      pronunciation: 'ske-jool',
      en: 'My schedule starts at eight.',
      so: 'Jadwalkaygu wuxuu bilaabmaa siddeedda.',
    ),
    (
      word: 'Timetable',
      meaning: 'Jadwal waqtiyeed',
      pronunciation: 'taaym-tey-bal',
      en: 'Read the school timetable.',
      so: 'Akhri jadwalka iskuulka.',
    ),
    (
      word: 'Start',
      meaning: 'Bilow',
      pronunciation: 'staart',
      en: 'Class starts at eight.',
      so: 'Fasalku wuxuu bilaabmaa siddeedda.',
    ),
    (
      word: 'Finish',
      meaning: 'Dhammee',
      pronunciation: 'fi-nish',
      en: 'Class finishes at nine.',
      so: 'Fasalku wuxuu dhammaadaa sagaalka.',
    ),
    (
      word: 'Open',
      meaning: 'Fur/furan',
      pronunciation: 'oo-pan',
      en: 'The office opens at seven.',
      so: 'Xafiisku wuxuu furmaa toddobada.',
    ),
    (
      word: 'Close',
      meaning: 'Xir',
      pronunciation: 'klooz',
      en: 'The shop closes at eight.',
      so: 'Dukaanku wuxuu xirmaa siddeedda.',
    ),
    (
      word: 'Break',
      meaning: 'Nasasho',
      pronunciation: 'breyk',
      en: 'The break starts at ten fifteen.',
      so: 'Nasashadu waxay bilaabataa 10:15.',
    ),
    (
      word: 'Lesson',
      meaning: 'Cashar',
      pronunciation: 'le-san',
      en: 'The lesson is one hour.',
      so: 'Casharku waa hal saac.',
    ),
    (
      word: 'Meeting',
      meaning: 'Kulan',
      pronunciation: 'mii-ting',
      en: 'The meeting is at two.',
      so: 'Kulanku waa labada.',
    ),
    (
      word: 'Appointment',
      meaning: 'Ballan',
      pronunciation: 'a-point-ment',
      en: 'I have an appointment at three.',
      so: 'Waxaan leeyahay ballan saddexda.',
    ),
    (
      word: 'From',
      meaning: 'Laga bilaabo',
      pronunciation: 'from',
      en: 'The class is from eight.',
      so: 'Fasalku wuxuu ka bilaabmaa siddeedda.',
    ),
    (
      word: 'To',
      meaning: 'Ilaa',
      pronunciation: 'tuu',
      en: 'The class is from eight to nine.',
      so: 'Fasalku waa siddeed ilaa sagaal.',
    ),
    (
      word: 'Before',
      meaning: 'Ka hor',
      pronunciation: 'bi-foor',
      en: 'I read before class.',
      so: 'Waxaan akhriyaa fasalka ka hor.',
    ),
    (
      word: 'After',
      meaning: 'Kadib',
      pronunciation: 'aaf-tar',
      en: 'I rest after lunch.',
      so: 'Waxaan nastaa qadada kadib.',
    ),
  ], type: 'schedule term');
  add(
    number: 10,
    titleEnglish: 'Schedules and Timetables',
    titleSomali: 'Jadwallada waqtiga',
    description:
        'Bar akhrinta timetable iyo start/finish/from/to/before/after.',
    objectives: [
      'Timetable akhri.',
      'Start iyo finish weydii.',
      'From/to iyo before/after isticmaal.',
    ],
    type: 'reading',
    minutes: 32,
    vocabulary: l10v,
    grammarTopic: grammar(
      titleEnglish: 'Schedules with from, to, before and after',
      titleSomali: 'Jadwalka iyo from/to/before/after',
      explanation:
          'From…to wuxuu muujinayaa waqtiga bilowga iyo dhammaadka. Before waa ka hor; after waa kadib. Present Simple waxaa loo isticmaalaa jadwalka.',
      rule: 'Event + starts/finishes + at; event + from + time + to + time',
      structure: 'What time does + event + start/finish?',
      examples: l10e,
      questions: examples([
        (
          'What time does the class start?',
          'Saacad imisa ayuu fasalku bilaabmaa?',
        ),
        ('When does the shop close?', 'Goorma ayuu dukaanku xirmaa?'),
        ('What day is the meeting?', 'Maalintee ayuu kulanku yahay?'),
        ('Is the office open on Friday?', 'Xafiisku ma furan yahay Jimcaha?'),
      ]),
      mistakes: [
        'Does ka dib base verb: does the class start, ma aha starts.',
        'From waxaa la socda to.',
      ],
    ),
    lessonExamples: l10e,
    lessonDialogues: twoDialogues(
      titleOne: 'Jadwalka casharka',
      questionOne: 'What time does English start?',
      questionOneSomali: 'Saacad imisa ayuu English-ku bilaabmaa?',
      answerOne: 'At eight o’clock.',
      answerOneSomali: 'Siddeedda saacad.',
      titleTwo: 'Kulanka shaqada',
      questionTwo: 'When is the work meeting?',
      questionTwoSomali: 'Goorma ayuu kulanka shaqadu yahay?',
      answerTwo: 'From two to three.',
      answerTwoSomali: 'Laba ilaa saddex.',
    ),
    fillQuestion: 'The lesson is ___ eight to nine.',
    fillOptions: ['at', 'on', 'from', 'after'],
    fillAnswer: 'from',
    conversionQuestion: 'English lesson 8:00–9:00 macnaheedu waa…',
    conversionOptions: [
      'from eight to nine',
      'at eight to ten',
      'from nine to eight',
      'after nine',
    ],
    conversionAnswer: 'from eight to nine',
    grammarQuestion: 'What time does the class ___?',
    grammarOptions: ['starts', 'start', 'starting', 'started'],
    grammarAnswer: 'start',
    mistakeQuestion: 'Sax “What time does the shop closes?”',
    mistakeOptions: [
      'What time does the shop close?',
      'What time do the shop closes?',
      'What time is shop close?',
      'What time the shop closes?',
    ],
    mistakeAnswer: 'What time does the shop close?',
    arrangeQuestion:
        'Kala hagaaji: ten / break / thirty / to / The / ten / is / fifteen / from',
    arrangeAnswer: 'The break is from ten fifteen to ten thirty.',
    readingQuestion:
        'Timetable: English 8:00–9:00; Mathematics 9:15–10:15; Break 10:15–10:30. Goormay break-ku dhammaataa?',
    readingOptions: ['9:00', '10:15', '10:30', '11:00'],
    readingAnswer: '10:30',
    dialogueQuestion: 'Kulanka shaqadu waa goorma?',
    dialogueOptions: ['8–9', '9:15–10:15', '10:15–10:30', '2–3'],
    dialogueAnswer: '2–3',
    speaking:
        'Akhri timetable-ka tusaalaha ah, kadib samee jadwal school ama work ah.',
    writing: 'Samee timetable shan saf leh: activity, day, start iyo finish.',
    summary:
        'Timetable-ku wuxuu muujinayaa activity, start iyo finish. From…to, before iyo after ayaa jadwalka isku xira.',
  );

  final l11e = examples([
    ('Are you free on Monday?', 'Ma bannaan tahay Isniinta?'),
    ('We can meet at ten.', 'Waxaan kulmi karnaa tobanka.'),
    ('I have an appointment at two.', 'Waxaan leeyahay ballan labada.'),
    ('The meeting is on Wednesday.', 'Kulanku waa Arbacada.'),
    ('See you tomorrow morning.', 'Waan is arki doonnaa berri subax.'),
    ('The interview is next week.', 'Wareysigu waa toddobaadka dambe.'),
  ]);
  final l11v = vocab([
    (
      word: 'Appointment',
      meaning: 'Ballan',
      pronunciation: 'a-point-ment',
      en: 'I have an appointment at two.',
      so: 'Waxaan leeyahay ballan labada.',
    ),
    (
      word: 'Meeting',
      meaning: 'Kulan',
      pronunciation: 'mii-ting',
      en: 'The meeting is on Wednesday.',
      so: 'Kulanku waa Arbacada.',
    ),
    (
      word: 'Class',
      meaning: 'Fasal/cashar',
      pronunciation: 'klaas',
      en: 'The class is at eight.',
      so: 'Casharku waa siddeedda.',
    ),
    (
      word: 'Exam',
      meaning: 'Imtixaan',
      pronunciation: 'ig-zaam',
      en: 'The exam is on Monday.',
      so: 'Imtixaanku waa Isniinta.',
    ),
    (
      word: 'Interview',
      meaning: 'Wareysi',
      pronunciation: 'in-tar-vyuu',
      en: 'The interview is next week.',
      so: 'Wareysigu waa toddobaadka dambe.',
    ),
    (
      word: 'Visit',
      meaning: 'Booqasho',
      pronunciation: 'vi-zit',
      en: 'The visit is on Friday.',
      so: 'Booqashadu waa Jimcaha.',
    ),
    (
      word: 'This week',
      meaning: 'Toddobaadkan',
      pronunciation: 'dhis wiik',
      en: 'I have a meeting this week.',
      so: 'Toddobaadkan kulan ayaan leeyahay.',
    ),
    (
      word: 'Next week',
      meaning: 'Toddobaadka dambe',
      pronunciation: 'nekst wiik',
      en: 'The exam is next week.',
      so: 'Imtixaanku waa toddobaadka dambe.',
    ),
    (
      word: 'Free',
      meaning: 'Bannaan/firaaqo ah',
      pronunciation: 'frii',
      en: 'Are you free on Monday?',
      so: 'Ma bannaan tahay Isniinta?',
    ),
    (
      word: 'Can meet',
      meaning: 'Kulmi karnaa',
      pronunciation: 'kan miit',
      en: 'We can meet at ten.',
      so: 'Waxaan kulmi karnaa tobanka.',
    ),
  ], type: 'appointment phrase');
  add(
    number: 11,
    titleEnglish: 'Appointments and Plans',
    titleSomali: 'Ballamaha iyo qorshayaasha waqtiga',
    description:
        'Bar ballan dhakhtar, kulan, cashar, imtixaan, wareysi iyo booqasho qaabab A1 ah.',
    objectives: [
      'Qof waqtigiisa bannaan weydii.',
      'Ballan day/time leh samee.',
      'This week iyo next week isticmaal.',
    ],
    type: 'speaking',
    minutes: 29,
    vocabulary: l11v,
    grammarTopic: grammar(
      titleEnglish: 'Simple appointment language',
      titleSomali: 'Qaababka fudud ee ballanta',
      explanation:
          'Are you free…?, We can meet… iyo I have an appointment… waa qaabab A1 ah. Future grammar qoto dheer looma baahna.',
      rule: 'Appointment/event + at + time / on + day / next week',
      structure: 'Are you free + on day? We can meet + at time.',
      examples: l11e,
      mistakes: [
        'Maalin: on Monday; saacad: at ten.',
        'Next week ka hor in/on looma baahna qaabkan.',
      ],
    ),
    lessonExamples: l11e,
    lessonDialogues: twoDialogues(
      titleOne: 'Ballan dhakhtar',
      questionOne: 'What time is your appointment?',
      questionOneSomali: 'Saacad imisa ayay ballantaadu tahay?',
      answerOne: 'At two this afternoon.',
      answerOneSomali: 'Labada galabta.',
      titleTwo: 'Kulan shaqo',
      questionTwo: 'Are you free on Wednesday?',
      questionTwoSomali: 'Ma bannaan tahay Arbacada?',
      answerTwo: 'Yes. We can meet at ten.',
      answerTwoSomali: 'Haa. Waxaan kulmi karnaa tobanka.',
    ),
    fillQuestion: 'The meeting is ___ Wednesday.',
    fillOptions: ['at', 'on', 'in', 'to'],
    fillAnswer: 'on',
    conversionQuestion: '“Toddobaadka dambe” waa…',
    conversionOptions: [
      'this week',
      'next week',
      'tomorrow morning',
      'yesterday',
    ],
    conversionAnswer: 'next week',
    grammarQuestion: 'We can meet ___ ten.',
    grammarOptions: ['at', 'on', 'in', 'from'],
    grammarAnswer: 'at',
    mistakeQuestion: 'Sax “The meeting is at Monday.”',
    mistakeOptions: [
      'The meeting is on Monday.',
      'The meeting is in Monday.',
      'The meeting is to Monday.',
      'The meeting on is Monday.',
    ],
    mistakeAnswer: 'The meeting is on Monday.',
    arrangeQuestion: 'Kala hagaaji: free / Monday / Are / on / you',
    arrangeAnswer: 'Are you free on Monday?',
    readingQuestion:
        '“Doctor: Monday 2:00; Work meeting: Wednesday 10:00.” Goormay ballanta dhakhtarku tahay?',
    readingOptions: [
      'Monday at two',
      'Wednesday at ten',
      'Monday at ten',
      'Friday at two',
    ],
    readingAnswer: 'Monday at two',
    dialogueQuestion: 'Kulanka shaqadu saacad imisa ayuu yahay?',
    dialogueOptions: ['Labada', 'Siddeedda', 'Tobanka', 'Laba iyo tobanka'],
    dialogueAnswer: 'Tobanka',
    speaking:
        'Samee role-play ballan dhakhtar, kulan shaqo ama macmiil; day iyo time ku dar.',
    writing:
        'Qor laba appointment dialogues, mid this week ah iyo mid next week ah.',
    summary:
        'Ballan: on + day, at + time. Qaababka A1: Are you free…? We can meet… I have an appointment….',
  );

  final l12e = examples([
    (
      'I study English on Sunday and Tuesday.',
      'Waxaan English bartaa Axad iyo Talaado.',
    ),
    (
      'My lesson starts at eight o’clock in the morning.',
      'Casharkaygu wuxuu bilaabmaa siddeedda subaxnimo.',
    ),
    (
      'I work from Monday to Thursday.',
      'Waxaan shaqeeyaa Isniin ilaa Khamiis.',
    ),
    ('On Friday, I visit my family.', 'Jimcaha, waxaan booqdaa qoyskayga.'),
    ('I usually rest in the evening.', 'Inta badan fiidkii waan nastaa.'),
    ('The meeting is on Wednesday at two.', 'Kulanku waa Arbacada labada.'),
  ]);
  final l12v = vocab([
    (
      word: 'My week',
      meaning: 'Toddobaadkayga',
      pronunciation: 'maay wiik',
      en: 'This is my week.',
      so: 'Kani waa toddobaadkayga.',
    ),
    (
      word: 'Study schedule',
      meaning: 'Jadwal waxbarasho',
      pronunciation: 'sta-di ske-jool',
      en: 'My study schedule starts on Sunday.',
      so: 'Jadwalkayga waxbarashadu wuxuu bilaabmaa Axadda.',
    ),
    (
      word: 'Work schedule',
      meaning: 'Jadwal shaqo',
      pronunciation: 'werk ske-jool',
      en: 'My work schedule is Monday to Thursday.',
      so: 'Jadwalkayga shaqadu waa Isniin ilaa Khamiis.',
    ),
    (
      word: 'From Monday to Thursday',
      meaning: 'Isniin ilaa Khamiis',
      pronunciation: 'from man-dey tu therz-dey',
      en: 'I work from Monday to Thursday.',
      so: 'Waxaan shaqeeyaa Isniin ilaa Khamiis.',
    ),
    (
      word: 'On Friday',
      meaning: 'Jimcaha',
      pronunciation: 'on fraay-dey',
      en: 'I visit family on Friday.',
      so: 'Waxaan qoyska booqdaa Jimcaha.',
    ),
    (
      word: 'At eight',
      meaning: 'Siddeedda',
      pronunciation: 'at eyt',
      en: 'My lesson starts at eight.',
      so: 'Casharkaygu wuxuu bilaabmaa siddeedda.',
    ),
    (
      word: 'In the morning',
      meaning: 'Subaxdii',
      pronunciation: 'in dha moor-ning',
      en: 'I study in the morning.',
      so: 'Subaxdii wax ayaan bartaa.',
    ),
    (
      word: 'In the evening',
      meaning: 'Fiidkii',
      pronunciation: 'in dhi iiv-ning',
      en: 'I rest in the evening.',
      so: 'Fiidkii waan nastaa.',
    ),
  ], type: 'weekly schedule phrase');
  add(
    number: 12,
    titleEnglish: 'Talking About Your Week',
    titleSomali: 'Ka hadalka toddobaadkaaga',
    description:
        'Isku dar days, times, parts of day, at/on/in iyo study/work schedule.',
    objectives: [
      'Toddobaad tusaale ah sharax.',
      'At/on/in sax u isticmaal.',
      '6–10 jumladood oo isku xiran qor.',
    ],
    type: 'writing',
    minutes: 31,
    vocabulary: l12v,
    grammarTopic: grammar(
      titleEnglish: 'A weekly paragraph',
      titleSomali: 'Faqrad toddobaadle ah',
      explanation:
          'Weekly paragraph-ku wuxuu isku daraa on + day, at + time, in + part of day iyo from…to. Present Simple ayaa jadwalka lagu sheegaa.',
      rule: 'on + day; at + time; in + part of day; from + day + to + day',
      structure: 'Subject + Present Simple activity + time expression',
      examples: l12e,
      mistakes: [
        'Preposition-ka ku salee nooca waqtiga.',
        'Days capital letter ku bilow.',
      ],
    ),
    lessonExamples: l12e,
    lessonDialogues: twoDialogues(
      titleOne: 'Jadwalka ardayga',
      questionOne: 'When do you study English?',
      questionOneSomali: 'Goorma ayaad English barataa?',
      answerOne: 'On Sunday and Tuesday at eight.',
      answerOneSomali: 'Axad iyo Talaado siddeedda.',
      titleTwo: 'Jadwalka shaqaalaha',
      questionTwo: 'What days do you work?',
      questionTwoSomali: 'Maalmahee ayaad shaqaysaa?',
      answerTwo: 'From Monday to Thursday.',
      answerTwoSomali: 'Isniin ilaa Khamiis.',
    ),
    fillQuestion: 'I visit my family ___ Friday.',
    fillOptions: ['at', 'on', 'in', 'from'],
    fillAnswer: 'on',
    conversionQuestion: '“Isniin ilaa Khamiis” waa…',
    conversionOptions: [
      'on Monday Thursday',
      'from Monday to Thursday',
      'in Monday at Thursday',
      'Monday before Thursday',
    ],
    conversionAnswer: 'from Monday to Thursday',
    grammarQuestion: 'My lesson starts ___ eight ___ the morning.',
    grammarOptions: ['on / at', 'at / in', 'in / on', 'from / to'],
    grammarAnswer: 'at / in',
    mistakeQuestion: 'Sax “I study in Sunday.”',
    mistakeOptions: [
      'I study on Sunday.',
      'I study at Sunday.',
      'I study to Sunday.',
      'I study Sunday in.',
    ],
    mistakeAnswer: 'I study on Sunday.',
    arrangeQuestion: 'Kala hagaaji: evening / usually / the / rest / I / in',
    arrangeAnswer: 'I usually rest in the evening.',
    readingQuestion:
        '“I study Sunday and Tuesday; I work Monday to Thursday; I visit family Friday.” Goormaan qoyska booqdaa?',
    readingOptions: ['Sunday', 'Tuesday', 'Thursday', 'Friday'],
    readingAnswer: 'Friday',
    dialogueQuestion: 'Ardaygu goormuu English bartaa?',
    dialogueOptions: [
      'Monday at ten',
      'Sunday and Tuesday at eight',
      'Friday at noon',
      'Thursday evening',
    ],
    dialogueAnswer: 'Sunday and Tuesday at eight',
    speaking:
        'Sharax toddobaad male-awaal ah 6–10 jumladood; study, work, visit iyo rest ku dar.',
    writing:
        'Qor paragraph 8 jumladood ah oo toddobaad tusaale ah; at/on/in iyo from/to isticmaal.',
    summary:
        'Toddobaadku wuxuu isku daraa on + day, at + time, in + part of day iyo from…to.',
  );

  final l13e = examples([
    ('It is quarter past eight.', 'Waa siddeedda iyo rubuc.'),
    ('It is twenty to nine.', 'Labaatan ayaa ka harsan sagaalka.'),
    ('The meeting is on Monday at ten.', 'Kulanku waa Isniinta tobanka.'),
    (
      'The course starts in September.',
      'Koorsadu waxay bilaabataa Sebteembar.',
    ),
    ('The exam is on 12 June.', 'Imtixaanku waa 12 Juun.'),
    (
      'I work from Monday to Thursday.',
      'Waxaan shaqeeyaa Isniin ilaa Khamiis.',
    ),
  ]);
  final l13v = vocab([
    (
      word: 'Clock reading',
      meaning: 'Akhrinta saacadda',
      pronunciation: 'klok rii-ding',
      en: 'Practice clock reading.',
      so: 'Ku celceli akhrinta saacadda.',
    ),
    (
      word: 'Past and to',
      meaning: 'Dhaafay iyo ka harsan',
      pronunciation: 'paast and tuu',
      en: 'Review past and to.',
      so: 'Dib u eeg past iyo to.',
    ),
    (
      word: 'Half and quarter',
      meaning: 'Nus iyo rubuc',
      pronunciation: 'haaf and kwoor-tar',
      en: 'Review half and quarter.',
      so: 'Dib u eeg nus iyo rubuc.',
    ),
    (
      word: 'Days recap',
      meaning: 'Dib-u-eegista maalmaha',
      pronunciation: 'deyz rii-kap',
      en: 'Name all days.',
      so: 'Magacow maalmaha oo dhan.',
    ),
    (
      word: 'Months recap',
      meaning: 'Dib-u-eegista bilaha',
      pronunciation: 'manths rii-kap',
      en: 'Name all months.',
      so: 'Magacow bilaha oo dhan.',
    ),
    (
      word: 'Date',
      meaning: 'Taariikh',
      pronunciation: 'deyt',
      en: 'Write the date.',
      so: 'Qor taariikhda.',
    ),
    (
      word: 'Ordinal number',
      meaning: 'Tiro kala horreyn',
      pronunciation: 'oor-di-nal nam-bar',
      en: 'First is an ordinal number.',
      so: 'First waa tiro kala horreyn.',
    ),
    (
      word: 'Time preposition',
      meaning: 'Erayga xiriiriya waqtiga',
      pronunciation: 'taaym pre-pa-zi-shan',
      en: 'Choose at, on or in.',
      so: 'Dooro at, on ama in.',
    ),
    (
      word: 'Timetable',
      meaning: 'Jadwal waqtiyeed',
      pronunciation: 'taaym-tey-bal',
      en: 'Read the timetable.',
      so: 'Akhri jadwalka.',
    ),
    (
      word: 'Appointment dialogue',
      meaning: 'Wada hadal ballan',
      pronunciation: 'a-point-ment daay-a-log',
      en: 'Complete the appointment dialogue.',
      so: 'Dhammaystir wada hadalka ballanta.',
    ),
  ], type: 'review term');
  add(
    number: 13,
    titleEnglish: 'Unit Review',
    titleSomali: 'Dib-u-eegista Unit 6',
    description:
        'Dib u eeg time, days, months, dates, at/on/in, timetables iyo appointments.',
    objectives: [
      'Dhammaan xirfadaha isku dar.',
      'Khaladaadka past/to iyo prepositions sax.',
      'Jadwal iyo ballan akhri.',
    ],
    type: 'review',
    minutes: 42,
    vocabulary: l13v,
    lessonExamples: l13e,
    lessonDialogues: twoDialogues(
      titleOne: 'Review saacadda',
      questionOne: 'What time is the meeting?',
      questionOneSomali: 'Saacad imisa ayuu kulanku yahay?',
      answerOne: 'At quarter past eight.',
      answerOneSomali: 'Siddeedda iyo rubuc.',
      titleTwo: 'Review taariikhda',
      questionTwo: 'When is the exam?',
      questionTwoSomali: 'Goorma ayuu imtixaanku yahay?',
      answerTwo: 'On 12 June.',
      answerTwoSomali: '12 Juun.',
    ),
    fillQuestion: 'The meeting is ___ Monday ___ ten.',
    fillOptions: ['in / on', 'on / at', 'at / in', 'from / to'],
    fillAnswer: 'on / at',
    conversionQuestion: '11:45 waa…',
    conversionOptions: [
      'quarter past eleven',
      'quarter to twelve',
      'half past eleven',
      'fifteen past twelve',
    ],
    conversionAnswer: 'quarter to twelve',
    grammarQuestion: 'The course starts ___ September.',
    grammarOptions: ['at', 'on', 'in', 'to'],
    grammarAnswer: 'in',
    mistakeQuestion: 'Sax “It is twenty to eight” haddii waqtigu yahay 8:40.',
    mistakeOptions: [
      'It is twenty to nine.',
      'It is twenty past nine.',
      'It is forty to eight.',
      'It is quarter to nine.',
    ],
    mistakeAnswer: 'It is twenty to nine.',
    arrangeQuestion:
        'Kala hagaaji: meeting / Monday / ten / on / at / is / The',
    arrangeAnswer: 'The meeting is on Monday at ten.',
    readingQuestion:
        'Timetable: English 8–9; Break 9–9:15; Math 9:15–10:15. Goormay Math dhammaataa?',
    readingOptions: ['9:00', '9:15', '10:00', '10:15'],
    readingAnswer: '10:15',
    dialogueQuestion: 'Review dialogue-ka: imtixaanku goormuu yahay?',
    dialogueOptions: ['5 June', '12 June', '21 June', '31 June'],
    dialogueAnswer: '12 June',
    speaking:
        'Akhri waqtiyo, magacow days/months, sheeg date, kadib appointment role-play samee.',
    writing: 'Qor timetable iyo paragraph toddobaadle ah oo at/on/in sax leh.',
    summary:
        'Waxaad dib u eegtay saacadda, past/to, half/quarter, days, months, dates, prepositions, schedules iyo appointments.',
    review: true,
  );

  final quiz = <Json>[
    exercise(
      'a1-u06-q01',
      'multipleChoice',
      '6:30 digital ahaan waxaa loo akhriyaa…',
      ['six thirteen', 'six thirty', 'thirty six', 'six forty'],
      'six thirty',
      '6:30 waa six thirty.',
    ),
    exercise(
      'a1-u06-q02',
      'multipleChoice',
      '8:15 waa…',
      ['eight fifty', 'eight fifteen', 'fifteen eight', 'eight forty-five'],
      'eight fifteen',
      '8:15 waa eight fifteen.',
    ),
    exercise(
      'a1-u06-q03',
      'multipleChoice',
      '12:00 maalintii waa…',
      ['midnight', 'noon', 'evening', 'night'],
      'noon',
      '12:00 maalintii waa noon.',
    ),
    exercise(
      'a1-u06-q04',
      'multipleChoice',
      '12:00 habeenkii waa…',
      ['noon', 'afternoon', 'midnight', 'morning'],
      'midnight',
      '12:00 habeenkii waa midnight.',
    ),
    exercise(
      'a1-u06-q05',
      'fillInTheBlank',
      'It is nine ___. (9:45)',
      ['fifteen', 'thirty', 'forty-five', 'fifty-four'],
      'forty-five',
      '9:45 waa nine forty-five.',
    ),
    exercise(
      'a1-u06-q06',
      'multipleChoice',
      'Su’aasha saxda ah ee saacaddu waa…',
      [
        'What day is it?',
        'What time is it?',
        'Where time is it?',
        'How time is it?',
      ],
      'What time is it?',
      'What time is it? ayaa saacadda weydiinaysa.',
    ),
    exercise(
      'a1-u06-q07',
      'multipleChoice',
      '6:05 waa…',
      ['five to six', 'five past six', 'six past five', 'quarter past six'],
      'five past six',
      'Shan daqiiqo ayaa lixda dhaafay.',
    ),
    exercise(
      'a1-u06-q08',
      'multipleChoice',
      '8:40 waa…',
      [
        'twenty past eight',
        'twenty to eight',
        'twenty to nine',
        'forty to nine',
      ],
      'twenty to nine',
      '20 daqiiqo ayaa ka harsan sagaalka.',
    ),
    exercise(
      'a1-u06-q09',
      'multipleChoice',
      '7:30 waa…',
      [
        'quarter past seven',
        'half past seven',
        'quarter to eight',
        'half to seven',
      ],
      'half past seven',
      '30 daqiiqo waa half past.',
    ),
    exercise(
      'a1-u06-q10',
      'multipleChoice',
      '9:45 waa…',
      [
        'quarter past nine',
        'quarter to nine',
        'quarter to ten',
        'half past nine',
      ],
      'quarter to ten',
      '15 daqiiqo ayaa ka harsan tobanka.',
    ),
    exercise(
      'a1-u06-q11',
      'multipleChoice',
      'Maalinta ka dambaysa Monday waa…',
      ['Sunday', 'Tuesday', 'Wednesday', 'Friday'],
      'Tuesday',
      'Tuesday ayaa ka dambaysa Monday.',
    ),
    exercise(
      'a1-u06-q12',
      'multipleChoice',
      'Maalinta ka hor Friday waa…',
      ['Wednesday', 'Thursday', 'Saturday', 'Sunday'],
      'Thursday',
      'Thursday ayaa ka horreysa Friday.',
    ),
    exercise(
      'a1-u06-q13',
      'multipleChoice',
      'Kee ayaa sax loo qoray?',
      ['wednesday', 'Wednesday', 'WEDnesday', 'wednesDay'],
      'Wednesday',
      'Day name wuxuu capital letter ku bilaabmaa.',
    ),
    exercise(
      'a1-u06-q14',
      'multipleChoice',
      'Today is Sunday. Tomorrow is…',
      ['Saturday', 'Monday', 'Tuesday', 'Friday'],
      'Monday',
      'Maalinta Axadda ka dambaysa waa Isniin.',
    ),
    exercise(
      'a1-u06-q15',
      'multipleChoice',
      'Bisha ka dambaysa August waa…',
      ['July', 'September', 'October', 'December'],
      'September',
      'September ayaa ka dambaysa August.',
    ),
    exercise(
      'a1-u06-q16',
      'multipleChoice',
      'Bisha labaad waa…',
      ['January', 'February', 'March', 'April'],
      'February',
      'February waa bisha labaad.',
    ),
    exercise(
      'a1-u06-q17',
      'multipleChoice',
      '21st waa…',
      ['twenty-one', 'twentieth', 'twenty-first', 'twenty-oneth'],
      'twenty-first',
      '21st waa twenty-first.',
    ),
    exercise(
      'a1-u06-q18',
      'multipleChoice',
      'Qaabka British-ka saxda ahi waa…',
      ['July 5, 2026', '5 July 2026', '2026 July 5 is', 'July 2026 fifth'],
      '5 July 2026',
      'Day + Month + Year waa British format.',
    ),
    exercise(
      'a1-u06-q19',
      'fillInTheBlank',
      'The class starts ___ eight.',
      ['at', 'on', 'in', 'to'],
      'at',
      'Saacad gaar ah: at.',
    ),
    exercise(
      'a1-u06-q20',
      'fillInTheBlank',
      'We meet ___ Monday.',
      ['at', 'on', 'in', 'from'],
      'on',
      'Maalin: on.',
    ),
    exercise(
      'a1-u06-q21',
      'fillInTheBlank',
      'The course starts ___ September.',
      ['at', 'on', 'in', 'to'],
      'in',
      'Bil: in.',
    ),
    exercise(
      'a1-u06-q22',
      'fillInTheBlank',
      'I study ___ the morning.',
      ['at', 'on', 'in', 'to'],
      'in',
      'In the morning.',
    ),
    exercise(
      'a1-u06-q23',
      'fillInTheBlank',
      'He sleeps ___ night.',
      ['at', 'on', 'in', 'from'],
      'at',
      'Exception-ka guud waa at night.',
    ),
    exercise(
      'a1-u06-q24',
      'readingComprehension',
      'Timetable: English 8:00–9:00; Math 9:15–10:15. Goormay English dhammaataa?',
      ['8:00', '9:00', '9:15', '10:15'],
      '9:00',
      'English-ku waa 8:00–9:00.',
    ),
    exercise(
      'a1-u06-q25',
      'readingComprehension',
      'Break: 10:15–10:30. Immisa daqiiqo ayay socotaa?',
      ['10', '15', '20', '30'],
      '15',
      '10:15 ilaa 10:30 waa 15 daqiiqo.',
    ),
    exercise(
      'a1-u06-q26',
      'readingComprehension',
      'Work meeting: 2:00–3:00. Goormuu bilaabmaa?',
      ['1:00', '2:00', '2:30', '3:00'],
      '2:00',
      'Kulanku wuxuu bilaabmaa 2:00.',
    ),
    exercise(
      'a1-u06-q27',
      'readingComprehension',
      'A: Are you free on Monday? B: Yes. We can meet at ten. Goormay kulmayaan?',
      ['Monday at eight', 'Monday at ten', 'Tuesday at ten', 'Friday at noon'],
      'Monday at ten',
      'Wada hadalku wuxuu sheegay Monday at ten.',
    ),
    exercise(
      'a1-u06-q28',
      'readingComprehension',
      'A: When is the exam? B: On 12 June. Imtixaanku goormuu yahay?',
      ['5 June', '12 June', '21 June', '12 July'],
      '12 June',
      'Jawaabtu waa on 12 June.',
    ),
    exercise(
      'a1-u06-q29',
      'somaliToEnglish',
      'U beddel: “Kulanku waa Isniinta tobanka.”',
      [
        'The meeting is in Monday on ten.',
        'The meeting is on Monday at ten.',
        'The meeting is at Monday in ten.',
        'The meeting on Monday is in ten.',
      ],
      'The meeting is on Monday at ten.',
      'Day: on Monday; time: at ten.',
    ),
    exercise(
      'a1-u06-q30',
      'somaliToEnglish',
      'U beddel: “Koorsadu waxay bilaabataa Sebteembar.”',
      [
        'The course starts at September.',
        'The course starts on September.',
        'The course starts in September.',
        'The course starts to September.',
      ],
      'The course starts in September.',
      'Month waxaa lala isticmaalaa in.',
    ),
  ];

  final unit = {
    'id': 'a1-u06',
    'levelId': 'A1',
    'unitNumber': 6,
    'titleEnglish': 'Time, Days and Months',
    'titleSomali': 'Waqtiga, Maalmaha iyo Bilaha',
    'introductionSomali':
        'Unit-kan waxaad ku baranaysaa saacadda, past/to, half/quarter, qaybaha maalinta, days, months, dates, at/on/in, timetables iyo appointments.',
    'requiredPreviousUnitId': 'a1-u05',
    'lessons': lessons,
    'unitQuiz': quiz,
    'passingScore': 70,
  };
  final output = const JsonEncoder.withIndent('  ').convert(unit);
  File('assets/content/a1/unit_06.json').writeAsStringSync('$output\n');
}
