import 'dart:convert';
import 'dart:io';

Map<String, dynamic> word(
  String english,
  String somali,
  String part,
  String pronunciation,
  String exampleEnglish,
  String exampleSomali,
  String explanation, [
  String mistake = '',
]) => {
  'englishWord': english,
  'somaliMeaning': somali,
  'partOfSpeech': part,
  'pronunciation': pronunciation,
  'exampleEnglish': exampleEnglish,
  'exampleSomali': exampleSomali,
  'explanationSomali': explanation,
  'commonMistakeSomali': mistake,
};

Map<String, String> example(String english, String somali) => {
  'english': english,
  'somali': somali,
};

Map<String, dynamic> exercise(
  String id,
  String type,
  String question,
  List<String> options,
  String answer,
  String explanation,
) => {
  'id': id,
  'type': type,
  'question': question,
  'options': options,
  'correctAnswer': answer,
  'explanationSomali': explanation,
};

Map<String, dynamic> lesson({
  required String id,
  required int number,
  required String englishTitle,
  required String somaliTitle,
  required String description,
  required List<String> objectives,
  required String type,
  required List<Map<String, dynamic>> vocabulary,
  required List<Map<String, String>> examples,
  required String speaking,
  required String writing,
  required String summary,
  required String previousId,
  required String fillQuestion,
  required String fillAnswer,
  required String arrangeQuestion,
  required String arrangeAnswer,
  required String truthQuestion,
  required String truthAnswer,
}) {
  final first = vocabulary.first;
  final second = vocabulary[1];
  final exercises = [
    exercise(
      '$id-p01',
      'multipleChoice',
      '“${first['englishWord']}” maxay ka dhigan tahay?',
      [
        first['somaliMeaning'] as String,
        second['somaliMeaning'] as String,
        'Tiro',
        'Meel',
      ],
      first['somaliMeaning'] as String,
      'Jawaabta saxda ahi waa “${first['somaliMeaning']}”; waa macnaha ${first['englishWord']} ee casharkan.',
    ),
    exercise(
      '$id-p02',
      'fillInTheBlank',
      fillQuestion,
      [fillAnswer, 'name', 'small', 'sound'],
      fillAnswer,
      'Erayga “$fillAnswer” ayaa jumladda macne sax ah siinaya.',
    ),
    exercise(
      '$id-p03',
      'matchWords',
      'Isku aadi ${second['englishWord']} iyo macnihiisa.',
      [
        second['somaliMeaning'] as String,
        first['somaliMeaning'] as String,
        'Salaan',
        'Mahadsanid',
      ],
      second['somaliMeaning'] as String,
      '${second['englishWord']} waxaa loola jeedaa ${second['somaliMeaning']}.',
    ),
    exercise(
      '$id-p04',
      'arrangeSentence',
      arrangeQuestion,
      const [],
      arrangeAnswer,
      'Kala horreynta saxda ahi waa “$arrangeAnswer”.',
    ),
    exercise(
      '$id-p05',
      'englishToSomali',
      'Turjun: ${examples.first['english']}',
      [
        examples.first['somali']!,
        examples[1]['somali']!,
        'Magacaygu waa Cali.',
        'Waxaan aadayaa suuqa.',
      ],
      examples.first['somali']!,
      'Turjumaadda saxda ahi waxay gudbinaysaa macnaha jumladda oo dhan.',
    ),
    exercise(
      '$id-p06',
      'somaliToEnglish',
      'U beddel English: ${examples[1]['somali']}',
      [
        examples[1]['english']!,
        examples.first['english']!,
        'I go to school.',
        'This is my phone.',
      ],
      examples[1]['english']!,
      'Jumladda “${examples[1]['english']}” ayaa si dabiici ah u gudbinaysa macnaha Soomaaliga.',
    ),
    exercise(
      '$id-p07',
      'trueFalse',
      truthQuestion,
      const ['True', 'False'],
      truthAnswer,
      truthAnswer == 'True'
          ? 'Weedhu waa sax marka la raaco waxa casharka lagu bartay.'
          : 'Weedhu waa khalad; dib u eeg xeerka iyo tusaalooyinka casharka.',
    ),
    exercise(
      '$id-p08',
      'speakingPrompt',
      speaking,
      const [],
      'Teacher review',
      'Si cod dheer u hadal. Ujeeddadu waa dhawaaq cad iyo kalsooni, mana aha xawaare.',
    ),
    exercise(
      '$id-p09',
      'shortWriting',
      writing,
      const [],
      'Teacher review',
      'Qoraalkaaga hubi: xaraf sax ah, kala horreyn sax ah iyo calaamadda dhammaadka.',
    ),
  ];
  return {
    'id': id,
    'levelId': 'A1',
    'unitId': 'a1-u01',
    'lessonNumber': number,
    'titleEnglish': englishTitle,
    'titleSomali': somaliTitle,
    'shortDescriptionSomali': description,
    'learningObjectives': objectives,
    'lessonType': type,
    'estimatedMinutes': type == 'review' ? 20 : 15,
    'difficulty': 'beginner',
    'isLocked': number != 1,
    'requiredPreviousLessonId': previousId.isEmpty ? null : previousId,
    'vocabulary': vocabulary,
    'grammar': null,
    'examples': examples,
    'practiceExercises': exercises,
    'speakingPractice': speaking,
    'writingPractice': writing,
    'summarySomali': summary,
    'quizQuestions': exercises.take(3).toList(),
  };
}

void main() {
  final lessons = [
    lesson(
      id: 'a1-u01-l01',
      number: 1,
      englishTitle: 'The English Alphabet',
      somaliTitle: 'Xarfaha English-ka',
      description:
          'English-ku wuxuu leeyahay 26 xaraf. Casharkan waxaad ku baranaysaa magaca xaraf kasta iyo sida xarfaha loogu kala hormariyo A ilaa Z.',
      objectives: const [
        'Aqoonso 26-ka xaraf ee English-ka.',
        'U akhri xarfaha A ilaa Z si tartiib ah.',
        'Kala saar magaca xarafka iyo dhawaaqa uu samayn karo.',
      ],
      type: 'vocabulary',
      previousId: '',
      vocabulary: [
        word(
          'Alphabet',
          'Xarfaha luqaddu ka kooban tahay',
          'noun',
          'al-fuh-bet',
          'The English alphabet has 26 letters.',
          'Xarfaha English-ku waa 26 xaraf.',
          'Alphabet waa ururka xarfaha loo isticmaalo qorista luqad.',
          'Ha u qaadan in alphabet uu yahay hal xaraf.',
        ),
        word(
          'Letter',
          'Xaraf',
          'noun',
          'let-er',
          'A is the first letter.',
          'A waa xarafka koowaad.',
          'Letter halkan wuxuu ka dhigan yahay xaraf, mana aha warqad boosto.',
        ),
        word(
          'Order',
          'Kala horreyn',
          'noun',
          'or-der',
          'Say the letters in order.',
          'Xarfaha u sheeg sida ay u kala horreeyaan.',
          'Order wuxuu tilmaamayaa sida wax loo kala hormariyay.',
        ),
      ],
      examples: [
        example('A comes before B.', 'A wuxuu ka horreeyaa B.'),
        example('Z is the last letter.', 'Z waa xarafka ugu dambeeya.'),
        example('My name starts with M.', 'Magacaygu wuxuu ka bilaabmaa M.'),
        example('Please say the alphabet.', 'Fadlan sheeg xarfaha English-ka.'),
        example(
          'This word has four letters.',
          'Eraygani wuxuu leeyahay afar xaraf.',
        ),
      ],
      speaking:
          'Si tartiib ah u sheeg A ilaa Z, kadib sheeg xarfaha magacaaga.',
      writing: 'Qor A ilaa Z hal mar adigoo kala fogaynaya xaraf kasta.',
      summary:
          'Waxaad baratay in English-ku leeyahay 26 xaraf oo ka bilaabma A kuna dhammaada Z. Magaca xarafka iyo dhawaaqiisa mararka qaarkood way kala duwan yihiin.',
      fillQuestion: 'The English alphabet has ___ letters.',
      fillAnswer: '26',
      arrangeQuestion: 'Kala hagaaji: letter / first / A / the / is',
      arrangeAnswer: 'A is the first letter.',
      truthQuestion: 'Z is the last letter of the English alphabet.',
      truthAnswer: 'True',
    ),
    lesson(
      id: 'a1-u01-l02',
      number: 2,
      englishTitle: 'Capital and Small Letters',
      somaliTitle: 'Xarfaha waaweyn iyo kuwa yaryar',
      description:
          'Xaraf kasta wuxuu leeyahay qaab weyn iyo qaab yar. Xarafka weyn waxaa lagu bilaabaa jumlad iyo magac qof ama meel.',
      objectives: const [
        'Isku aadi capital iyo small letters.',
        'Ku bilow jumlad xaraf weyn.',
        'Magacyada dadka iyo meelaha si sax ah u qor.',
      ],
      type: 'writing',
      previousId: 'a1-u01-l01',
      vocabulary: [
        word(
          'Capital letter',
          'Xaraf weyn',
          'noun',
          'kap-i-tl let-er',
          'Somalia starts with a capital S.',
          'Somalia waxay ku bilaabataa S weyn.',
          'Capital letter waxaa loo adeegsadaa bilowga jumlad iyo magacyo gaar ah.',
        ),
        word(
          'Small letter',
          'Xaraf yar',
          'noun',
          'smol let-er',
          'The small form of A is a.',
          'Qaabka yar ee A waa a.',
          'Small letters ayaa inta badan lagu qoraa erayada dhexdiisa.',
        ),
        word(
          'Sentence',
          'Jumlad',
          'noun',
          'sen-tens',
          'Start a sentence with a capital letter.',
          'Jumlad ku bilow xaraf weyn.',
          'Sentence waa erayo isu tegay oo fikrad dhammeystiran gudbiya.',
        ),
      ],
      examples: [
        example('My name is Amina.', 'Magacaygu waa Aamina.'),
        example('Mogadishu is a city.', 'Muqdisho waa magaalo.'),
        example('This is my book.', 'Kani waa buuggayga.'),
        example('Ali works in a bank.', 'Cali wuxuu ka shaqeeyaa bangi.'),
        example('The lesson starts now.', 'Casharku hadda ayuu bilaabmayaa.'),
      ],
      speaking:
          'Sheeg laba magac oo qof iyo laba magac oo meel ah; ku dhawaaq xarafka ay ku bilaabmaan.',
      writing:
          'Qor magacaaga, magaaladaada iyo laba jumladood. Hubi capital letters.',
      summary:
          'Capital letter waxaa lagu bilaabaa jumlad iyo magac gaar ah. Small letters waxaa lagu isticmaalaa inta kale ee erayada badankood.',
      fillQuestion: 'A sentence starts with a ___ letter.',
      fillAnswer: 'capital',
      arrangeQuestion: 'Kala hagaaji: is / Hargeisa / city / a',
      arrangeAnswer: 'Hargeisa is a city.',
      truthQuestion: 'A person’s name should start with a small letter.',
      truthAnswer: 'False',
    ),
    lesson(
      id: 'a1-u01-l03',
      number: 3,
      englishTitle: 'Vowels and Consonants',
      somaliTitle: 'Shaqallada iyo shibbanayaasha',
      description:
          'A, E, I, O iyo U waa vowels. Xarfaha kale waa consonants. Vowel-ku wuxuu muhiim u yahay samaynta dhawaaqa erayga.',
      objectives: const [
        'Magacow shanta vowel.',
        'Kala saar vowel iyo consonant.',
        'Ka hel vowels-ka ku jira eray fudud.',
      ],
      type: 'pronunciation',
      previousId: 'a1-u01-l02',
      vocabulary: [
        word(
          'Vowel',
          'Shaqal',
          'noun',
          'vau-uhl',
          'A is a vowel.',
          'A waa shaqal.',
          'Vowels-ka English-ku waa A, E, I, O iyo U.',
        ),
        word(
          'Consonant',
          'Shibbane',
          'noun',
          'kon-suh-nant',
          'B is a consonant.',
          'B waa shibbane.',
          'Consonant waa xaraf aan ka mid ahayn shanta vowel.',
        ),
        word(
          'Sound',
          'Dhawaaq',
          'noun',
          'saund',
          'Listen to the sound.',
          'Dhegayso dhawaaqa.',
          'Sound waa codka la maqlo marka xaraf ama eray la yiraahdo.',
        ),
      ],
      examples: [
        example('A is in apple.', 'A wuxuu ku jiraa apple.'),
        example('E is in egg.', 'E wuxuu ku jiraa egg.'),
        example('I is in ink.', 'I wuxuu ku jiraa ink.'),
        example('O is in orange.', 'O wuxuu ku jiraa orange.'),
        example('U is in umbrella.', 'U wuxuu ku jiraa umbrella.'),
      ],
      speaking:
          'Ku dhawaaq A, E, I, O, U, kadibna sheeg apple, egg, ink, orange iyo umbrella.',
      writing:
          'Qor shanta vowel, kadib ku wareeji vowels-ka ku jira magacaaga.',
      summary:
          'Shanta vowel waa A, E, I, O iyo U. 21-ka xaraf ee kale waa consonants. Labaduba waxay dhisaan erayada.',
      fillQuestion: 'A, E, I, O and U are ___.',
      fillAnswer: 'vowels',
      arrangeQuestion: 'Kala hagaaji: vowel / is / E / a',
      arrangeAnswer: 'E is a vowel.',
      truthQuestion: 'B is a vowel.',
      truthAnswer: 'False',
    ),
    lesson(
      id: 'a1-u01-l04',
      number: 4,
      englishTitle: 'Spelling Names',
      somaliTitle: 'Higaadinta magacyada',
      description:
          'Spelling waa in eray ama magac xaraf-xaraf loo sheego. Waxaa loo isticmaalaa telefoonka, xafiiska, bangiga iyo marka magaca la diiwaangelinayo.',
      objectives: const [
        'Magacaaga xaraf-xaraf u sheeg.',
        'Weydii qof sida magaciisa loo higgaadiyo.',
        'Si sax ah u qor magac la higgaadiyay.',
      ],
      type: 'speaking',
      previousId: 'a1-u01-l03',
      vocabulary: [
        word(
          'Spell',
          'Higgaadi',
          'verb',
          'spel',
          'Please spell your name.',
          'Fadlan higgaadi magacaaga.',
          'Spell waa inaad sheegto xaraf kasta oo erayga ku jira.',
        ),
        word(
          'Name',
          'Magac',
          'noun',
          'neym',
          'My name is Hassan.',
          'Magacaygu waa Xasan.',
          'Name waa magaca qof, meel ama shay lagu yaqaan.',
        ),
        word(
          'Repeat',
          'Ku celi',
          'verb',
          'ri-peat',
          'Please repeat the last letter.',
          'Fadlan ku celi xarafka ugu dambeeya.',
          'Repeat waxaa la yiraahdaa marka aad rabto in wax mar kale la sheego.',
        ),
      ],
      examples: [
        example(
          'How do you spell your name?',
          'Sidee baad u higgaadisaa magacaaga?',
        ),
        example(
          'Amina is A-M-I-N-A.',
          'Aamina waxaa loo higgaadiyaa A-M-I-N-A.',
        ),
        example('Please repeat the letter.', 'Fadlan ku celi xarafka.'),
        example(
          'My last name starts with A.',
          'Magacayga dambe wuxuu ka bilaabmaa A.',
        ),
        example('Is that M or N?', 'Kaasi ma M baa mise N?'),
      ],
      speaking:
          'Magacaaga saddex jeer higgaadi: si tartiib ah, si caadi ah, kadib adigoo jumlad ku bilaabaya “My name is…”.',
      writing:
          'Qor magacaaga iyo laba magac oo kale, kuna kala saar xarfaha xarriiq gaaban.',
      summary:
          'Markaad magac higgaadinayso, xaraf kasta si cad u sheeg. Waxaad oran kartaa “How do you spell…?” ama “Please repeat.”',
      fillQuestion: 'Please ___ your name.',
      fillAnswer: 'spell',
      arrangeQuestion: 'Kala hagaaji: spell / do / name / your / you / How',
      arrangeAnswer: 'How do you spell your name?',
      truthQuestion: 'Spelling means saying a word letter by letter.',
      truthAnswer: 'True',
    ),
    lesson(
      id: 'a1-u01-l05',
      number: 5,
      englishTitle: 'Basic English Sounds',
      somaliTitle: 'Dhawaaqyada aasaasiga ah ee English-ka',
      description:
          'Xarafku mararka qaarkood wuxuu leeyahay dhawaaq ka duwan magaciisa. Casharkan wuxuu ku barayaa dhawaaqyo bilow ah sida b, m, s, sh iyo th.',
      objectives: const [
        'Kala garo magaca xarafka iyo dhawaaqiisa.',
        'Ku celceli b, m, s, sh iyo th.',
        'Si tartiib ah u akhri erayo fudud.',
      ],
      type: 'pronunciation',
      previousId: 'a1-u01-l04',
      vocabulary: [
        word(
          'Pronounce',
          'Ku dhawaaq',
          'verb',
          'pruh-nauns',
          'Pronounce the word slowly.',
          'Erayga si tartiib ah ugu dhawaaq.',
          'Pronounce wuxuu ka hadlayaa sida eray afka looga yiraahdo.',
        ),
        word(
          'Listen',
          'Dhegayso',
          'verb',
          'lis-en',
          'Listen and repeat.',
          'Dhegayso oo ku celi.',
          'Listen waa inaad si feejigan codka u maqasho.',
        ),
        word(
          'Slowly',
          'Si tartiib ah',
          'adverb',
          'sloh-lee',
          'Speak slowly, please.',
          'Si tartiib ah u hadal, fadlan.',
          'Slowly wuxuu tilmaamayaa in aan wax degdeg loo samayn.',
        ),
      ],
      examples: [
        example(
          'B sounds like /b/ in book.',
          'B wuxuu leeyahay dhawaaqa /b/ ee book.',
        ),
        example(
          'M sounds like /m/ in milk.',
          'M wuxuu leeyahay dhawaaqa /m/ ee milk.',
        ),
        example(
          'S sounds like /s/ in school.',
          'S wuxuu leeyahay dhawaaqa /s/ ee school.',
        ),
        example('Sh is in shop.', 'Sh wuxuu ku jiraa shop.'),
        example('Th is in thank.', 'Th wuxuu ku jiraa thank.'),
      ],
      speaking:
          'Dhegayso maskax ahaan kadib ku celi: book, milk, school, shop, thank. Afkaaga si cad u dhaqaaji.',
      writing:
          'Qor b, m, s, sh iyo th; mid kasta agtiisa ku qor hal eray oo dhawaaqaas leh.',
      summary:
          'Magaca xarafku iyo dhawaaqiisu way kala duwanaan karaan. Dhegaysi iyo ku celcelin tartiib ah ayaa kaa caawinaya pronunciation-ka.',
      fillQuestion: 'Listen and ___ the word.',
      fillAnswer: 'repeat',
      arrangeQuestion: 'Kala hagaaji: slowly / word / the / Pronounce',
      arrangeAnswer: 'Pronounce the word slowly.',
      truthQuestion:
          'The name of a letter is always the same as its sound in a word.',
      truthAnswer: 'False',
    ),
    lesson(
      id: 'a1-u01-l06',
      number: 6,
      englishTitle: 'Unit Review',
      somaliTitle: 'Dib-u-eegista Unit-ka',
      description:
          'Casharkan wuxuu isku soo koobayaa alphabet-ka, capital iyo small letters, vowels, consonants, spelling iyo dhawaaqyada aasaasiga ah.',
      objectives: const [
        'Dib u sheeg 26-ka xaraf.',
        'Sax capital letters iyo vowels.',
        'Higgaadi magacyo oo ku dhawaaq erayo fudud.',
      ],
      type: 'review',
      previousId: 'a1-u01-l05',
      vocabulary: [
        word(
          'Review',
          'Dib-u-eegis',
          'noun',
          'ri-vyuu',
          'Let us review the unit.',
          'Aan dib u eegno unit-ka.',
          'Review waa ku noqoshada wixii la bartay si loo xoojiyo.',
        ),
        word(
          'Practice',
          'Ku celcelin',
          'noun',
          'prak-tis',
          'Practice the alphabet every day.',
          'Maalin kasta ku celceli alphabet-ka.',
          'Practice waa samaynta hawl marar badan si xirfaddu u fiicnaato.',
        ),
        word(
          'Correct',
          'Sax',
          'adjective',
          'kuh-rekt',
          'Choose the correct letter.',
          'Dooro xarafka saxda ah.',
          'Correct wuxuu tilmaamayaa jawaab aan khalad ahayn.',
        ),
      ],
      examples: [
        example('A is a capital letter.', 'A waa xaraf weyn.'),
        example('a is a small letter.', 'a waa xaraf yar.'),
        example('There are five vowels.', 'Waxaa jira shan vowel.'),
        example('Spell Ali: A-L-I.', 'Higgaadi Cali: A-L-I.'),
        example(
          'Listen and repeat the sound.',
          'Dhegayso oo ku celi dhawaaqa.',
        ),
      ],
      speaking:
          'Sheeg alphabet-ka, vowels-ka, kadib higgaadi magacaaga iyo magaca magaaladaada.',
      writing:
          'Qor 26-ka xaraf laba saf: capital letters iyo small letters. Hoosta ka qor shanta vowel.',
      summary:
          'Waxaad dib u eegtay dhammaan Unit 1. Hadda waa inaad aqoonsan kartaa xarfaha, higgaadin kartaa magac, kala saari kartaa vowels iyo consonants, kuna celcelin kartaa dhawaaqyada.',
      fillQuestion: 'There are ___ vowels in English.',
      fillAnswer: 'five',
      arrangeQuestion: 'Kala hagaaji: name / Spell / your',
      arrangeAnswer: 'Spell your name.',
      truthQuestion: 'English has 26 letters.',
      truthAnswer: 'True',
    ),
  ];

  final quiz = [
    exercise(
      'a1-u01-q01',
      'multipleChoice',
      'Immisa xaraf ayuu leeyahay English alphabet-ku?',
      ['24', '25', '26', '27'],
      '26',
      'English alphabet-ku wuxuu leeyahay 26 xaraf.',
    ),
    exercise(
      'a1-u01-q02',
      'multipleChoice',
      'Waa kee xarafka ugu horreeya?',
      ['A', 'B', 'Y', 'Z'],
      'A',
      'A waa xarafka ugu horreeya ee alphabet-ka.',
    ),
    exercise(
      'a1-u01-q03',
      'trueFalse',
      'Z is the last letter.',
      ['True', 'False'],
      'True',
      'Z waa xarafka ugu dambeeya.',
    ),
    exercise(
      'a1-u01-q04',
      'multipleChoice',
      'Kee ayaa ah capital letter?',
      ['m', 'n', 'M', 'o'],
      'M',
      'M waa qaabka weyn; m waa qaabka yar.',
    ),
    exercise(
      'a1-u01-q05',
      'fillInTheBlank',
      'A sentence starts with a ___ letter.',
      ['capital', 'small', 'last', 'silent'],
      'capital',
      'Jumlad waxaa lagu bilaabaa capital letter.',
    ),
    exercise(
      'a1-u01-q06',
      'multipleChoice',
      'Kee ayaa vowel ah?',
      ['B', 'E', 'M', 'S'],
      'E',
      'E wuxuu ka mid yahay A, E, I, O, U.',
    ),
    exercise(
      'a1-u01-q07',
      'multipleChoice',
      'Kee ayaa consonant ah?',
      ['A', 'I', 'O', 'T'],
      'T',
      'T ma aha vowel, sidaas darteed waa consonant.',
    ),
    exercise(
      'a1-u01-q08',
      'fillInTheBlank',
      'A, E, I, O and U are ___.',
      ['vowels', 'names', 'sentences', 'numbers'],
      'vowels',
      'Shantaas xaraf waa vowels-ka English-ka.',
    ),
    exercise(
      'a1-u01-q09',
      'multipleChoice',
      'Sidee loo higgaadiyaa “Ali”?',
      ['A-L-I', 'E-L-I', 'A-R-I', 'A-L-E'],
      'A-L-I',
      'Ali xarafihiisu waa A, L iyo I.',
    ),
    exercise(
      'a1-u01-q10',
      'arrangeSentence',
      'Kala hagaaji: spell / name / your / Please',
      const [],
      'Please spell your name.',
      'Qaabka dabiiciga ahi waa “Please spell your name.”',
    ),
    exercise(
      'a1-u01-q11',
      'englishToSomali',
      '“Repeat” maxay ka dhigan tahay?',
      ['Ku celi', 'Qor', 'Akhri', 'Tag'],
      'Ku celi',
      'Repeat waxaa loola jeedaa in wax mar kale la sameeyo ama la yiraahdo.',
    ),
    exercise(
      'a1-u01-q12',
      'somaliToEnglish',
      'Dooro English-ka “Dhegayso”.',
      ['Speak', 'Write', 'Listen', 'Spell'],
      'Listen',
      'Listen waa “dhegayso”.',
    ),
    exercise(
      'a1-u01-q13',
      'trueFalse',
      'A letter name and its sound are always identical.',
      ['True', 'False'],
      'False',
      'Magaca xarafka iyo dhawaaqiisa erayga mararka qaar way kala duwan yihiin.',
    ),
    exercise(
      'a1-u01-q14',
      'multipleChoice',
      'Eraygee ku bilaabma dhawaaqa /sh/?',
      ['shop', 'book', 'milk', 'name'],
      'shop',
      'Shop wuxuu ku bilaabmaa isku-dhafka sh.',
    ),
    exercise(
      'a1-u01-q15',
      'multipleChoice',
      'Maxaa fiican marka pronunciation la baranayo?',
      ['Dhegayso oo ku celi', 'Aad u degdeg', 'Ha hadlin', 'Xarfaha ka bood'],
      'Dhegayso oo ku celi',
      'Dhegaysi iyo ku celcelin ayaa dhisa dhawaaq cad.',
    ),
  ];

  final unit = {
    'id': 'a1-u01',
    'levelId': 'A1',
    'unitNumber': 1,
    'titleEnglish': 'Alphabet and Basic Sounds',
    'titleSomali': 'Xarfaha iyo dhawaaqyada aasaasiga ah',
    'introductionSomali':
        'Unit-kan wuxuu ku bilaabayaa aasaaska English-ka: 26-ka xaraf, qaabkooda weyn iyo yar, vowels iyo consonants, higgaadinta magacyada iyo dhawaaqyada bilowga ah.',
    'requiredPreviousUnitId': null,
    'lessons': lessons,
    'unitQuiz': quiz,
    'passingScore': 70,
  };

  const encoder = JsonEncoder.withIndent('  ');
  File('assets/content/a1/unit_01.json')
    ..createSync(recursive: true)
    ..writeAsStringSync('${encoder.convert(unit)}\n');
}
